# Generated by Django 4.2.29 on 2026-03-23 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import langcodes
import re
import semantic_version.django_fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_tigauser'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Device',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                        ('active', models.BooleanField(default=True, help_text='Inactive devices will not be sent notifications', verbose_name='Is active')),
                        ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                        ('device_id', models.CharField(blank=True, db_index=True, help_text='Unique device identifier', max_length=255, null=True, verbose_name='Device ID')),
                        ('active_session', models.BooleanField(default=False)),
                        ('registration_id', models.TextField(db_index=True, null=True, verbose_name='Registration token')),
                        ('manufacturer', models.CharField(blank=True, help_text='The manufacturer of the device.', max_length=128, null=True)),
                        ('model', models.CharField(blank=True, help_text='The end-user-visible name for the end product.', max_length=128, null=True)),
                        ('type', models.CharField(choices=[('ios', 'ios'), ('android', 'android'), ('web', 'web')], max_length=10, null=True)),
                        ('os_name', models.CharField(blank=True, help_text='Operating system of device from which this report was submitted.', max_length=64, null=True)),
                        ('os_version', models.CharField(blank=True, help_text='Operating system version of device from which this report was submitted.', max_length=16, null=True)),
                        ('os_locale', models.CharField(blank=True, help_text="The locale configured in the device following the BCP 47 standard in 'language' or 'language-region' format (e.g., 'en' for English, 'en-US' for English (United States), 'fr' for French). The language is a two-letter ISO 639-1 code, and the region is an optional two-letter ISO 3166-1 alpha-2 code.", max_length=16, null=True, validators=[langcodes.tag_is_valid])),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('last_login', models.DateTimeField(null=True)),
                        ('mobile_app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.mobileapp')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', related_query_name='fcmdevice', to='users.tigauser'))
                    ],
                    options={
                        'verbose_name': 'Device',
                        'verbose_name_plural': 'Devices',
                        'db_table': 'tigaserver_app_device',
                        'abstract': False,
                    },
                ),
                migrations.AddIndex(
                    model_name='device',
                    index=models.Index(fields=['device_id', 'user'], name='tigaserver__device__682815_idx'),
                ),
                migrations.AddConstraint(
                    model_name='device',
                    constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('registration_id__isnull', False), models.Q(('registration_id__exact', ''), _negated=True)), fields=('active', 'registration_id'), name='unique_active_registration_id'),
                ),
                migrations.AddConstraint(
                    model_name='device',
                    constraint=models.UniqueConstraint(condition=models.Q(('active_session', True), ('device_id__isnull', False), models.Q(('device_id__exact', ''), _negated=True)), fields=('active_session', 'device_id'), name='unique_active_session_device_id'),
                ),
                migrations.AddConstraint(
                    model_name='device',
                    constraint=models.UniqueConstraint(condition=models.Q(('device_id__isnull', False), ('user__isnull', False), models.Q(('device_id__exact', ''), _negated=True)), fields=('user', 'device_id'), name='unique_user_device_id'),
                ),
                migrations.AddConstraint(
                    model_name='device',
                    constraint=models.UniqueConstraint(condition=models.Q(('registration_id__isnull', False), ('user__isnull', False), models.Q(('registration_id__exact', ''), _negated=True)), fields=('user', 'registration_id'), name='unique_user_registration_id'),
                ),
                migrations.CreateModel(
                    name='HistoricalDevice',
                    fields=[
                        ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                        ('active', models.BooleanField(default=True, help_text='Inactive devices will not be sent notifications', verbose_name='Is active')),
                        ('device_id', models.CharField(blank=True, db_index=True, help_text='Unique device identifier', max_length=255, null=True, verbose_name='Device ID')),
                        ('registration_id', models.TextField(db_index=True, null=True, verbose_name='Registration token')),
                        ('manufacturer', models.CharField(blank=True, help_text='The manufacturer of the device.', max_length=128, null=True)),
                        ('model', models.CharField(blank=True, help_text='The end-user-visible name for the end product.', max_length=128, null=True)),
                        ('type', models.CharField(choices=[('ios', 'ios'), ('android', 'android'), ('web', 'web')], max_length=10, null=True)),
                        ('os_name', models.CharField(blank=True, help_text='Operating system of device from which this report was submitted.', max_length=64, null=True)),
                        ('os_version', models.CharField(blank=True, help_text='Operating system version of device from which this report was submitted.', max_length=16, null=True)),
                        ('os_locale', models.CharField(blank=True, help_text="The locale configured in the device following the BCP 47 standard in 'language' or 'language-region' format (e.g., 'en' for English, 'en-US' for English (United States), 'fr' for French). The language is a two-letter ISO 639-1 code, and the region is an optional two-letter ISO 3166-1 alpha-2 code.", max_length=16, null=True, validators=[langcodes.tag_is_valid])),
                        ('history_id', models.AutoField(primary_key=True, serialize=False)),
                        ('history_date', models.DateTimeField(db_index=True)),
                        ('history_change_reason', models.CharField(max_length=100, null=True)),
                        ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                        ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.tigauser')),
                        ('mobile_app', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.mobileapp')),
                    ],
                    options={
                        'verbose_name': 'historical Device',
                        'verbose_name_plural': 'historical Devices',
                        'db_table': 'tigaserver_app_historicaldevice',
                        'ordering': ('-history_date', '-history_id'),
                        'get_latest_by': ('history_date', 'history_id'),
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
                migrations.CreateModel(
                    name='MobileApp',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('package_name', models.CharField(max_length=128)),
                        ('package_version', semantic_version.django_fields.VersionField(coerce=False, max_length=32, partial=False, validators=[django.core.validators.RegexValidator(code='invalid_version', regex=re.compile('^(\\d+)\\.(\\d+)\\.(\\d+)(?:-([0-9a-zA-Z.-]+))?(?:\\+([0-9a-zA-Z.-]+))?$'))])),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'tigaserver_app_mobileapp',
                    },
                ),
                migrations.AddConstraint(
                    model_name='mobileapp',
                    constraint=models.UniqueConstraint(fields=('package_name', 'package_version'), name='unique_name_version'),
                ),
            ]
        ),
    ]
