# Generated by Django 4.2.3 on 2023-12-01 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flag",
            name="object_id",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="flaginstance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_flags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
