# Generated by Django 4.2.29 on 2026-03-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Taxon',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('path', models.CharField(max_length=255, unique=True)),
                        ('depth', models.PositiveIntegerField()),
                        ('numchild', models.PositiveIntegerField(default=0)),
                        ('rank', models.PositiveSmallIntegerField(choices=[(30, 'Class'), (40, 'Order'), (50, 'Family'), (60, 'Genus'), (61, 'Subgenus'), (70, 'Species complex'), (71, 'Species')])),
                        ('name', models.CharField(max_length=32, unique=True)),
                        ('is_relevant', models.BooleanField(db_index=True, default=False, help_text='Indicates if this taxon is relevant for the application. Will be shown first and will set task to conflict if final taxon is not this.')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('common_name', models.CharField(blank=True, max_length=64, null=True)),
                        ('common_name_en', models.CharField(blank=True, max_length=64, null=True)),
                        ('common_name_es', models.CharField(blank=True, max_length=64, null=True)),
                        ('common_name_ca', models.CharField(blank=True, max_length=64, null=True)),
                    ],
                    options={
                        'db_table': 'tigacrafting_taxon',
                        'verbose_name': 'taxon',
                        'verbose_name_plural': 'taxa',
                    },
                ),
                migrations.AddConstraint(
                    model_name='taxon',
                    constraint=models.UniqueConstraint(fields=('name', 'rank'), name='unique_name_rank'),
                ),
                migrations.AddConstraint(
                    model_name='taxon',
                    constraint=models.UniqueConstraint(condition=models.Q(('depth', 1)), fields=('depth',), name='unique_root'),
                ),
            ]
        )
    ]
