# Generated by Django 4.0.8 on 2023-01-23 09:21

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Absent'), (10, 'Introduced'), (20, 'Established')])),
                ('month', month.models.MonthField()),
            ],
            options={
                'verbose_name': 'monthly distribution',
                'verbose_name_plural': 'monthly distributions',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(choices=[(0, 'Domain'), (10, 'Kingdom'), (20, 'Phylum'), (30, 'Class'), (40, 'Order'), (50, 'Family'), (60, 'Genus'), (61, 'Subgenus'), (70, 'Species complex'), (71, 'Species')])),
                ('name', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('common_name', models.CharField(blank=True, max_length=64, null=True)),
                ('common_name_en', models.CharField(blank=True, max_length=64, null=True)),
                ('common_name_ca', models.CharField(blank=True, max_length=64, null=True)),
                ('common_name_es', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'taxon',
                'verbose_name_plural': 'taxa',
            },
        ),
        migrations.AddConstraint(
            model_name='taxon',
            constraint=models.UniqueConstraint(fields=('name', 'rank'), name='unique_name_rank'),
        ),
        migrations.AddField(
            model_name='monthlydistribution',
            name='boundary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='geo.boundary'),
        ),
        migrations.AddField(
            model_name='monthlydistribution',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='taxa.taxon'),
        ),
        migrations.AddConstraint(
            model_name='monthlydistribution',
            constraint=models.UniqueConstraint(fields=('boundary', 'taxon', 'month'), name='unique_taxon_boundary_month'),
        ),
    ]
