# Generated by Django 4.0.8 on 2023-03-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taxon',
            constraint=models.UniqueConstraint(condition=models.Q(('depth', 1)), fields=('depth',), name='unique_root'),
        ),
    ]
