# Generated by Django 4.2.3 on 2023-07-19 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
        ("taxa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciedistribution",
            name="boundary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="geo.boundary",
            ),
        ),
    ]
