# Generated by Django 4.2.3 on 2023-10-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxa", "0002_alter_speciedistribution_boundary"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="gbif_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
