# Generated by Django 4.2.3 on 2023-10-11 14:55

from django.db import migrations, models
import django.db.models.functions.datetime
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("taxa", "0004_taxon_updated_at_alter_taxon_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciedistribution",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="speciedistribution",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddConstraint(
            model_name="speciedistribution",
            constraint=models.CheckConstraint(
                check=models.Q(("created_at__lte", django.db.models.functions.datetime.Now())),
                name="taxa_speciedistribution_created_at_cannot_be_future_dated",
            ),
        ),
        migrations.AddConstraint(
            model_name="speciedistribution",
            constraint=models.CheckConstraint(
                check=models.Q(("updated_at__lte", django.db.models.functions.datetime.Now())),
                name="taxa_speciedistribution_updated_at_cannot_be_future_dated",
            ),
        ),
        migrations.AddConstraint(
            model_name="speciedistribution",
            constraint=models.CheckConstraint(
                check=models.Q(("updated_at__gte", models.F("created_at"))),
                name="taxa_speciedistribution_updated_at_must_be_after_created_at",
            ),
        ),
    ]
