# Generated by Django 4.2.3 on 2023-10-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxa", "0005_speciedistribution_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="gbif_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
