# Generated by Django 4.2.3 on 2023-11-09 15:53

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0002_alter_boundary_created_at_alter_boundary_updated_at_and_more"),
        ("taxa", "0006_alter_taxon_gbif_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalspeciedistribution",
            name="stats_summary",
            field=django_jsonform.models.fields.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="speciedistribution",
            name="stats_summary",
            field=django_jsonform.models.fields.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="historicalspeciedistribution",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Absent"), (10, "Reported"), (20, "Introduced"), (30, "Established")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="speciedistribution",
            name="boundary",
            field=models.ForeignKey(
                limit_choices_to={"numchild": 0},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="geo.boundary",
            ),
        ),
        migrations.AlterField(
            model_name="speciedistribution",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Absent"), (10, "Reported"), (20, "Introduced"), (30, "Established")],
                null=True,
            ),
        ),
    ]
