# Generated by Django 4.2.3 on 2023-11-30 15:42

from django.db import migrations, models
import django.db.models.functions.datetime
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("taxa", "0007_historicalspeciedistribution_stats_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciedistribution",
            name="status_since",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddConstraint(
            model_name="speciedistribution",
            constraint=models.CheckConstraint(
                check=models.Q(("status_since__lte", django.db.models.functions.datetime.Now())),
                name="status_since_cannot_be_future_dated",
            ),
        ),
    ]
