# Generated by Django 4.2.29 on 2026-03-20 14:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tigaserver_app', '0095_delete_award_delete_awardcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AwardCategory',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('category_label', models.TextField(help_text='Coded label for the translated version of the award. For instance award_good_picture. This code refers to strings in several languages')),
                        ('xp_points', models.IntegerField(help_text='Number of xp points associated to this kind of award')),
                        ('category_long_description', models.TextField(blank=True, default=None, help_text='Long description specifying conditions in which the award should be conceded', null=True)),
                    ],
                    options={
                        'db_table': 'tigaserver_app_awardcategory',
                    },
                ),
                migrations.CreateModel(
                    name='Award',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date_given', models.DateTimeField(default=datetime.datetime.now, help_text='Date in which the award was given')),
                        ('special_award_text', models.TextField(blank=True, default=None, help_text='Custom text for custom award', null=True)),
                        ('special_award_xp', models.IntegerField(blank=True, default=0, help_text='Custom xp awarded', null=True)),
                        ('category', models.ForeignKey(blank=True, help_text='Category to which the award belongs. Can be blank for arbitrary awards', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_awards', to='awards.awardcategory')),
                        ('expert', models.ForeignKey(blank=True, help_text='Expert that gave the award', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_awards', to=settings.AUTH_USER_MODEL)),
                        ('given_to', models.ForeignKey(help_text='User to which the notification was awarded. Usually this is the user that uploaded the report, but the report can be blank for special awards', on_delete=django.db.models.deletion.CASCADE, related_name='user_awards', to='tigaserver_app.tigauser')),
                        ('report', models.ForeignKey(blank=True, default=None, help_text='Report which the award refers to. Can be blank for arbitrary awards', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_award', to='tigaserver_app.report')),
                    ],
                    options={
                        'db_table': 'tigaserver_app_award',
                    },
                ),
            ],
        )
    ]
