# Generated by Django 4.2.29 on 2026-03-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tigauser'),
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='given_to',
            field=models.ForeignKey(help_text='User to which the notification was awarded. Usually this is the user that uploaded the report, but the report can be blank for special awards', on_delete=django.db.models.deletion.CASCADE, related_name='user_awards', to='users.tigauser'),
        ),
    ]
