# Generated by Django 4.2.29 on 2026-03-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('awards', '0002_alter_award_given_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='report',
            field=models.ForeignKey(blank=True, default=None, help_text='Report which the award refers to. Can be blank for arbitrary awards', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_award', to='reports.report'),
        ),
    ]
