# Generated by Django 4.2.3 on 2023-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("name_en", models.CharField(max_length=64, null=True, unique=True)),
                ("name_ca", models.CharField(max_length=64, null=True, unique=True)),
                ("name_es", models.CharField(max_length=64, null=True, unique=True)),
            ],
            options={
                "verbose_name": "disease",
                "verbose_name_plural": "diseases",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DiseaseVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "disease vector",
                "verbose_name_plural": "disease vectors",
                "ordering": ["taxon__name"],
            },
        ),
    ]
