# Generated by Django 4.0.8 on 2023-01-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('name_en', models.CharField(max_length=64, null=True, unique=True)),
                ('name_ca', models.CharField(max_length=64, null=True, unique=True)),
                ('name_es', models.CharField(max_length=64, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'disease',
                'verbose_name_plural': 'diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyDistribution',
            fields=[
            ],
            options={
                'verbose_name': 'monthly distribution',
                'verbose_name_plural': 'monthly distributions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taxa.monthlydistribution',),
        ),
        migrations.CreateModel(
            name='DiseaseVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseases', models.ManyToManyField(related_name='disease_vectors', to='epidemiology.disease')),
                ('taxon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disease_vector', to='taxa.taxon')),
            ],
            options={
                'verbose_name': 'disease vector',
                'verbose_name_plural': 'disease vectors',
                'ordering': ['taxon__name'],
            },
        ),
    ]
