# Generated by Django 4.0.8 on 2023-03-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0002_taxon_unique_root'),
        ('epidemiology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasevector',
            name='taxon',
            field=models.OneToOneField(limit_choices_to={'rank__gte': 70}, on_delete=django.db.models.deletion.CASCADE, related_name='disease_vector', to='taxa.taxon'),
        ),
    ]
