# Generated by Django 4.2.3 on 2023-07-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taxa", "0001_initial"),
        ("epidemiology", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseVectorDistribution",
            fields=[],
            options={
                "verbose_name": "disease vector distribution",
                "verbose_name_plural": "disease vectors distribution",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("taxa.speciedistribution",),
        ),
        migrations.AddField(
            model_name="diseasevector",
            name="diseases",
            field=models.ManyToManyField(
                related_name="disease_vectors", to="epidemiology.disease"
            ),
        ),
        migrations.AddField(
            model_name="diseasevector",
            name="taxon",
            field=models.OneToOneField(
                limit_choices_to={"rank__gte": 70},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disease_vector",
                to="taxa.taxon",
            ),
        ),
    ]
