# Generated by Django 4.2.3 on 2023-07-19 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxa", "0002_alter_speciedistribution_boundary"),
        ("epidemiology", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDiseaseVectorDistribution",
            fields=[],
            options={
                "verbose_name": "historical disease vector distribution",
                "verbose_name_plural": "historical disease vectors distribution",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("taxa.historicalspeciedistribution",),
        ),
    ]
