# Generated by Django 4.2.3 on 2023-07-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taxa", "0002_alter_speciedistribution_boundary"),
        ("epidemiology", "0003_historicaldiseasevectordistribution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diseasevector",
            name="id",
        ),
        migrations.AlterField(
            model_name="diseasevector",
            name="taxon",
            field=models.OneToOneField(
                limit_choices_to={"rank__gte": 70},
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="disease_vector",
                serialize=False,
                to="taxa.taxon",
            ),
        ),
    ]
