# Generated by Django 4.2.3 on 2024-10-18 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geo", "0003_location_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoundaryAuthorization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ("supervisor_exclusivity_days", models.PositiveSmallIntegerField(default=15)),
                ("members_only", models.BooleanField(default=False)),
                (
                    "boundary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="authorization", to="geo.boundary"
                    ),
                ),
            ],
            options={
                "verbose_name": "Boundary Authorization",
                "verbose_name_plural": "Boundary Authorizations",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("s", "Supervisor"), ("i", "Identificator"), ("v", "Viewer")],
                        db_index=True,
                        max_length=1,
                    ),
                ),
                (
                    "boundary_authorization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="authorization.boundaryauthorization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boundary_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="boundaryauthorization",
            name="users",
            field=models.ManyToManyField(through="authorization.BoundaryMembership", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name="boundarymembership",
            constraint=models.CheckConstraint(
                check=models.Q(("created_at__lte", django.db.models.functions.datetime.Now())),
                name="authorization_boundarymembership_created_at_cannot_be_future_dated",
            ),
        ),
        migrations.AddConstraint(
            model_name="boundarymembership",
            constraint=models.CheckConstraint(
                check=models.Q(("updated_at__lte", django.db.models.functions.datetime.Now())),
                name="authorization_boundarymembership_updated_at_cannot_be_future_dated",
            ),
        ),
        migrations.AddConstraint(
            model_name="boundarymembership",
            constraint=models.CheckConstraint(
                check=models.Q(("updated_at__gte", models.F("created_at"))),
                name="authorization_boundarymembership_updated_at_must_be_after_created_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="boundaryauthorization",
            constraint=models.CheckConstraint(
                check=models.Q(("created_at__lte", django.db.models.functions.datetime.Now())),
                name="authorization_boundaryauthorization_created_at_cannot_be_future_dated",
            ),
        ),
        migrations.AddConstraint(
            model_name="boundaryauthorization",
            constraint=models.CheckConstraint(
                check=models.Q(("updated_at__lte", django.db.models.functions.datetime.Now())),
                name="authorization_boundaryauthorization_updated_at_cannot_be_future_dated",
            ),
        ),
        migrations.AddConstraint(
            model_name="boundaryauthorization",
            constraint=models.CheckConstraint(
                check=models.Q(("updated_at__gte", models.F("created_at"))),
                name="authorization_boundaryauthorization_updated_at_must_be_after_created_at",
            ),
        ),
    ]
