from polymorphic.managers import PolymorphicManager

from mosquito_alert.geo.querysets import GeoLocatedPolymorphicModelQuerySet

ReportManager = PolymorphicManager.from_queryset(GeoLocatedPolymorphicModelQuerySet)
