# Generated by Django 4.0.8 on 2023-03-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('body_part', models.CharField(choices=[('HD', 'Head'), ('LA', 'Left arm'), ('RA', 'Right arm'), ('CT', 'Chest'), ('AB', 'Abdomen'), ('LL', 'Left leg'), ('RL', 'Right leg')], max_length=2)),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='individuals.individual')),
            ],
            options={
                'verbose_name': 'bite',
                'verbose_name_plural': 'bites',
            },
        ),
    ]
