# Generated by Django 4.0.8 on 2023-01-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individuals', '0001_initial'),
        ('bites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bite',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='individuals.individual'),
        ),
    ]
