# Generated by Django 4.2.29 on 2026-03-24 11:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mosquito_alert.reports.fields
import mosquito_alert.reports.models
import simple_history.models
import taggit.managers
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('geo', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
        ('users', '0003_tigauser'),
        ('tigaserver_app', '0105_delete_organizationpin'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Report',
                    fields=[
                        ('version_UUID', models.CharField(default=uuid.uuid4, help_text='UUID randomly generated on phone to identify each unique report version. Must be exactly 36 characters (32 hex digits plus 4 hyphens).', max_length=36, primary_key=True, serialize=False)),
                        ('version_number', models.SmallIntegerField(db_index=True, default=0, editable=False, help_text='-1 if deleted, otherwise 0.')),
                        ('report_id', models.CharField(db_index=True, default=mosquito_alert.reports.models.generate_report_id, help_text='4-digit alpha-numeric code generated on user phone to identify each unique report from that user. Digits should lbe randomly drawn from the set of all lowercase and uppercase alphabetic characters and 0-9, but excluding 0, o, and O to avoid confusion if we ever need user to be able to refer to a report ID in correspondence with MoveLab (as was previously the case when we had them sending samples).', max_length=4)),
                        ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the report was last modified')),
                        ('server_upload_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time on server when report uploaded. (Automatically generated by server.)')),
                        ('phone_upload_time', models.DateTimeField(editable=False, help_text="Date and time on phone when it uploaded fix. Format as ECMA 262 date time string (e.g. '2014-05-17T12:34:56.123+01:00'.")),
                        ('creation_time', models.DateTimeField(editable=False, help_text="Date and time on phone when first version of report was created. Format as ECMA 262 date time string (e.g. '2014-05-17T12:34:56.123+01:00'.")),
                        ('published_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Datetime when the report was published.', null=True)),
                        ('version_time', models.DateTimeField(help_text="Date and time on phone when this version of report was created. Format as ECMA 262 date time string (e.g. '2014-05-17T12:34:56.123+01:00'.")),
                        ('datetime_fix_offset', models.IntegerField(blank=True, default=None, editable=False, help_text="An integer representing the offset (in seconds) applied to the original datetime values for fixing. If None, it indicates that no information about the original time zone could be inferred or the timezone was already provided when posting the report. To retrieve the original values, use: original_value = current_value - datetime_fix_offset.Fields to apply (if necessary) are: 'phone_upload_time', 'creation_time' and 'version_time'.", null=True)),
                        ('type', models.CharField(choices=[('bite', 'Bite'), ('adult', 'Adult'), ('site', 'Breeding Site'), ('mission', 'Mission')], db_index=True, help_text="Type of report: 'adult', 'site', or 'mission'.", max_length=7)),
                        ('hide', models.BooleanField(db_index=True, default=False, help_text='Hide this report from public views?')),
                        ('location_choice', models.CharField(choices=[('current', "Current location detected by user's device"), ('selected', 'Location selected by user from map'), ('missing', 'No location choice submitted - should be used only for missions')], help_text="Did user indicate that report relates to current location of phone ('current') or to a location selected manually on the map ('selected')? Or is the choice missing ('missing')", max_length=8)),
                        ('current_location_lon', models.FloatField(blank=True, help_text="Longitude of user's current location. In decimal degrees.", null=True)),
                        ('current_location_lat', models.FloatField(blank=True, help_text="Latitude of user's current location. In decimal degrees.", null=True)),
                        ('selected_location_lon', models.FloatField(blank=True, help_text='Latitude of location selected by user on map. In decimal degrees.', null=True)),
                        ('selected_location_lat', models.FloatField(blank=True, help_text='Longitude of location selected by user on map. In decimal degrees.', null=True)),
                        ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                        ('timezone', timezone_field.fields.TimeZoneField(help_text='The timezone corresponding to the GPS of the report.', null=True)),
                        ('location_is_masked', models.BooleanField(default=False)),
                        ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                        ('note', models.TextField(blank=True, help_text='Note user attached to report.', null=True)),
                        ('nuts_2', models.CharField(blank=True, editable=False, max_length=4, null=True)),
                        ('nuts_3', models.CharField(blank=True, editable=False, max_length=5, null=True)),
                        ('package_name', models.CharField(blank=True, db_index=True, help_text='Name of tigatrapp package from which this report was submitted.', max_length=400, null=True)),
                        ('package_version', models.IntegerField(blank=True, db_index=True, help_text='Version number of tigatrapp package from which this report was submitted.', null=True)),
                        ('device_manufacturer', models.CharField(blank=True, help_text='Manufacturer of device from which this report was submitted.', max_length=200, null=True)),
                        ('device_model', models.CharField(blank=True, help_text='Model of device from which this report was submitted.', max_length=200, null=True)),
                        ('os', models.CharField(blank=True, help_text='Operating system of device from which this report was submitted.', max_length=200, null=True)),
                        ('os_version', models.CharField(blank=True, help_text='Operating system version of device from which this report was submitted.', max_length=200, null=True)),
                        ('os_language', models.CharField(blank=True, help_text='Language setting of operating system on device from which this report was submitted. 2-digit ISO-639-1 language code.', max_length=10, null=True)),
                        ('app_language', models.CharField(blank=True, help_text='Language setting, within tigatrapp, of device from which this report was submitted. 2-digit ISO-639-1 language code.', max_length=10, null=True)),
                        ('flipped', models.BooleanField(default=False, help_text='If true, indicates that the report type has been changed in the coarse filter')),
                        ('flipped_on', models.DateTimeField(blank=True, help_text='Timestamp of when the report was flipped', null=True)),
                        ('flipped_to', models.CharField(blank=True, help_text='Type it was flipped from, to type it was flipped to, separated by #        \n            For instance, if the report was and adult and flipped to storm_drain_water, this field would have the value adult#storm_drain_water\n        ', max_length=60, null=True)),
                        ('event_environment', models.CharField(blank=True, choices=[('indoors', 'Indoors'), ('outdoors', 'Outdoors'), ('vehicle', 'Inside vehicle')], help_text='The environment where the event took place.', max_length=16, null=True)),
                        ('event_moment', models.CharField(blank=True, choices=[('now', 'Now'), ('last_morning', 'Last morning'), ('last_midday', 'Last midday'), ('last_afternoon', 'Last afternoon'), ('last_night', 'Last night')], help_text='The moment of the day when the event took place.', max_length=32, null=True)),
                        ('bite_count', models.PositiveSmallIntegerField(blank=True, editable=False, help_text='Total number of bites reported.', null=True)),
                        ('head_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the head.', null=True)),
                        ('left_arm_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the left arm.', null=True)),
                        ('right_arm_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the right arm.', null=True)),
                        ('chest_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the chest.', null=True)),
                        ('left_leg_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the left leg.', null=True)),
                        ('right_leg_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the right leg.', null=True)),
                        ('user_perceived_mosquito_specie', models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The mosquito specie perceived by the user.', max_length=16, null=True)),
                        ('user_perceived_mosquito_thorax', models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The species of mosquito that the thorax resembles, according to the user.', max_length=16, null=True)),
                        ('user_perceived_mosquito_abdomen', models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The species of mosquito that the abdomen resembles, according to the user.', max_length=16, null=True)),
                        ('user_perceived_mosquito_legs', models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The species of mosquito that the leg resembles, according to the user.', max_length=16, null=True)),
                        ('breeding_site_type', models.CharField(blank=True, choices=[('basin', 'Basin'), ('bucket', 'Bucket'), ('fountain', 'Fountain'), ('small_container', 'Small container'), ('storm_drain', 'Storm Drain'), ('well', 'Well'), ('other', 'Other')], help_text='Breeding site type.', max_length=32, null=True)),
                        ('breeding_site_has_water', models.BooleanField(blank=True, help_text='Either if the user perceived water in the breeding site.', null=True)),
                        ('breeding_site_in_public_area', models.BooleanField(blank=True, help_text='Either if the breeding site is found in a public area.', null=True)),
                        ('breeding_site_has_near_mosquitoes', models.BooleanField(blank=True, help_text='Either if the user perceived mosquitoes near the breeding site (less than 10 meters).', null=True)),
                        ('breeding_site_has_larvae', models.BooleanField(blank=True, help_text='Either if the user perceived larvaes the breeding site.', null=True)),
                        ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.europecountry')),
                        ('device', models.ForeignKey(help_text='The device from where the report was sent.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_reports', to='devices.device')),
                        ('lau_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.laueurope')),
                        ('mobile_app', models.ForeignKey(help_text='The mobile app version from where the report was sent.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='devices.mobileapp')),
                        ('nuts_2_fk', models.ForeignKey(blank=True, limit_choices_to={'levl_code': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.nutseurope')),
                        ('nuts_3_fk', models.ForeignKey(blank=True, limit_choices_to={'levl_code': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.nutseurope')),
                        ('session', models.ForeignKey(blank=True, help_text='Session ID for session in which this report was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_reports', to='tigaserver_app.session')),
                        ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags you can add to a report to make them easier to find.', through='utils.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags')),
                        ('user', models.ForeignKey(help_text='user_UUID for the user sending this report. Must be exactly 36 characters (32 hex digits plus 4 hyphens) and user must have already registered this ID.', on_delete=django.db.models.deletion.PROTECT, related_name='user_reports', to='users.tigauser')),
                    ],
                    options={
                        'db_table': 'tigaserver_app_report',
                    },
                ),
                migrations.CreateModel(
                    name='ReportResponse',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('question_id', models.IntegerField(blank=True, help_text='Numeric identifier of the question.', null=True)),
                        ('question', models.CharField(help_text='Question that the user responded to.', max_length=1000)),
                        ('answer_id', models.IntegerField(blank=True, help_text='Numeric identifier of the answer.', null=True)),
                        ('answer', models.CharField(help_text='Answer that user selected.', max_length=1000)),
                        ('answer_value', models.CharField(blank=True, help_text='The value right now can contain 2 things: an integer representing the number or bites, or either a WKT representation of a point for a location answer. In all other cases, it will be blank', max_length=1000, null=True)),
                        ('report', models.ForeignKey(help_text='Report to which this response is associated.', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reports.report')),
                    ],
                    options={
                        'db_table': 'tigaserver_app_reportresponse',
                    },
                ),
                migrations.CreateModel(
                    name='Photo',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('photo', mosquito_alert.reports.fields.ProcessedImageField(help_text='Photo uploaded by user.', upload_to=mosquito_alert.reports.models.MakeImageUUID('tigapics'))),
                        ('hide', models.BooleanField(db_index=True, default=False, help_text='Hide this photo from public views?')),
                        ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                        ('report', models.ForeignKey(help_text='Report and version to which this photo is associated (36-digit report_UUID).', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.report')),
                    ],
                    options={
                        'db_table': 'tigaserver_app_photo',
                    },
                ),
                migrations.CreateModel(
                    name='HistoricalReport',
                    fields=[
                        ('version_UUID', models.CharField(db_index=True, default=uuid.uuid4, help_text='UUID randomly generated on phone to identify each unique report version. Must be exactly 36 characters (32 hex digits plus 4 hyphens).', max_length=36)),
                        ('report_id', models.CharField(db_index=True, default=mosquito_alert.reports.models.generate_report_id, help_text='4-digit alpha-numeric code generated on user phone to identify each unique report from that user. Digits should lbe randomly drawn from the set of all lowercase and uppercase alphabetic characters and 0-9, but excluding 0, o, and O to avoid confusion if we ever need user to be able to refer to a report ID in correspondence with MoveLab (as was previously the case when we had them sending samples).', max_length=4)),
                        ('creation_time', models.DateTimeField(editable=False, help_text="Date and time on phone when first version of report was created. Format as ECMA 262 date time string (e.g. '2014-05-17T12:34:56.123+01:00'.")),
                        ('published_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Datetime when the report was published.', null=True)),
                        ('datetime_fix_offset', models.IntegerField(blank=True, default=None, editable=False, help_text="An integer representing the offset (in seconds) applied to the original datetime values for fixing. If None, it indicates that no information about the original time zone could be inferred or the timezone was already provided when posting the report. To retrieve the original values, use: original_value = current_value - datetime_fix_offset.Fields to apply (if necessary) are: 'phone_upload_time', 'creation_time' and 'version_time'.", null=True)),
                        ('type', models.CharField(choices=[('bite', 'Bite'), ('adult', 'Adult'), ('site', 'Breeding Site'), ('mission', 'Mission')], db_index=True, help_text="Type of report: 'adult', 'site', or 'mission'.", max_length=7)),
                        ('location_choice', models.CharField(choices=[('current', "Current location detected by user's device"), ('selected', 'Location selected by user from map'), ('missing', 'No location choice submitted - should be used only for missions')], help_text="Did user indicate that report relates to current location of phone ('current') or to a location selected manually on the map ('selected')? Or is the choice missing ('missing')", max_length=8)),
                        ('current_location_lon', models.FloatField(blank=True, help_text="Longitude of user's current location. In decimal degrees.", null=True)),
                        ('current_location_lat', models.FloatField(blank=True, help_text="Latitude of user's current location. In decimal degrees.", null=True)),
                        ('selected_location_lon', models.FloatField(blank=True, help_text='Latitude of location selected by user on map. In decimal degrees.', null=True)),
                        ('selected_location_lat', models.FloatField(blank=True, help_text='Longitude of location selected by user on map. In decimal degrees.', null=True)),
                        ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                        ('timezone', timezone_field.fields.TimeZoneField(help_text='The timezone corresponding to the GPS of the report.', null=True)),
                        ('location_is_masked', models.BooleanField(default=False)),
                        ('note', models.TextField(blank=True, help_text='Note user attached to report.', null=True)),
                        ('nuts_2', models.CharField(blank=True, editable=False, max_length=4, null=True)),
                        ('nuts_3', models.CharField(blank=True, editable=False, max_length=5, null=True)),
                        ('package_version', models.IntegerField(blank=True, db_index=True, help_text='Version number of tigatrapp package from which this report was submitted.', null=True)),
                        ('event_environment', models.CharField(blank=True, choices=[('indoors', 'Indoors'), ('outdoors', 'Outdoors'), ('vehicle', 'Inside vehicle')], help_text='The environment where the event took place.', max_length=16, null=True)),
                        ('event_moment', models.CharField(blank=True, choices=[('now', 'Now'), ('last_morning', 'Last morning'), ('last_midday', 'Last midday'), ('last_afternoon', 'Last afternoon'), ('last_night', 'Last night')], help_text='The moment of the day when the event took place.', max_length=32, null=True)),
                        ('bite_count', models.PositiveSmallIntegerField(blank=True, editable=False, help_text='Total number of bites reported.', null=True)),
                        ('head_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the head.', null=True)),
                        ('left_arm_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the left arm.', null=True)),
                        ('right_arm_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the right arm.', null=True)),
                        ('chest_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the chest.', null=True)),
                        ('left_leg_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the left leg.', null=True)),
                        ('right_leg_bite_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the right leg.', null=True)),
                        ('user_perceived_mosquito_specie', models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The mosquito specie perceived by the user.', max_length=16, null=True)),
                        ('user_perceived_mosquito_thorax', models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The species of mosquito that the thorax resembles, according to the user.', max_length=16, null=True)),
                        ('user_perceived_mosquito_abdomen', models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The species of mosquito that the abdomen resembles, according to the user.', max_length=16, null=True)),
                        ('user_perceived_mosquito_legs', models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The species of mosquito that the leg resembles, according to the user.', max_length=16, null=True)),
                        ('breeding_site_type', models.CharField(blank=True, choices=[('basin', 'Basin'), ('bucket', 'Bucket'), ('fountain', 'Fountain'), ('small_container', 'Small container'), ('storm_drain', 'Storm Drain'), ('well', 'Well'), ('other', 'Other')], help_text='Breeding site type.', max_length=32, null=True)),
                        ('breeding_site_has_water', models.BooleanField(blank=True, help_text='Either if the user perceived water in the breeding site.', null=True)),
                        ('breeding_site_in_public_area', models.BooleanField(blank=True, help_text='Either if the breeding site is found in a public area.', null=True)),
                        ('breeding_site_has_near_mosquitoes', models.BooleanField(blank=True, help_text='Either if the user perceived mosquitoes near the breeding site (less than 10 meters).', null=True)),
                        ('breeding_site_has_larvae', models.BooleanField(blank=True, help_text='Either if the user perceived larvaes the breeding site.', null=True)),
                        ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('history_date', models.DateTimeField(db_index=True)),
                        ('history_change_reason', models.CharField(max_length=100, null=True)),
                        ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                        ('device', models.ForeignKey(blank=True, db_constraint=False, help_text='The device from where the report was sent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.device')),
                        ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.tigauser')),
                        ('lau_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geo.laueurope')),
                        ('mobile_app', models.ForeignKey(blank=True, db_constraint=False, help_text='The mobile app version from where the report was sent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.mobileapp')),
                        ('nuts_2_fk', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'levl_code': 2}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geo.nutseurope')),
                        ('nuts_3_fk', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'levl_code': 3}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geo.nutseurope')),
                    ],
                    options={
                        'db_table': 'tigaserver_app_historicaldevice',
                        'verbose_name': 'historical report',
                        'verbose_name_plural': 'historical reports',
                        'ordering': ('-history_date', '-history_id'),
                        'get_latest_by': ('history_date', 'history_id'),
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
                migrations.AddIndex(
                    model_name='report',
                    index=models.Index(fields=['user', 'type', 'report_id'], name='tigaserver__user_id_7343f3_idx'),
                ),
                migrations.AddIndex(
                    model_name='report',
                    index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('hide', False), ('location_is_masked', False), ('point__isnull', False), ('published_at__isnull', False)), fields=['published_at'], name='report_visible_published_idx'),
                ),
                migrations.AddConstraint(
                    model_name='report',
                    constraint=models.CheckConstraint(check=models.Q(models.Q(('deleted_at__isnull', True), ('version_number', 0)), models.Q(('deleted_at__isnull', False), ('version_number', -1)), _connector='OR'), name='version_number_constraint'),
                ),
                migrations.AddConstraint(
                    model_name='report',
                    constraint=models.CheckConstraint(check=models.Q(('published_at__isnull', True), models.Q(('hide', False), ('deleted_at__isnull', True), ('location_is_masked', False)), _connector='OR'), name='is_browsable_when_published'),
                ),
            ]
        )
    ]
