# Generated by Django 4.0.8 on 2023-01-23 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('individuals', '0002_initial'),
        ('bites', '0002_initial'),
        ('taxa', '0001_initial'),
        ('breeding_sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualreport',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='individuals.individual'),
        ),
        migrations.AddField(
            model_name='individualreport',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxa.taxon'),
        ),
        migrations.AddField(
            model_name='breedingsitereport',
            name='breeding_site',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='breeding_sites.breedingsite'),
        ),
        migrations.AddField(
            model_name='bitereport',
            name='bites',
            field=models.ManyToManyField(related_name='reports', to='bites.bite'),
        ),
    ]
