# Generated by Django 4.2.30 on 2026-06-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_session'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session ID for session in which this report was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_reports', to='users.session'),
        ),
    ]
