# Generated by Django 4.0.8 on 2023-07-14 08:34

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.datetime
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now)]),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(('created_at__lte', django.db.models.functions.datetime.Now())), name='created_at_cannot_be_future_dated'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(('observed_at__lte', django.db.models.expressions.F('created_at'))), name='observed_at_cannot_be_after_created_at'),
        ),
    ]
