# Generated by Django 4.2.3 on 2023-07-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taxa", "0001_initial"),
        ("breeding_sites", "0001_initial"),
        ("reports", "0001_initial"),
        ("bites", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualreport",
            name="taxon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="taxa.taxon",
            ),
        ),
        migrations.AddField(
            model_name="breedingsitereport",
            name="breeding_site",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="breeding_sites.breedingsite",
            ),
        ),
        migrations.AddField(
            model_name="bitereport",
            name="bites",
            field=models.ManyToManyField(related_name="reports", to="bites.bite"),
        ),
    ]
