# Generated by Django 4.2.3 on 2023-09-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individuals", "0001_initial"),
        ("reports", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individualreport",
            name="individual",
        ),
        migrations.AddField(
            model_name="individualreport",
            name="individuals",
            field=models.ManyToManyField(related_name="reports", to="individuals.individual"),
        ),
    ]
