# Generated by Django 4.0.8 on 2023-01-25 13:09

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='observed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now)]),
        ),
    ]
