# Generated by Django 4.2.30 on 2026-06-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='flipped',
        ),
        migrations.RemoveField(
            model_name='report',
            name='flipped_on',
        ),
        migrations.RemoveField(
            model_name='report',
            name='flipped_to',
        ),
    ]
