# Generated by Django 4.2.3 on 2023-10-09 15:01

from django.db import migrations, models
import django.db.models.functions.datetime
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_remove_individualreport_individual_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="report",
            name="created_at_cannot_be_future_dated",
        ),
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="observed_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                check=models.Q(("created_at__lte", django.db.models.functions.datetime.Now())),
                name="reports_report_created_at_cannot_be_future_dated",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                check=models.Q(("updated_at__lte", django.db.models.functions.datetime.Now())),
                name="reports_report_updated_at_cannot_be_future_dated",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                check=models.Q(("updated_at__gte", models.F("created_at"))),
                name="reports_report_updated_at_must_be_after_created_at",
            ),
        ),
    ]
