# Generated by Django 4.2.30 on 2026-10-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_flipped_remove_report_flipped_on_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('hide', False), ('location_is_masked', False), ('published_at__isnull', False)), fields=['country', 'type', 'server_upload_time'], name='report_stats_country_type_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('hide', False), ('location_is_masked', False), ('published_at__isnull', False)), fields=['nuts_2_fk', 'type', 'server_upload_time'], name='report_stats_nuts2_type_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('hide', False), ('location_is_masked', False), ('published_at__isnull', False)), fields=['nuts_3_fk', 'type', 'server_upload_time'], name='report_stats_nuts3_type_idx'),
        ),
    ]
