# Generated by Django 4.2.3 on 2023-10-11 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0004_remove_report_created_at_cannot_be_future_dated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="user",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
