# Generated by Django 4.2.3 on 2024-10-17 12:40

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
        ("reports", "0005_alter_report_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags you can add to a report to make them easier to find.",
                through="tags.UUIDTaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
