# Generated by Django 4.2.3 on 2024-10-18 09:46

from django.db import migrations
import mosquito_alert.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0006_alter_report_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="short_id",
            field=mosquito_alert.utils.fields.ShortIDField(editable=False, size=10),
        ),
    ]
