#!/usr/bin/python
import psycopg2

import psycopg2.extras
import sys

from openpyxl import Workbook
from openpyxl.compat import range
from openpyxl.utils import get_column_letter


# coordenades exemple 

# nord oest: 42.4388, 0.7992
# nord est: 42.2683, 3.2931
# sud oest: 41.3099, 0.4916
# sud est: 41.2439, 1.9363

def generar_excel(southwest_lon, southwest_lat, northeast_lon, northeast_lat):
	
	
	conn_string = "host='sigserver3.udg.edu' port='5434' dbname='mosquito2' user='mosquito' password='_p1234'"
	# Imprimir l'string de configuracio per a comprovar si ha funcionat be
	# print "Connecting to database\n	->%s" % (conn_string)
 
	conn = psycopg2.connect(conn_string)
 
	
	cursor = conn.cursor('notis', cursor_factory=psycopg2.extras.DictCursor)
    # select amb les tres taules relacionades
	cursor.execute('select * from map_aux_reports, tigaserver_app_notification, tigapublic_notificationcontent where  tigaserver_app_notification.report_id=map_aux_reports.version_uuid and tigaserver_app_notification.notification_content_id = tigapublic_notificationcontent.id  and lat <'+str(northeast_lat)+' and lat > '+str(southwest_lat)+' and lon > '+str(southwest_lon)+' and lon <'+str(northeast_lon)+'')
 

	rows = []
	row_count = 0
	for row in cursor:
		rows.append(row)
		
	
	excel_writer(rows)
		
		


    		
def excel_writer(rows):
	
	wb = Workbook()
	dest_filename = 'empty_book.xlsx'
	
	ws1 = wb.active
	ws1.title = "range names"
	
	

	for i in range(len(rows)):
		for j in range(len(rows[i])):
			if i == 1:
				d = ws1.cell(row=1, column=1, value="ID")
				d = ws1.cell(row=1, column=2, value="VERSION UUID")
				d = ws1.cell(row=1, column=3, value="OBSERVATION DATE")
				d = ws1.cell(row=1, column=4, value="LON")
				d = ws1.cell(row=1, column=5, value="LAT")
				d = ws1.cell(row=1, column=6, value="REF SYSTEM")
				d = ws1.cell(row=1, column=7, value="TYPE")
				d = ws1.cell(row=1, column=8, value="BREEDING SITE ANSWERS")
				d = ws1.cell(row=1, column=9, value="MOSQUITO ANSWERS VARYING")
				d = ws1.cell(row=1, column=10, value="EXPERT VALIDATED(boolean)")
				d = ws1.cell(row=1, column=11, value="EXPERT VALIDATION RESULT")
				d = ws1.cell(row=1, column=12, value="ID")
			else:
				d = ws1.cell(row=i+1, column=j+1, value=rows[i][j])
			#print rows[i][j]
	
	wb.save(filename = dest_filename)


northeast_lat = 42.2683
northeast_lon = 3.2931

southwest_lat = 41.3099
southwest_lon = 0.4916

generar_excel(southwest_lon, southwest_lat, northeast_lon, northeast_lat)


