# Generated by Django 4.2.29 on 2026-04-28 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from mosquito_alert.workspaces.models import WorkspaceMembership as WorkspaceMembershipModel

def populate_workspace(apps, schema_editor):
    Workspace = apps.get_model("workspaces", "Workspace")
    WorkspaceMembership = apps.get_model("workspaces", "WorkspaceMembership")
    EuropeCountry = apps.get_model("geo", "EuropeCountry")
    UserStat = apps.get_model("users", "UserStat")

    for country in EuropeCountry.objects.all():
        w = Workspace.objects.create(
            country=country,
            is_public=country.reports_can_be_published,
            supervisor_exclusivity_days=country.national_supervisor_report_expires_in,
        )
        # Add all users with stats in the country as members of the workspace
        user_ids = UserStat.objects.filter(native_of=country).values_list("user_id", flat=True)
        WorkspaceMembership.objects.bulk_create(
            [
                WorkspaceMembership(
                    workspace=w,
                    user_id=user_id,
                    role=WorkspaceMembershipModel.Role.ANNOTATOR,
                )
                for user_id in user_ids
            ],
            batch_size=1000,
        )

        # Add all users that are supervisors
        supervisor_ids = UserStat.objects.filter(national_supervisor_of=country).values_list("user_id", flat=True)
        WorkspaceMembership.objects.bulk_create(
            [
                WorkspaceMembership(
                    workspace=w,
                    user_id=user_id,
                    role=WorkspaceMembershipModel.Role.SUPERVISOR,
                )
                for user_id in supervisor_ids
            ],
            batch_size=1000,
            update_conflicts=True,
            update_fields=["role"],
            unique_fields=["user", "workspace"],
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, help_text='Whether the results of the workspace are visible to the public.')),
                ('supervisor_exclusivity_days', models.IntegerField(default=14, help_text='Number of days that a identification tasks in the queue is exclusively available to the supervisors.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='workspace', to='geo.europecountry')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('annotator', 'Annotator'), ('supervisor', 'Supervisor')], db_index=True, default='member', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(fields=('user', 'workspace'), name='unique_workspace_membership'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(help_text='Users who can access the workspace.', related_name='workspaces', through='workspaces.WorkspaceMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_workspace, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='WorkspaceCollaborationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewers', models.ManyToManyField(related_name='collaboration_groups', to=settings.AUTH_USER_MODEL)),
                ('workspaces', models.ManyToManyField(help_text='Workspaces that can collaborate with each other within this group.', related_name='collaboration_groups', to='workspaces.workspace')),
            ],
        ),
    ]
