# Generated by Django 4.2.29 on 2026-06-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='supervisor_exclusivity_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Number of days that a identification tasks in the queue is exclusively available to the supervisors.'),
        ),
    ]
