# Generated by Django 2.2.7 on 2021-03-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0006_auto_20210301_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acknowledgednotification',
            name='acknowledged',
        ),
    ]
