# Generated by Django 2.2.7 on 2021-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0011_auto_20210308_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcontent',
            name='body_html_native',
            field=models.TextField(blank=True, default=None, help_text='Expert comment, expanded and allows html, in the language indicated by the field native_locale', null=True),
        ),
        migrations.AddField(
            model_name='notificationcontent',
            name='native_locale',
            field=models.CharField(blank=True, help_text='Locale code for text in body_html_native and title_native', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationcontent',
            name='title_native',
            field=models.TextField(blank=True, default=None, help_text='Title of the comment, shown in non-detail view, in the language indicated by the field title_native', null=True),
        ),
        migrations.AddField(
            model_name='notificationtopic',
            name='topic_group',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Language topics'), (2, 'Country topics')], default=0, help_text='Your degree of belief that at least one photo shows a tiger mosquito breeding site', verbose_name='Group of topics'),
        ),
    ]
