# Generated by Django 2.2.7 on 2021-04-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0017_report_nuts_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='nuts_2',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
