# Generated by Django 2.2.7 on 2021-05-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0021_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='acknowledged',
            field=models.BooleanField(default=False, help_text='This is set to True through the public API, when the user signals that the message has been received'),
        ),
    ]
