# Generated by Django 2.2.7 on 2022-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0027_auto_20220204_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingData',
            fields=[
                ('user_UUID', models.CharField(help_text='User identifier uuid', max_length=36, primary_key=True, serialize=False)),
                ('class_value', models.CharField(max_length=60)),
                ('rank', models.IntegerField()),
                ('score_v2', models.IntegerField()),
                ('last_update', models.DateTimeField(blank=True, help_text='Last time ranking data was updated', null=True)),
            ],
        ),
    ]
