# Generated by Django 2.2.7 on 2022-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0029_auto_20220204_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='europecountry',
            name='last_crisis_report_n_update',
            field=models.DateTimeField(blank=True, help_text='Last time count was updated', null=True),
        ),
        migrations.AddField(
            model_name='europecountry',
            name='pending_crisis_reports',
            field=models.IntegerField(blank=True, help_text='Number of reports in country assignable to non-supervisors', null=True),
        ),
    ]
