# Generated by Django 2.2.7 on 2022-04-25 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0030_auto_20220317_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ia_filter_1',
            field=models.FloatField(blank=True, default=None, help_text='Value ranging from -1.0 to 1.0 positive values indicate possible insect, negative values indicate spam(non-insect)', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ia_filter_2',
            field=models.FloatField(blank=True, default=None, help_text='Score for best classified image. 0 indicates not classified, 1.xx indicates classified with score xx, 2.xx classified with alert with score xx. ', null=True),
        ),
        migrations.CreateModel(
            name='IAScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1_c1', models.FloatField(blank=True, help_text='Score for filter 1, class 1', null=True)),
                ('f1_c2', models.FloatField(blank=True, help_text='Score for filter 1, class 2', null=True)),
                ('f2_c1', models.FloatField(blank=True, help_text='Score for filter 2, class 1', null=True)),
                ('f2_c2', models.FloatField(blank=True, help_text='Score for filter 2, class 2', null=True)),
                ('f3_c1', models.FloatField(blank=True, help_text='Score for filter 3, class 1', null=True)),
                ('f3_c2', models.FloatField(blank=True, help_text='Score for filter 3, class 2', null=True)),
                ('f4_c1', models.FloatField(blank=True, help_text='Score for filter 4, class 1', null=True)),
                ('f4_c2', models.FloatField(blank=True, help_text='Score for filter 4, class 2', null=True)),
                ('f5_c1', models.FloatField(blank=True, help_text='Score for filter 5, class 1', null=True)),
                ('f5_c2', models.FloatField(blank=True, help_text='Score for filter 5, class 2', null=True)),
                ('f6_c1', models.FloatField(blank=True, help_text='Score for filter 6, class 1', null=True)),
                ('f6_c2', models.FloatField(blank=True, help_text='Score for filter 6, class 2', null=True)),
                ('f7_c1', models.FloatField(blank=True, help_text='Score for filter 7, class 1', null=True)),
                ('f7_c2', models.FloatField(blank=True, help_text='Score for filter 7, class 2', null=True)),
                ('f8_c1', models.FloatField(blank=True, help_text='Score for filter 8, class 1', null=True)),
                ('f8_c2', models.FloatField(blank=True, help_text='Score for filter 8, class 2', null=True)),
                ('f9_c1', models.FloatField(blank=True, help_text='Score for filter 9, class 1', null=True)),
                ('f9_c2', models.FloatField(blank=True, help_text='Score for filter 9, class 2', null=True)),
                ('x_tl', models.IntegerField(default=0, help_text='photo bounding box coordinates top left x')),
                ('x_br', models.IntegerField(default=0, help_text='photo bounding box coordinates bottom right x')),
                ('y_tl', models.IntegerField(default=0, help_text='photo bounding box coordinates top left y')),
                ('y_br', models.IntegerField(default=0, help_text='photo bounding box coordinates bottom right y')),
                ('photo', models.ForeignKey(help_text='Photo to which the score refers to', on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_iascore', to='tigaserver_app.Photo')),
                ('report', models.ForeignKey(help_text='Report which the score refers to.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_iascore', to='tigaserver_app.Report')),
            ],
        ),
    ]
