# Generated by Django 2.2.7 on 2022-05-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0033_photo_blood_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='blood_genre',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('fblood', 'Female blood'), ('dk', 'Dont know')], default='dk', max_length=20),
        ),
    ]
