# Generated by Django 2.2.7 on 2022-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0034_auto_20220530_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='blood_genre',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('fblood', 'Female blood'), ('dk', 'Dont know')], default=None, max_length=20, null=True),
        ),
    ]
