# Generated by Django 2.2.7 on 2022-06-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0036_auto_20220613_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_label',
            field=models.CharField(blank=True, default=None, help_text='Arbitrary label used to group thematically equal notifications. Optional. ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='blood_genre',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('fblood', 'Female blood'), ('fgravid', 'Female gravid'), ('fgblood', 'Female gravid + blood')], default=None, max_length=20, null=True),
        ),
    ]
