# Generated by Django 2.2.7 on 2024-10-31 11:10

from django.db import migrations
import imagekit.models.fields
import mosquito_alert.reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0058_report_ordering_server_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=mosquito_alert.reports.fields.ProcessedImageField(help_text='Photo uploaded by user.', upload_to=mosquito_alert.reports.models.MakeImageUUID('tigapics')),
        ),
    ]
