# Generated by Django 3.2.25 on 2024-12-18 16:05


from django.db import migrations, models


def fix_duplicate_active_registration_id(apps, schema_editor):
    Device = apps.get_model('tigaserver_app', 'Device')

    last_logged_in_active_device_qs = Device.objects.filter(
        active=True,
        registration_id=models.OuterRef('registration_id'),
    ).order_by('-last_login', '-date_created').values('pk')[:1]

    Device.objects.filter(active=True).exclude(pk__in=last_logged_in_active_device_qs).update(active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0075_fix_device'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_id__isnull', False), ('user__isnull', False), models.Q(('registration_id__exact', ''), _negated=True)), fields=('user', 'registration_id'), name='unique_user_registration_id'),
        ),
        migrations.RunPython(fix_duplicate_active_registration_id, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('registration_id__isnull', False), models.Q(('registration_id__exact', ''), _negated=True)), fields=('active', 'registration_id'), name='unique_active_registration_id'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('device_id__isnull', False), ('is_logged_in', True), models.Q(('device_id__exact', ''), _negated=True)), fields=('is_logged_in', 'device_id'), name='unique_is_logged_in_device_id'),
        ),
    ]
