# Generated by Django 3.2.25 on 2025-03-27 10:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion

def populate_lau_fk(apps, schema_editor):
    Report = apps.get_model('tigaserver_app', 'Report')
    HistoricalReport = apps.get_model("tigaserver_app", "HistoricalReport")
    LauEurope = apps.get_model("tigaserver_app", "LauEurope")

    Report.objects.filter(point__isnull=False).update(
        lau_fk=models.Subquery(
            LauEurope.objects.filter(geom__contains=models.OuterRef('point')).values('pk')[:1]
        )
    )

    HistoricalReport.objects.filter(point__isnull=False).update(
        lau_fk=models.Subquery(
            LauEurope.objects.filter(geom__contains=models.OuterRef('point')).values('pk')[:1]
        )
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0080_report_nuts_fk_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LauEurope',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('lau_id', models.CharField(max_length=13)),
                ('lau_name', models.CharField(max_length=80)),
                ('gisco_id', models.CharField(blank=True, max_length=16, null=True)),
                ('cntr_id', models.CharField(blank=True, max_length=2, null=True)),
                ('fid', models.CharField(max_length=16, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'lau_rg_01m_2018_4326',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='lau_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tigaserver_app.laueurope'),
        ),
        migrations.AddField(
            model_name='report',
            name='lau_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tigaserver_app.laueurope'),
        ),
        migrations.RunPython(populate_lau_fk, migrations.RunPython.noop)
    ]
