# Generated by Django 4.1.13 on 2026-01-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0089_alter_historicaldevice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='europecountry',
            name='last_crisis_report_n_update',
        ),
        migrations.RemoveField(
            model_name='europecountry',
            name='pending_crisis_reports',
        ),
    ]
