# Generated by Django 4.2.29 on 2026-03-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0094_alter_tigauser_locale'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Award',
                ),
                migrations.DeleteModel(
                    name='AwardCategory',
                ),
            ]
        )
    ]
