# Generated by Django 4.2.29 on 2026-03-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0095_delete_award_delete_awardcategory'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='RankingData',
                ),
            ]
        )
    ]
