# Generated by Django 4.2.29 on 2026-03-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('tigaserver_app', '0096_delete_rankingdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreport',
            name='lau_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geo.laueurope'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='nuts_2_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'levl_code': 2}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geo.nutseurope'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='nuts_3_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'levl_code': 3}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geo.nutseurope'),
        ),
        migrations.AlterField(
            model_name='owcampaigns',
            name='country',
            field=models.ForeignKey(help_text='Country in which the campaign is taking place', on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='geo.europecountry'),
        ),
        migrations.AlterField(
            model_name='report',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.europecountry'),
        ),
        migrations.AlterField(
            model_name='report',
            name='lau_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.laueurope'),
        ),
        migrations.AlterField(
            model_name='report',
            name='nuts_2_fk',
            field=models.ForeignKey(blank=True, limit_choices_to={'levl_code': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.nutseurope'),
        ),
        migrations.AlterField(
            model_name='report',
            name='nuts_3_fk',
            field=models.ForeignKey(blank=True, limit_choices_to={'levl_code': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.nutseurope'),
        ),
    ]
