# Generated by Django 4.2.29 on 2026-03-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userstat_national_supervisor_of_and_more'),
        ('tigaserver_app', '0097_remove_nutseurope_europecountry_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='EuropeCountry',
                ),
                migrations.DeleteModel(
                    name='LauEurope',
                ),
                migrations.DeleteModel(
                    name='NutsEurope',
                ),
            ]
        )
    ]
