# Generated by Django 4.2.29 on 2026-03-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tigauser'),
        ('awards', '0002_alter_award_given_to'),
        ('tigaserver_app', '0098_delete_europecountry_delete_laueurope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgednotification',
            name='user',
            field=models.ForeignKey(help_text='User which has acknowledged the notification', on_delete=django.db.models.deletion.CASCADE, related_name='user_acknowledgements', to='users.tigauser'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', related_query_name='fcmdevice', to='users.tigauser'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.tigauser'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.tigauser'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tigauser'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(help_text='user_UUID for the user sending this report. Must be exactly 36 characters (32 hex digits plus 4 hyphens) and user must have already registered this ID.', on_delete=django.db.models.deletion.PROTECT, related_name='user_reports', to='users.tigauser'),
        ),
        migrations.AlterField(
            model_name='sentnotification',
            name='sent_to_user',
            field=models.ForeignKey(blank=True, help_text='User to which the notification was sent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sentnotifications', to='users.tigauser'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(help_text='user_UUID for the user sending this report. Must be exactly 36 characters (32 hex digits plus 4 hyphens) and user must have already registered this ID.', on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='users.tigauser'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(help_text='User which is subscribed to the topic', on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='users.tigauser'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='TigaUser',
                ),
            ]
        )
    ]
