# Generated by Django 4.2.29 on 2026-03-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '__first__'),
        ('tigaserver_app', '0099_alter_acknowledgednotification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreport',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The device from where the report was sent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='mobile_app',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The mobile app version from where the report was sent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.mobileapp'),
        ),
        migrations.AlterField(
            model_name='report',
            name='device',
            field=models.ForeignKey(help_text='The device from where the report was sent.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_reports', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mobile_app',
            field=models.ForeignKey(help_text='The mobile app version from where the report was sent.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='devices.mobileapp'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Device',
                ),
                migrations.DeleteModel(
                    name='HistoricalDevice',
                ),
                migrations.DeleteModel(
                    name='MobileApp',
                ),
            ]
        )
    ]
