# Generated by Django 4.2.29 on 2026-03-24 08:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('utils', '0001_initial'),
        ('tigaserver_app', '0100_remove_historicaldevice_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags you can add to a report to make them easier to find.', through='utils.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='UUIDTaggedItem',
                ),
            ]
        ),
    ]
