# Generated by Django 4.2.29 on 2026-03-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0101_alter_report_tags_delete_uuidtaggeditem'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='AcknowledgedNotification',
                ),
                migrations.DeleteModel(
                    name='Notification',
                ),
                migrations.DeleteModel(
                    name='NotificationContent',
                ),
                migrations.DeleteModel(
                    name='NotificationTopic',
                ),
                migrations.DeleteModel(
                    name='SentNotification',
                ),
                migrations.DeleteModel(
                    name='UserSubscription',
                ),
            ]
        )
    ]
