# Generated by Django 4.2.29 on 2026-03-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0102_remove_notification_expert_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='CoverageAreaMonth',
                ),
                migrations.DeleteModel(
                    name='Fix',
                ),
            ]
        )
    ]
