# Generated by Django 4.2.29 on 2026-03-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0104_delete_owcampaigns'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='OrganizationPin',
                ),
            ]
        )
    ]
