# Generated by Django 4.2.29 on 2026-03-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_award_report'),
        ('notifications', '0002_alter_notification_report'),
        ('identification_tasks', '0002_alter_expertreportannotation_best_photo_and_more'),
        ('tigaserver_app', '0105_delete_organizationpin'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='HistoricalReport',
                ),
                migrations.DeleteModel(
                    name='Photo',
                ),
                migrations.DeleteModel(
                    name='Report',
                ),
                migrations.DeleteModel(
                    name='ReportResponse',
                ),
            ]
        )
    ]
