# Generated by Django 4.2.30 on 2026-06-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0106_remove_photo_report_remove_report_country_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Session',
                ),
            ]
        )
    ]
