# Generated by Django 2.2.7 on 2020-11-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0002_auto_20200807_0619'),
        ('tigacrafting', '0002_auto_20200806_1404'),
    ]

    operations = [
    ]
