# Generated by Django 2.2.7 on 2021-12-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0003_auto_20211028_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='accuracy_last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timestamp for last accuracy data update'),
        ),
        migrations.AddField(
            model_name='userstat',
            name='accuracy_stats',
            field=models.TextField(blank=True, null=True, verbose_name='Json structure containing validation accuracy data'),
        ),
    ]
