# Generated by Django 2.2.7 on 2022-04-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0006_userstat_last_emergency_mode_grab'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherspecies',
            name='ordering',
            field=models.IntegerField(blank=True, null=True, verbose_name='Auxiliary help to tweak list ordering'),
        ),
    ]
