# Generated by Django 2.2.7 on 2023-05-24 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0038_auto_20220616_0713'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tigacrafting', '0007_otherspecies_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritedReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Add a brief description that will help you remember the report', verbose_name='Brief note stating why this report interested you')),
                ('report', models.ForeignKey(help_text='User which marked the report as favorite', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='tigaserver_app.Report')),
                ('user', models.ForeignKey(help_text='User which marked the report as favorite', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
