# Generated by Django 2.2.7 on 2023-05-24 07:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0038_auto_20220616_0713'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tigacrafting', '0008_favoritedreports'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritedreports',
            unique_together={('user', 'report')},
        ),
    ]
