# Generated by Django 2.2.7 on 2023-07-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0039_auto_20230718_0857'),
        ('tigacrafting', '0010_merge_20230710_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='AimaAlertLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xvb', models.BooleanField(verbose_name='Stands for expert validation based - if True, means that the alert was sent after expert validation. For False, it was sent before')),
                ('report_datetime', models.DateTimeField()),
                ('locCode', models.CharField(max_length=25, verbose_name='Locale code - can be either a nuts3 code, or a nuts3_natcode (natcode is a municipality code) for spanish reports')),
                ('catId', models.IntegerField(verbose_name='aima species category id')),
                ('species', models.CharField(max_length=25, verbose_name='Species slug')),
                ('certainty', models.FloatField(verbose_name='IA certainty value')),
                ('status', models.CharField(max_length=50, verbose_name='Introduction status label')),
                ('hit', models.BooleanField(verbose_name='True if AIMA identification was initially correct, False if AIMA initially failed and was revised')),
                ('review_species', models.CharField(blank=True, max_length=25, null=True, verbose_name='Revised species slug, can be empty')),
                ('review_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Revised introduction status label')),
                ('review_datetime', models.DateTimeField(blank=True, null=True, verbose_name='revision timestamp')),
                ('report', models.ForeignKey(help_text='Report related with the alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tigaserver_app.Report')),
            ],
        ),
    ]
