# Generated by Django 2.2.7 on 2023-07-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0015_auto_20230719_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimaalertlog',
            name='alert_sent',
            field=models.BooleanField(default=False, verbose_name='flag for alert sent or not yet'),
        ),
        migrations.AddField(
            model_name='aimaalertlog',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes field for varied observations'),
        ),
        migrations.AlterField(
            model_name='aimaalertlog',
            name='status',
            field=models.CharField(default='', max_length=50, verbose_name='Introduction status label'),
        ),
    ]
