# Generated by Django 2.2.7 on 2024-03-22 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('tigacrafting', '0018_alertmetadata'), ('tigacrafting', '0019_auto_20240304_0910'), ('tigacrafting', '0020_alertmetadata_date_reviewed'), ('tigacrafting', '0021_auto_20240304_1457'), ('tigacrafting', '0022_alertmetadata_validation_status'), ('tigacrafting', '0023_auto_20240308_0810'), ('tigacrafting', '0024_auto_20240308_0811'), ('tigacrafting', '0025_alertnotificationcontact'), ('tigacrafting', '0026_auto_20240313_1042'), ('tigacrafting', '0027_alertmetadata_validation_species')]

    dependencies = [
        ('tigaserver_app', '0040_municipalitiesnatcode'),
        ('tigacrafting', '0017_auto_20230720_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotificationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_contacts', to='tigaserver_app.EuropeCountry')),
            ],
            options={
                'unique_together': {('country', 'email')},
            },
        ),
        migrations.CreateModel(
            name='AlertMetadata',
            fields=[
                ('communication_status', models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Accepted'), (2, 'Accepted and communicated'), (3, 'Rejected')], default=0, null=True, verbose_name='Communication status of the alert')),
                ('review_comments', models.TextField(blank=True, null=True, verbose_name='Review comments')),
                ('alert', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tigacrafting.Alert')),
                ('date_reviewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('validation_status', models.BooleanField(default=False, null=True)),
                ('validation_species', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
