# Generated by Django 2.2.7 on 2024-03-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0017_auto_20230720_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_status', models.IntegerField(blank=True, choices=[(0, 'Not reviewed. not sent'), (1, 'Reviewed, not sent'), (0, 'Reviewed and sent')], null=True, verbose_name='Communication status of the alert')),
                ('review_comments', models.TextField(blank=True, null=True, verbose_name='Review comments')),
            ],
        ),
    ]
