# Generated by Django 2.2.7 on 2024-03-04 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0018_alertmetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertmetadata',
            name='id',
        ),
        migrations.AddField(
            model_name='alertmetadata',
            name='alert',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tigacrafting.Alert'),
            preserve_default=False,
        ),
    ]
