# Generated by Django 2.2.7 on 2024-01-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0019_auto_20240122_1709'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expertreportannotation',
            name='unique_assignation',
        )
    ]
