# Generated by Django 2.2.7 on 2024-03-04 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0019_auto_20240304_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmetadata',
            name='date_reviewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
