# Generated by Django 2.2.7 on 2024-10-09 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0047_merge_20240813_1025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tigacrafting', '0019_auto_20240122_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Label for the bookmark. It allows the user to quickly identify why a bookmark was put', max_length=150)),
                ('module', models.CharField(help_text='Label which designates the module for which the bookmark is applied', max_length=150)),
                ('report', models.ForeignKey(help_text='Report to which the bookmark was applied', on_delete=django.db.models.deletion.CASCADE, related_name='report_bookmarks', to='tigaserver_app.Report')),
                ('user', models.ForeignKey(help_text='User which established the bookmark', on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'report', 'label')},
            },
        ),
    ]
