# Generated by Django 2.2.7 on 2024-03-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0020_alertmetadata_date_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmetadata',
            name='communication_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Reviewed, not sent'), (1, 'Reviewed and sent')], null=True, verbose_name='Communication status of the alert'),
        ),
    ]
