# Generated by Django 2.2.7 on 2024-01-25 15:57

from django.db import migrations, models
from django.db.models import OuterRef, Subquery

def remove_expert_report_annotation_duplicates(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model("tigacrafting", "ExpertReportAnnotation")

    # Will keep only the one with the most recent last_modified date.
    last_annotation_subquery = ExpertReportAnnotation.objects.filter(
        user=OuterRef('user'),
        report=OuterRef('report')
    ).order_by('-last_modified').values('pk')[:1]

    print("Deleting duplicate ExpertReportAnnotation, keeping last modified...")
    print(ExpertReportAnnotation.objects.exclude(pk__in=Subquery(last_annotation_subquery)).delete())


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0020_auto_20240125_1557'),
        ('tigaserver_app', '0050_report_versioning'),
    ]

    operations = [
        migrations.RunPython(remove_expert_report_annotation_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='expertreportannotation',
            constraint=models.UniqueConstraint(fields=('user', 'report'), name='unique_assignation'),
        ),
    ]
