# Generated by Django 2.2.7 on 2024-10-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0021_auto_20241009_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='json_filter',
            field=models.CharField(help_text='filter conditions when bookmark was set', max_length=500, null=True),
        ),
    ]
