# Generated by Django 2.2.7 on 2024-10-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0021_auto_20240125_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertreportannotation',
            name='validation_value',
            field=models.IntegerField(blank=True, choices=[(2, 'Definitely'), (1, 'Probably')], default=None, help_text='Certainty value, 1 for probable, 2 for sure, 0 for none', null=True, verbose_name='Validation Certainty'),
        ),
    ]
