# Generated by Django 2.2.7 on 2024-03-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0021_auto_20240304_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmetadata',
            name='validation_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
