# Generated by Django 2.2.7 on 2024-02-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0022_add_taxon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertreportannotation',
            name='validation_complete',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark this when you have completed your review and are ready for your annotation to be displayed to public.'),
        ),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='validation_complete_executive',
            field=models.BooleanField(db_index=True, default=False, help_text='Available only to national supervisor. Causes the report to be completely validated, with the final classification decided by the national supervisor'),
        ),
    ]
