# Generated by Django 2.2.7 on 2024-03-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0022_alertmetadata_validation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmetadata',
            name='communication_status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Accepted'), (2, 'Accepted and communicated')], null=True, verbose_name='Communication status of the alert'),
        ),
    ]
