# Generated by Django 3.2.25 on 2025-01-24 11:04

from django.conf import settings
from django.db import migrations, models


def create_missing_expertreportannotation(apps, schema_editor):
    Report = apps.get_model('tigaserver_app', 'Report')
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    MoveLabAnnotation = apps.get_model('tigacrafting', 'MoveLabAnnotation')
    Categories = apps.get_model('tigacrafting', 'Categories')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    reports_qs = Report.objects.annotate(
        expert_annotations_exists=models.Exists(
            ExpertReportAnnotation.objects.filter(report=models.OuterRef('pk'))
        ),
        movelab_annotation_exists=models.Exists(
            MoveLabAnnotation.objects.filter(task__photo__report=models.OuterRef('pk'))
        )
    ).filter(
        expert_annotations_exists=False,
        movelab_annotation_exists=True
    )

    annotations_to_create = MoveLabAnnotation.objects.filter(
        task__photo__report__in=reports_qs
    ).filter(
        pk=models.Subquery(
            MoveLabAnnotation.objects.filter(
                task__photo__report=models.OuterRef('task__photo__report')
            ).order_by('-tiger_certainty_category').values('pk')[:1]
        )
    ).select_related('task__photo__report')

    try:
        superexpert_user = User.objects.get(username='super_reritja')
        ae_albopictus = Categories.objects.get(name='Aedes albopictus')
        other_species = Categories.objects.get(name='Other species')
    except User.DoesNotExist:
        return
    except Categories.DoesNotExist:
        return

    expert_report_annotations_to_created = []
    for annotation in annotations_to_create.iterator():
        # Case annotation=2 -> definetely albopictus
        # Case annotation=1 -> probably albopictus
        # Case annotation=0 -> Not sure
        # Case annotation < 0 -> Other insect
        tiger_certainty_category = annotation.tiger_certainty_category or 0
        category = ae_albopictus if tiger_certainty_category > 0 else None
        other_species = other_species if tiger_certainty_category < 0 else None
        validation_value = 2 if tiger_certainty_category == 2 else 1 if tiger_certainty_category == 1 else 0
        expert_report_annotations_to_created.append(
            ExpertReportAnnotation(
                user=superexpert_user,
                report=annotation.task.photo.report,
                tiger_certainty_category=tiger_certainty_category,
                tiger_certainty_notes=annotation.certainty_notes,
                status=1 if not annotation.hide else -1,
                last_modified=annotation.last_modified,
                validation_complete=True,
                revise=True,
                created=annotation.created,
                category=category,
                other_species=other_species,
                validation_value=validation_value
            )
        )
    ExpertReportAnnotation.objects.bulk_create(
        expert_report_annotations_to_created,
        batch_size=2000
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0023_expertreportannotation_validation_complete_indexing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertreportannotation',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.RunPython(create_missing_expertreportannotation, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
