# Generated by Django 3.2.25 on 2025-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0024_movelabannotation_to_expertreportannotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreportannotation',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, to='tigacrafting.taxon'),
        ),
    ]
