# Generated by Django 2.2.7 on 2024-03-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0040_municipalitiesnatcode'),
        ('tigacrafting', '0024_auto_20240308_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotificationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_contacts', to='tigaserver_app.EuropeCountry')),
            ],
            options={
                'unique_together': {('country', 'email')},
            },
        ),
    ]
