# Generated by Django 2.2.7 on 2024-03-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0025_alertnotificationcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmetadata',
            name='communication_status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Accepted'), (2, 'Accepted and communicated'), (3, 'Rejected')], default=0, null=True, verbose_name='Communication status of the alert'),
        ),
    ]
