# Generated by Django 2.2.7 on 2024-03-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0026_auto_20240313_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmetadata',
            name='validation_species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
