# Generated by Django 3.2.25 on 2025-01-24 11:04

from django.db import migrations, models
from django.core.management import call_command


def set_expertreportannotation_identificationtasks(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    IdentificationTask = apps.get_model('tigacrafting', 'IdentificationTask')

    ExpertReportAnnotation.objects.update(
        identification_task=models.Subquery(
            IdentificationTask.objects.filter(
                report=models.OuterRef('report')
            ).values('pk')[:1]
        )
    )

def populate_identification_tasks(apps, schema_editor):
    call_command('refresh_identification_tasks')

class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0027_add_identificationtask'),
    ]

    operations = [
        migrations.RunPython(set_expertreportannotation_identificationtasks, migrations.RunPython.noop),
        migrations.RunPython(populate_identification_tasks, migrations.RunPython.noop),
    ]
