# Generated by Django 3.2.25 on 2025-03-18 14:39

from django.db import migrations, models


def remove_autoflagged_reports(apps, schema_editor):
    Report = apps.get_model('tigaserver_app', 'Report')
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')

    from tigacrafting.models import ExpertReportAnnotation as ExpertReportAnnotationModel

    reports_to_update = Report.objects.annotate(
        unique_classifications=models.Count(
            'expert_report_annotations__category',
            distinct=True,
            filter=models.Q(
                expert_report_annotations__user__groups__name='expert',
                expert_report_annotations__validation_complete=True
            )
        ) + models.Count(
            'expert_report_annotations__complex',
            distinct=True,
            filter=models.Q(
                expert_report_annotations__user__groups__name='expert',
                expert_report_annotations__validation_complete=True
            )
        ),
        count_status_flagged=models.Count(
            'expert_report_annotations', 
            filter=models.Q(
                expert_report_annotations__user__groups__name='expert',
                expert_report_annotations__validation_complete=True,
                expert_report_annotations__status=ExpertReportAnnotationModel.STATUS_FLAGGED
            )
        )
    ).filter(
        unique_classifications__gte=3,
        count_status_flagged__gte=2
    )

    # Update the status of ExpertReportAnnotations related to the filtered reports
    ExpertReportAnnotation.objects.filter(
        user__groups__name='expert',
        validation_complete=True,
        report__pk__in=models.Subquery(reports_to_update.values('pk')), 
        status=ExpertReportAnnotationModel.STATUS_FLAGGED
    ).update(status=ExpertReportAnnotationModel.STATUS_PUBLIC)

class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0028_populate_identificationtask'),
    ]

    operations = [
        migrations.RunPython(remove_autoflagged_reports, migrations.RunPython.noop),
    ]
