# Generated by Django 3.2.25 on 2025-03-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0029_remove_autoflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationtask',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='identificationtask',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('conflict', 'Conflict'), ('review', 'Review'), ('done', 'Done'), ('archived', 'Archived')], db_index=True, default='open', max_length=16),
        ),
    ]
