# Generated by Django 3.2.25 on 2025-04-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0030_auto_20250325_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identificationtask',
            options={'permissions': [('view_archived_identificationtasks', 'Can view archived records')]},
        ),
    ]
