# Generated by Django 3.2.25 on 2025-04-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0031_alter_identificationtask_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identificationtask',
            old_name='revision_type',
            new_name='review_type',
        ),
    ]
