# Generated by Django 3.2.25 on 2025-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0033_add_photoprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoprediction',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photoprediction',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
