# Generated by Django 3.2.25 on 2025-06-16 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0034_auto_20250616_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprediction',
            name='height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
