# Generated by Django 3.2.25 on 2025-11-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0038_photoprediction_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdcraftingresponse',
            name='task',
        ),
        migrations.RemoveField(
            model_name='crowdcraftingresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='crowdcraftingtask',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='movelabannotation',
            name='task',
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='CrowdcraftingResponse',
        ),
        migrations.DeleteModel(
            name='CrowdcraftingTask',
        ),
        migrations.DeleteModel(
            name='CrowdcraftingUser',
        ),
        migrations.DeleteModel(
            name='MoveLabAnnotation',
        ),
    ]
