# Generated by Django 4.2.27 on 2026-01-27 09:16

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0095_populate_report_uuid_fk'),
        ('tigacrafting', '0040_remove_userstat_crisis_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationtask',
            name='report_uuid',
            field=models.UUIDField(null=True),
            # field=models.OneToOneField(null=True, limit_choices_to={'type': 'adult'}, on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        ),
        migrations.AddField(
            model_name='expertreportannotation',
            name='report_uuid',
            field=models.UUIDField(null=True),
            # field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        ),
        migrations.AddField(
            model_name='favoritedreports',
            name='report_uuid',
            field=models.UUIDField(null=True),
            # field=models.ForeignKey(null=True, help_text='User which marked the report as favorite', on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        ),
        migrations.AddField(
            model_name='photoprediction',
            name='identification_task_uuid',
            field=models.UUIDField(null=True),
            # field=models.ForeignKey(null=True, help_text='Identification task to which the photo belongs', on_delete=django.db.models.deletion.CASCADE, to='tigacrafting.identificationtask', to_field='report_uuid'),
        ),
    ]
