# Generated by Django 4.2.27 on 2026-01-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0040_remove_userstat_crisis_mode_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='identificationtask',
            index=models.Index(fields=['taxon', 'report'], name='tigacraftin_taxon_i_d594e3_idx'),
        ),
    ]
