# Generated by Django 4.2.27 on 2026-01-27 09:16

from django.db import migrations, models
from django.db.models import F, Func
from django.db.models.functions import Cast
import django.db.models.deletion

def populate_identification_task_report_uuid(apps, schema_editor):
    IdentificationTask = apps.get_model('tigacrafting', 'IdentificationTask')
    IdentificationTask.objects.update(report_uuid=Func(F('report_id'), function='uuid'))

def reverse_populate_identification_task_report_uuid(apps, schema_editor):
    IdentificationTask = apps.get_model('tigacrafting', 'IdentificationTask')
    IdentificationTask.objects.update(report_id=Cast(F('report_uuid'), output_field=models.CharField()))

def populate_expertreportannotation_report_uuid(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    ExpertReportAnnotation.objects.update(report_uuid=Func(F('report_id'), function='uuid'))

def reverse_populate_expertreportannotation_report_uuid(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    ExpertReportAnnotation.objects.update(report_id=Cast(F('report_uuid'), output_field=models.CharField()))

def populate_favoritedreports_report_uuid(apps, schema_editor):
    FavoritedReports = apps.get_model('tigacrafting', 'FavoritedReports')
    FavoritedReports.objects.update(report_uuid=Func(F('report_id'), function='uuid'))

def reverse_populate_favoritedreports_report_uuid(apps, schema_editor):
    FavoritedReports = apps.get_model('tigacrafting', 'FavoritedReports')
    FavoritedReports.objects.update(report_id=Cast(F('report_uuid'), output_field=models.CharField()))

def populate_photoprediction_identification_task_uuid(apps, schema_editor):
    PhotoPrediction = apps.get_model('tigacrafting', 'PhotoPrediction')
    PhotoPrediction.objects.update(identification_task_uuid=Func(F('identification_task_id'), function='uuid'))

def reverse_populate_photoprediction_identification_task_uuid(apps, schema_editor):
    PhotoPrediction = apps.get_model('tigacrafting', 'PhotoPrediction')
    PhotoPrediction.objects.update(identification_task_id=Cast(F('identification_task_uuid'), output_field=models.CharField()))

class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0041_report_related_field_uuid_addition'),
    ]

    operations = [
        migrations.RunPython(populate_identification_task_report_uuid, reverse_code=reverse_populate_identification_task_report_uuid),
        migrations.AlterField(
            model_name='identificationtask',
            name='report_uuid',
            field=models.UUIDField(),
            # field=models.OneToOneField(limit_choices_to={'type': 'adult'}, on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        ),
        migrations.RunPython(populate_expertreportannotation_report_uuid, reverse_code=reverse_populate_expertreportannotation_report_uuid),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='report_uuid',
            field=models.UUIDField(),
            # field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        ),
        migrations.RunPython(populate_favoritedreports_report_uuid, reverse_code=reverse_populate_favoritedreports_report_uuid),
        migrations.AlterField(
            model_name='favoritedreports',
            name='report_uuid',
            field=models.UUIDField(),
            # field=models.ForeignKey(help_text='User which marked the report as favorite', on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        ),
        migrations.RunPython(populate_photoprediction_identification_task_uuid, reverse_code=reverse_populate_photoprediction_identification_task_uuid),
        migrations.AlterField(
            model_name='photoprediction',
            name='identification_task_uuid',
            field=models.UUIDField(),
            # field=models.ForeignKey(help_text='Identification task to which the photo belongs', on_delete=django.db.models.deletion.CASCADE, to='tigacrafting.identificationtask', to_field='report_uuid'),
        )
    ]
