# Generated by Django 4.2.27 on 2026-02-13 13:52

from django.db import migrations, models

def migrate_blood_genre_to_expert_report_annotation(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')

    # Annotate the values first
    annotations = ExpertReportAnnotation.objects.filter(
        models.Q(simplified_annotation=False) | models.Q(revise=True),
        best_photo__blood_genre__isnull=False,
    ).select_related('best_photo').annotate(
        new_sex=models.Case(
            models.When(best_photo__blood_genre__in=['dk', None], then=models.Value(None)),
            models.When(best_photo__blood_genre='male', then=models.Value('male')),
            default=models.Value('female'),
            output_field=models.CharField(),
        ),
        new_is_blood_fed=models.Case(
            models.When(best_photo__blood_genre__in=['dk', None], then=models.Value(None)),
            models.When(best_photo__blood_genre__in=['fblood', 'fgblood'], then=models.Value(True)),
            default=models.Value(False),
            output_field=models.BooleanField(),
        ),
        new_is_gravid=models.Case(
            models.When(best_photo__blood_genre__in=['dk', None], then=models.Value(None)),
            models.When(best_photo__blood_genre__in=['fgravid', 'fgblood'], then=models.Value(True)),
            default=models.Value(False),
            output_field=models.BooleanField(),
        ),
    )

    # Now update in bulk
    for ann in annotations:
        ann.sex = ann.new_sex
        ann.is_blood_fed = ann.new_is_blood_fed
        ann.is_gravid = ann.new_is_gravid

    ExpertReportAnnotation.objects.bulk_update(
        objs=annotations,
        fields=['sex', 'is_blood_fed', 'is_gravid'],
        batch_size=2000
    )

def migrate_reverse(apps, schema_editor):
    Photo = apps.get_model('tigaserver_app', 'Photo')

    Photo.objects.filter(
        expert_report_annotations__isnull=False,
    ).update(
        blood_genre=models.Case(
            # Unknown sex
            models.When(expert_report_annotations__sex__isnull=True, then=models.Value(None)),
            # Male
            models.When(expert_report_annotations__sex='male', then=models.Value('male')),
            # Female + blood fed + gravid (MOST SPECIFIC FIRST)
            models.When(
                expert_report_annotations__sex='female',
                expert_report_annotations__is_blood_fed=True,
                expert_report_annotations__is_gravid=True,
                then=models.Value('fgblood'),
            ),

            # Female + blood fed
            models.When(
                expert_report_annotations__sex='female',
                expert_report_annotations__is_blood_fed=True,
                then=models.Value('fblood'),
            ),

            # Female + gravid
            models.When(
                expert_report_annotations__sex='female',
                expert_report_annotations__is_gravid=True,
                then=models.Value('fgravid'),
            ),

            # Female only
            models.When(
                expert_report_annotations__sex='female',
                then=models.Value('female'),
            ),
            default=models.Value(None),
            output_field=models.CharField(),
        ),
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0041_identificationtask_tigacraftin_taxon_i_d594e3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreportannotation',
            name='is_blood_fed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertreportannotation',
            name='is_gravid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertreportannotation',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.RunPython(migrate_blood_genre_to_expert_report_annotation, reverse_code=migrate_reverse),
        migrations.AddConstraint(
            model_name='expertreportannotation',
            constraint=models.CheckConstraint(check=models.Q(('sex', 'male'), ('is_blood_fed', True), _negated=True), name='expertreportannotation_blood_fed_only_if_female'),
        ),
        migrations.AddConstraint(
            model_name='expertreportannotation',
            constraint=models.CheckConstraint(check=models.Q(('sex', 'male'), ('is_gravid', True), _negated=True), name='expertreportannotation_gravid_only_if_female'),
        ),
    ]
