# Generated by Django 4.2.27 on 2026-01-27 09:16

from django.db import migrations, models
from django.db.models import F, Func
from django.db.models.functions import Cast
import django.db.models.deletion

def populate_expertreportannotation_identification_task_uuid(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    ExpertReportAnnotation.objects.filter(identification_task__isnull=False).update(identification_task_uuid=Func(F('identification_task_id'), function='uuid'))

def reverse_populate_expertreportannotation_identification_task_uuid(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    ExpertReportAnnotation.objects.filter(identification_task_uuid__isnull=False).update(identification_task_id=Cast(F('identification_task_uuid'), output_field=models.CharField()))

class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0042_report_related_field_uuid_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreportannotation',
            name='identification_task_uuid',
            field=models.UUIDField(null=True),
            # field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tigacrafting.identificationtask', to_field='report_uuid'),
        ),
        migrations.RunPython(populate_expertreportannotation_identification_task_uuid, reverse_code=reverse_populate_expertreportannotation_identification_task_uuid),
    ]
