# Generated by Django 4.2.27 on 2026-02-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0042_expertreportannotation_is_blood_fed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationtask',
            name='is_blood_fed',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='identificationtask',
            name='is_gravid',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='identificationtask',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], editable=False, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='identificationtask',
            constraint=models.CheckConstraint(check=models.Q(('sex', 'male'), ('is_blood_fed', True), _negated=True), name='tigacrafting_identificationtask_blood_fed_only_if_female'),
        ),
        migrations.AddConstraint(
            model_name='identificationtask',
            constraint=models.CheckConstraint(check=models.Q(('sex', 'male'), ('is_gravid', True), _negated=True), name='tigacrafting_identificationtask_gravid_only_if_female'),
        ),
    ]
