# Generated by Django 4.2.27 on 2026-02-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0043_identificationtask_is_blood_fed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='site_certainty_notes',
        ),
    ]
