# Generated by Django 4.2.27 on 2026-01-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0043_identification_task_uuid_related_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificationtask',
            name='report',
        ),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='report',
        ),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='identification_task',
        ),
        migrations.RemoveField(
            model_name='favoritedreports',
            name='report',
        ),
        migrations.RemoveField(
            model_name='photoprediction',
            name='identification_task',
        )

    ]
