# Generated by Django 4.2.27 on 2026-01-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0044_alter_expertreportannotation_report_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertreportannotation',
            old_name='identification_task_uuid',
            new_name='identification_task',
        ),
        migrations.RenameField(
            model_name='expertreportannotation',
            old_name='report_uuid',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='favoritedreports',
            old_name='report_uuid',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='identificationtask',
            old_name='report_uuid',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='photoprediction',
            old_name='identification_task_uuid',
            new_name='identification_task',
        ),
    ]
