# Generated by Django 4.2.27 on 2026-01-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0098_rename_uuid_tmp_historicalreport_version_uuid_and_more'),
        ('tigacrafting', '0045_remove_expertreportannotation_identification_task_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationtask',
            name='report',
            field=models.OneToOneField(limit_choices_to={'type': 'adult'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='identification_task', serialize=False, to='tigaserver_app.report'),
        ),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='identification_task',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_report_annotations', to='tigacrafting.identificationtask'),
        ),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_report_annotations', to='tigaserver_app.report'),
        ),
        migrations.AlterField(
            model_name='favoritedreports',
            name='report',
            field=models.ForeignKey(help_text='User which marked the report as favorite', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='tigaserver_app.report'),
        ),
        migrations.AlterField(
            model_name='photoprediction',
            name='identification_task',
            field=models.ForeignKey(help_text='Identification task to which the photo belongs', on_delete=django.db.models.deletion.CASCADE, related_name='photo_predictions', to='tigacrafting.identificationtask'),
        ),
    ]
