# Generated by Django 4.2.27 on 2026-02-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0046_ensure_expertreportannotation_has_identification_task'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expertreportannotation',
            name='unique_assignation',
        ),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='report',
        ),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='identification_task',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='expert_report_annotations', to='tigacrafting.identificationtask'),
        ),
        migrations.AddConstraint(
            model_name='expertreportannotation',
            constraint=models.UniqueConstraint(fields=('user', 'identification_task'), name='unique_assignation'),
        ),
    ]
