# Generated by Django 4.2.27 on 2026-02-20 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def populate_reviewed_by(apps, schema_editor):
    IdentificationTask = apps.get_model('tigacrafting', 'IdentificationTask')
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    User = apps.get_model('auth', 'User')

    # Until now, only superexpert was allowed to set review,
    # so we can safely set reviewed_by to that user for all those tasks.
    # TODO: not setting pk to 25... It should be set to the actual user in superexpert group with the last created annotation.
    superexperts = User.objects.filter(groups__name="superexpert").values_list('id', flat=True)
    last_superexpert = ExpertReportAnnotation.objects.filter(
        user__in=superexperts,
        identification_task=models.OuterRef('pk')
    ).order_by('-created_at').values('user_id')[0]
    IdentificationTask.objects.filter(review_type__isnull=False).update(review_by=models.Subquery(last_superexpert))

    ExpertReportAnnotation.objects.filter(
        user__in=superexperts,
        revise=False
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0048_remove_replicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationtask',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_tasks_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_reviewed_by, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='identificationtask',
            constraint=models.CheckConstraint(check=models.Q(('review_type__isnull', True), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='review_requires_fields_if_set'),
        ),
    ]
