# Generated by Django 4.2.27 on 2026-02-23 10:41

from django.db import migrations, models

def populate_decision_level(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')

    ExpertReportAnnotation.objects.filter(
        revise=True
    ).update(decision_level='final')

    ExpertReportAnnotation.objects.filter(
        validation_complete_executive=True
    ).update(decision_level='executive')

def reverse_populate_decision_level(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')

    ExpertReportAnnotation.objects.filter(
        decision_level='final'
    ).update(revise=True)

    ExpertReportAnnotation.objects.filter(
        decision_level='executive'
    ).update(validation_complete_executive=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0049_remove_expertreportannotation_validation_complete_executive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identificationtask',
            options={'permissions': [('view_archived_identificationtasks', 'Can view archived records'), ('add_review', 'Can review')]},
        ),
        migrations.AddField(
            model_name='expertreportannotation',
            name='decision_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('executive', 'Executive'), ('final', 'Final')], default='normal', max_length=16),
        ),
        migrations.RunPython(populate_decision_level, reverse_code=reverse_populate_decision_level),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='revise',
        ),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='validation_complete_executive',
        ),
        
    ]
