# Generated by Django 4.2.27 on 2026-02-20 14:17

from django.db import migrations, models

def mark_is_decisive_annotation_with_revise(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')

    ExpertReportAnnotation.objects.filter(
        revise=True,
    ).update(
        is_decisive=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0049_remove_expertreportannotation_validation_complete_executive_and_more'),
    ]

    operations = [
        migrations.RunPython(mark_is_decisive_annotation_with_revise, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='revise',
        ),
        migrations.RenameField(
            model_name='expertreportannotation',
            old_name='validation_complete_executive',
            new_name='is_decisive',
        ),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='is_decisive',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
