# Generated by Django 4.2.27 on 2026-02-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0050_alter_identificationtask_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='aegypti_certainty_category',
        ),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='site_certainty_category',
        ),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='tiger_certainty_category',
        ),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Public'), (0, 'Flagged'), (-1, 'Hidden')], default=1, help_text='Whether report should be displayed on public map, flagged for further checking before public display), or hidden.', verbose_name='Status'),
        ),
    ]
