# Generated by Django 4.2.27 on 2026-02-24 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0053_remove_old_classification_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertreportannotation',
            name='confidence',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='validation_complete',
            field=models.BooleanField(db_index=True, default=True, help_text='Mark this when you have completed your review and are ready for your annotation to be displayed to public.'),
        ),
    ]
