# Generated by Django 4.2.27 on 2026-02-24 15:19

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0054_alter_expertreportannotation_confidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertreportannotation',
            old_name='tiger_certainty_notes',
            new_name='internal_note',
        ),
        migrations.RenameField(
            model_name='expertreportannotation',
            old_name='simplified_annotation',
            new_name='is_simplified',
        ),
        migrations.RenameField(
            model_name='expertreportannotation',
            old_name='edited_user_notes',
            new_name='public_note',
        ),
        migrations.RenameField(
            model_name='expertreportannotation',
            old_name='validation_complete',
            new_name='is_finished',
        ),
    ]
