# Generated by Django 4.2.27 on 2026-02-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0054_alter_expertreportannotation_confidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertreportannotation',
            old_name='tiger_certainty_notes',
            new_name='internal_note',
        ),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='internal_note',
            field=models.TextField(blank=True, help_text='Internal notes for yourself or other experts', null=True),
        ),
        migrations.RenameField(
            model_name='expertreportannotation',
            old_name='edited_user_notes',
            new_name='public_note',
        ),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='public_note',
            field=models.TextField(blank=True, help_text='Notes to display on public map', null=True),
        ),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expertreportannotation',
            name='message_for_user',
            field=models.TextField(blank=True, help_text='Message that user will receive when viewing report on phone', null=True),
        ),
    ]
