# Generated by Django 4.2.27 on 2026-02-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0055_remove_expertreportannotation_edited_user_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertreportannotation',
            old_name='simplified_annotation',
            new_name='is_simplified',
        ),
    ]
