# Generated by Django 4.2.27 on 2026-02-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0056_rename_simplified_annotation_expertreportannotation_is_simplified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertreportannotation',
            old_name='validation_complete',
            new_name='is_finished',
        ),
    ]
