# Generated by Django 4.2.29 on 2026-03-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tigaserver_app', '0103_delete_coverageareamonth_delete_fix'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Fix',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('user_coverage_uuid', models.CharField(blank=True, help_text='UUID randomly generated on phone to identify each unique user, but only within the coverage data so that privacy issues are not raised by linking this to the report data.. Must be exactly 36 characters (32 hex digits plus 4 hyphens).', max_length=36, null=True)),
                        ('fix_time', models.DateTimeField(help_text='Date and time when fix was recorded on phone. Format as ECMA 262 date time string (e.g. "2014-05-17T12:34:56.123+01:00".')),
                        ('server_upload_time', models.DateTimeField(auto_now_add=True, help_text='Date and time registered by server when it received fix upload. Automatically generated by server.')),
                        ('phone_upload_time', models.DateTimeField(help_text='Date and time on phone when it uploaded fix. Format as ECMA 262 date time string (e.g. "2014-05-17T12:34:56.123+01:00".')),
                        ('masked_lon', models.FloatField(help_text='Longitude rounded down to nearest 0.025 decimal degree.')),
                        ('masked_lat', models.FloatField(help_text='Latitude rounded down to nearest 0.025 decimal degree.')),
                        ('mask_size', models.FloatField(blank=True, help_text='size of location mask used', null=True)),
                        ('power', models.FloatField(blank=True, help_text='Power level of phone at time fix recorded, expressed as proportion of full charge. Range: 0-1.', null=True)),
                    ],
                    options={
                        'verbose_name': 'fix',
                        'verbose_name_plural': 'fixes',
                        'db_table': 'tigaserver_app_fix',
                    },
                ),
                migrations.CreateModel(
                    name='CoverageAreaMonth',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('lat', models.FloatField()),
                        ('lon', models.FloatField()),
                        ('year', models.IntegerField()),
                        ('month', models.IntegerField()),
                        ('n_fixes', models.PositiveIntegerField()),
                        ('last_modified', models.DateTimeField(auto_now=True)),
                        ('latest_report_server_upload_time', models.DateTimeField()),
                        ('latest_fix_id', models.PositiveIntegerField()),
                    ],
                    options={
                        'db_table': 'tigaserver_app_coverageareamonth',
                        'unique_together': {('lat', 'lon', 'year', 'month')},
                    },
                ),
            ]
        )
    ]
