# Generated by Django 4.2.3 on 2023-10-06 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("identifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="identifierprofile",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="useridentification",
            name="unique_user_task",
        ),
        migrations.RemoveField(
            model_name="useridentification",
            name="identifier_profile",
        ),
        migrations.AddField(
            model_name="useridentification",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"profile__is_identifier": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="identifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="useridentification",
            constraint=models.UniqueConstraint(fields=("user", "task"), name="unique_user_task"),
        ),
        migrations.DeleteModel(
            name="IdentifierProfile",
        ),
    ]
