# Generated by Django 4.0.8 on 2023-03-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityidentificationresult',
            options={'verbose_name': 'community identification result', 'verbose_name_plural': 'community identification results'},
        ),
        migrations.AlterModelOptions(
            name='ensembledidentificationresult',
            options={'verbose_name': 'ensembled identification result', 'verbose_name_plural': 'ensembled identification results'},
        ),
    ]
