# Generated by Django 4.2.3 on 2023-07-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identifications", "0001_initial"),
        ("individuals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useridentificationsuggestion",
            name="individual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="individuals.individual"
            ),
        ),
    ]
