# Generated by Django 4.2.3 on 2023-07-19 06:58

from django.db import migrations, models
import django.db.models.deletion
import mosquito_alert.identifications.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taxa", "0001_initial"),
        ("images", "0001_initial"),
        ("individuals", "0002_initial"),
        ("identifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useridentificationsuggestion",
            name="taxon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="taxa.taxon"
            ),
        ),
        migrations.AddField(
            model_name="useridentificationsuggestion",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="identifications",
                to="identifications.identifieruserprofile",
            ),
        ),
        migrations.AddField(
            model_name="imagetaxonpredictionrun",
            name="photo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taxon_prediction_run",
                to="images.photo",
            ),
        ),
        migrations.AddField(
            model_name="imagetaxonprediction",
            name="prediction_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_taxon_predictions",
                to="identifications.imagetaxonpredictionrun",
            ),
        ),
        migrations.AddField(
            model_name="imagetaxonprediction",
            name="taxon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="taxa.taxon"
            ),
        ),
        migrations.AddField(
            model_name="identificationresult",
            name="individual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="individuals.individual"
            ),
        ),
        migrations.AddField(
            model_name="identificationresult",
            name="taxon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="taxa.taxon"
            ),
        ),
        migrations.AddField(
            model_name="computervisionidentificationsuggestion",
            name="individual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="individuals.individual"
            ),
        ),
        migrations.AddField(
            model_name="computervisionidentificationsuggestion",
            name="taxon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="taxa.taxon"
            ),
        ),
        migrations.CreateModel(
            name="CommunityIdentificationResult",
            fields=[],
            options={
                "verbose_name": "community identification result",
                "verbose_name_plural": "community identification results",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                mosquito_alert.identifications.mixins.IdentificationResultProxyMixin,
                "identifications.identificationresult",
            ),
        ),
        migrations.CreateModel(
            name="EnsembledIdentificationResult",
            fields=[],
            options={
                "verbose_name": "ensembled identification result",
                "verbose_name_plural": "ensembled identification results",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                mosquito_alert.identifications.mixins.IdentificationResultProxyMixin,
                "identifications.identificationresult",
            ),
        ),
        migrations.AddConstraint(
            model_name="useridentificationsuggestion",
            constraint=models.UniqueConstraint(
                fields=("user_profile", "individual"), name="unique_user_individual"
            ),
        ),
        migrations.AddConstraint(
            model_name="imagetaxonprediction",
            constraint=models.UniqueConstraint(
                fields=("taxon", "prediction_run"), name="unique_taxon_prediction_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="identificationresult",
            constraint=models.UniqueConstraint(
                fields=("individual", "type", "taxon"),
                name="unique_taxon_individual_type",
            ),
        ),
    ]
