# Generated by Django 4.0.8 on 2023-03-31 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyGeoLocatedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
