# Generated by Django 4.2.29 on 2026-03-24 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='OrganizationPin',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                        ('textual_description', models.TextField(help_text='Text desription on the pin. This text is meant to be visualized as the text body of the dialog on the map')),
                        ('page_url', models.URLField(help_text='URL link to the organization page')),
                    ],
                    options={
                        'db_table': 'tigaserver_app_organizationpin',
                    },
                ),
            ]
        )
    ]
