# Generated by Django 2.2.7 on 2020-08-07 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
