# Generated by Django 2.2.7 on 2022-02-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0004_expertreportannotation_validation_complete_executive'),
        ('tigacrafting', '0003_auto_20211028_0744'),
    ]

    operations = [
    ]
