# Generated by Django 2.2.7 on 2023-04-21 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0038_auto_20220616_0713'),
        ('tigacrafting', '0007_otherspecies_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='nuts2_assignation',
            field=models.ForeignKey(blank=True, help_text='Nuts2 division in which the user operates. Influences the priority of report assignation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nuts2_assigned', to='tigaserver_app.NutsEurope'),
        ),
    ]
