# Generated by Django 2.2.7 on 2023-07-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0008_userstat_nuts2_assignation'),
        ('tigacrafting', '0009_auto_20230524_0722'),
    ]

    operations = [
    ]
