# Generated by Django 2.2.7 on 2023-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0013_auto_20230718_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimaalertlog',
            name='report',
            field=models.CharField(help_text='Report related with the alert', max_length=40),
        ),
    ]
