# Generated by Django 2.2.7 on 2023-07-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0014_auto_20230718_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimaalertlog',
            old_name='catId',
            new_name='cat_id',
        ),
        migrations.RenameField(
            model_name='aimaalertlog',
            old_name='locCode',
            new_name='loc_code',
        ),
        migrations.RenameField(
            model_name='aimaalertlog',
            old_name='report',
            new_name='report_id',
        ),
    ]
