# Generated by Django 2.2.7 on 2023-07-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0016_auto_20230719_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AimaAlertLog',
            new_name='Alert',
        ),
    ]
