# Generated by Django 2.2.7 on 2023-12-21 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0017_auto_20230720_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertreportannotation',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
