# Generated by Django 3.2.25 on 2025-06-16 14:46

import django.core.validators
from django.db import migrations, models
from django.db.models import F, Case, When, Value, FloatField

def convert_bbox_to_relative(apps, schema_editor):
    PhotoPrediction = apps.get_model('tigacrafting', 'PhotoPrediction')

    PhotoPrediction.objects.update(
        x_tl=Case(
            When(width=0, then=Value(0)),
            default=F('x_tl') / F('width'),
            output_field=FloatField()
        ),
        x_br=Case(
            When(width=0, then=Value(0)),
            default=F('x_br') / F('width'),
            output_field=FloatField()
        ),
        y_tl=Case(
            When(height=0, then=Value(0)),
            default=F('y_tl') / F('height'),
            output_field=FloatField()
        ),
        y_br=Case(
            When(height=0, then=Value(0)),
            default=F('y_br') / F('height'),
            output_field=FloatField()
        ),
    )

def convert_bbox_to_absolute(apps, schema_editor):
    PhotoPrediction = apps.get_model('tigacrafting', 'PhotoPrediction')
    PhotoPrediction.objects.update(
        x_tl=models.F('x_tl') * models.F('width'),
        x_br=models.F('x_br') * models.F('width'),
        y_tl=models.F('y_tl') * models.F('height'),
        y_br=models.F('y_br') * models.F('height'),
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0036_photoprediction_width_default_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprediction',
            name='x_br',
            field=models.FloatField(help_text='photo bounding box relative coordinates bottom right x', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='photoprediction',
            name='x_tl',
            field=models.FloatField(help_text='photo bounding box relative coordinates top left x', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='photoprediction',
            name='y_br',
            field=models.FloatField(help_text='photo bounding box relative coordinates bottom right y', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='photoprediction',
            name='y_tl',
            field=models.FloatField(help_text='photo bounding box relative coordinates top left y', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.RunPython(convert_bbox_to_relative, convert_bbox_to_absolute)
    ]
