# Generated by Django 3.2.25 on 2025-06-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0037_populate_bbox_relative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoprediction',
            name='height',
        ),
        migrations.RemoveField(
            model_name='photoprediction',
            name='width',
        ),
        migrations.AddConstraint(
            model_name='photoprediction',
            constraint=models.CheckConstraint(check=models.Q(('x_tl__range', (0, 1))), name='tigacrafting_photoprediction_x_tl_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='photoprediction',
            constraint=models.CheckConstraint(check=models.Q(('x_br__range', (0, 1))), name='tigacrafting_photoprediction_x_br_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='photoprediction',
            constraint=models.CheckConstraint(check=models.Q(('y_tl__range', (0, 1))), name='tigacrafting_photoprediction_y_tl_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='photoprediction',
            constraint=models.CheckConstraint(check=models.Q(('y_br__range', (0, 1))), name='tigacrafting_photoprediction_y_br_between_0_and_1'),
        ),
    ]
