# Generated by Django 4.1.13 on 2026-01-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0039_auto_20251125_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstat',
            name='crisis_mode',
        ),
        migrations.RemoveField(
            model_name='userstat',
            name='last_emergency_mode_grab',
        ),
    ]
