# Generated by Django 4.2.27 on 2026-02-19 14:29

from django.db import migrations, models

def populate_is_favourite_field(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    FavoritedReports = apps.get_model('tigacrafting', 'FavoritedReports')

    favourites = FavoritedReports.objects.filter(
        user=models.OuterRef("user"),
        report=models.OuterRef("report"),
    )

    ExpertReportAnnotation.objects.update(
        is_favourite=models.Exists(favourites)
    )

def reverse_populate_is_favourite_field(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    FavoritedReports = apps.get_model('tigacrafting', 'FavoritedReports')

    # Get all annotations marked as favourited
    favourited_annotations = ExpertReportAnnotation.objects.filter(
        is_favourite=True
    ).values('user', 'report')

    # Recreate FavoritedReports entries
    FavoritedReports.objects.bulk_create(
        [
            FavoritedReports(
                user_id=entry['user'],
                report_id=entry['report'],
            )
            for entry in favourited_annotations
        ],
        ignore_conflicts=True,  # avoids duplicates if unique constraint exists
        batch_size=2000
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0043_identificationtask_is_blood_fed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreportannotation',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_is_favourite_field, reverse_code=reverse_populate_is_favourite_field),
        migrations.DeleteModel(
            name='FavoritedReports',
        ),
    ]
