# Generated by Django 4.2.27 on 2026-02-19 11:42

from django.db import migrations, models
from mosquito_alert.tigaserver_app.models import Report

def assign_identification_task_to_expert_report_annotations(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')

    ExpertReportAnnotation.objects.filter(
        report__type=Report.TYPE_ADULT,
        identification_task__isnull=True,
        report__identification_task=models.F('report_id')
    ).update(
        identification_task_id=models.F('report_id')
    )

def remove_expert_report_annotations_without_identification_task(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')

    ExpertReportAnnotation.objects.filter(
        identification_task__isnull=True
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0045_remove_expertreportannotation_site_certainty_notes'),
    ]

    operations = [
        migrations.RunPython(assign_identification_task_to_expert_report_annotations, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(remove_expert_report_annotations_without_identification_task, reverse_code=migrations.RunPython.noop),
    ]
