# Generated by Django 4.2.27 on 2026-02-20 13:55

from django.db import migrations, models

def remove_replicas(apps, schema_editor):
    IdentificationTask = apps.get_model('tigacrafting', 'IdentificationTask')
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    User = apps.get_model('auth', 'User')

    superexperts = User.objects.filter(groups__name="superexpert").values_list('id', flat=True)

    ExpertReportAnnotation.objects.filter(
        user__in=superexperts,
        validation_complete=False
    ).delete()

    ExpertReportAnnotation.objects.filter(
        user__username__in=["innie", "minnie", "manny"],
    ).delete()

    User.objects.filter(
        username__in=["innie", "minnie", "manny"],
    ).delete()

    task_qs = IdentificationTask.objects.annotate(
        count_annotations=models.Count(
            'expert_report_annotations',
            filter=~models.Q(expert_report_annotations__user__in=superexperts) & models.Q(expert_report_annotations__validation_complete=True)
        ),
        has_superexpert_annotations=models.Exists(
            ExpertReportAnnotation.objects.filter(
                identification_task=models.OuterRef('pk'),
                user__in=superexperts,
                validation_complete=True
            )
        )
    ).filter(
        count_annotations=0,
        has_superexpert_annotations=True,
        review_type__isnull=False,
    ).exclude(
        result_source='ai'
    )

    for task in task_qs.iterator():
        ExpertReportAnnotation.objects.filter(
            user__in=superexperts,
            identification_task=task,
        ).update(
            revise=True,
            # Copy fields from IdentificationTask
            best_photo_id=task.photo_id,
            edited_user_notes=task.public_note or "",
            message_for_user=task.message_for_user or "",
            taxon=task.taxon,
            confidence=task.confidence,
            validation_value=2 if task.confidence >= 0.8 else 1,
            status=-1 if not task.is_safe else (0 if task.is_flagged else 1),
            sex=task.sex,
            is_gravid=task.is_gravid,
            is_blood_fed=task.is_blood_fed,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0047_remove_expertreportannotation_report'),
    ]

    operations = [
        migrations.RunPython(remove_replicas, reverse_code=migrations.RunPython.noop),
    ]
