# Generated by Django 4.2.27 on 2026-02-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0052_clean_replicas_on_ai_results'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taxon',
            name='unique_content_type_object_id',
        ),
        migrations.RemoveIndex(
            model_name='taxon',
            name='tigacraftin_content_583e94_idx',
        ),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='complex',
        ),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='other_species',
        ),
        migrations.RemoveField(
            model_name='expertreportannotation',
            name='validation_value',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='object_id',
        ),
        migrations.DeleteModel(
            name='OtherSpecies',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Complex',
        ),
    ]
