# Generated by Django 4.2.27 on 2026-02-24 15:19

from django.db import migrations

def make_blank_internal_note_null(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    ExpertReportAnnotation.objects.filter(internal_note='').update(internal_note=None)

def make_null_internal_note_blank(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    ExpertReportAnnotation.objects.filter(internal_note=None).update(internal_note='')

def make_blank_public_note_null(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    ExpertReportAnnotation.objects.filter(public_note='').update(public_note=None)

def make_null_public_note_blank(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    ExpertReportAnnotation.objects.filter(public_note=None).update(public_note='')

def make_blank_message_for_user_null(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    ExpertReportAnnotation.objects.filter(message_for_user='').update(message_for_user=None)

def make_null_message_for_user_blank(apps, schema_editor):
    ExpertReportAnnotation = apps.get_model('tigacrafting', 'ExpertReportAnnotation')
    ExpertReportAnnotation.objects.filter(message_for_user=None).update(message_for_user='')


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0056_expertreportannotation_allow_null_notes_simplified'),
    ]

    operations = [
        migrations.RunPython(make_blank_internal_note_null, reverse_code=make_null_internal_note_blank),
        migrations.RunPython(make_blank_public_note_null, reverse_code=make_null_public_note_blank),
        migrations.RunPython(make_blank_message_for_user_null, reverse_code=make_null_message_for_user_blank),
    ]
