# Generated by Django 4.2.29 on 2026-03-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0057_expertreportannotation_populate_null_on_blank_notes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='identificationtask',
            name='tigacrafting_identificationtask_confidence_between_0_and_1',
        ),
        migrations.RemoveConstraint(
            model_name='identificationtask',
            name='tigacrafting_identificationtask_uncertainty_between_0_and_1',
        ),
        migrations.RemoveConstraint(
            model_name='identificationtask',
            name='tigacrafting_identificationtask_agreement_between_0_and_1',
        ),
        migrations.RemoveConstraint(
            model_name='identificationtask',
            name='tigacrafting_identificationtask_blood_fed_only_if_female',
        ),
        migrations.RemoveConstraint(
            model_name='identificationtask',
            name='tigacrafting_identificationtask_gravid_only_if_female',
        ),
        migrations.RemoveConstraint(
            model_name='photoprediction',
            name='tigacrafting_photoprediction_x_tl_between_0_and_1',
        ),
        migrations.RemoveConstraint(
            model_name='photoprediction',
            name='tigacrafting_photoprediction_x_br_between_0_and_1',
        ),
        migrations.RemoveConstraint(
            model_name='photoprediction',
            name='tigacrafting_photoprediction_y_tl_between_0_and_1',
        ),
        migrations.RemoveConstraint(
            model_name='photoprediction',
            name='tigacrafting_photoprediction_y_br_between_0_and_1',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='ExpertReportAnnotation',
                ),
                migrations.DeleteModel(
                    name='IdentificationTask',
                ),
                migrations.DeleteModel(
                    name='PhotoPrediction',
                ),
                migrations.DeleteModel(
                    name='Taxon',
                ),
                migrations.DeleteModel(
                    name='UserStat',
                ),
            ]
        ),
    ]
