# Generated by Django 4.2.30 on 2026-06-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0058_remove_identificationtask_assignees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
