# Generated by Django 4.2.29 on 2026-03-16 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grabbed_reports', models.IntegerField(default=0, help_text='Number of reports grabbed since implementation of simplified reports. For each 3 reports grabbed, one is simplified', verbose_name='Grabbed reports')),
                ('license_accepted', models.BooleanField(default=False, verbose_name='Value is true if user has accepted the license terms of EntoLab')),
            ],
            options={
                'db_table': 'tigacrafting_userstat',
            },
        ),
    ]
