# Generated by Django 4.2.3 on 2023-10-06 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "is_identifier",
                    models.BooleanField(
                        default=False, help_text="Designates where the user can access the identification app."
                    ),
                ),
                (
                    "is_superidentifier",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions in the identification app.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
