# Generated by Django 4.2.3 on 2024-10-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0003_location_timezone"),
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_identification_boundary",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="geo.boundary"
            ),
        ),
    ]
