# Generated by Django 4.2.29 on 2026-03-20 16:44

import django.contrib.auth.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import langcodes
import mosquito_alert.users.models
import mosquito_alert.users.permissions
import numpyencoder.numpyencoder
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userstat_national_supervisor_of_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='TigaUser',
                    fields=[
                        ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                        ('password', models.CharField(default=mosquito_alert.users.models.get_default_password_hash, max_length=128, verbose_name='password')),
                        ('user_UUID', models.CharField(default=uuid.uuid4, editable=False, help_text='UUID randomly generated on phone to identify each unique user. Must be exactly 36 characters (32 hex digits plus 4 hyphens).', max_length=36, primary_key=True, serialize=False)),
                        ('registration_time', models.DateTimeField(auto_now_add=True, help_text='The date and time when user registered and consented to sharing data. Automatically set by server when user uploads registration.')),
                        ('score', models.IntegerField(default=0, help_text='Score associated with user. This field is used only if the user does not have a profile')),
                        ('score_v2', models.IntegerField(default=0, help_text='Global XP Score. This field is updated whenever the user asks for the score, and is only stored here. The content must equal score_v2_adult + score_v2_bite + score_v2_site')),
                        ('score_v2_adult', models.IntegerField(default=0, help_text='Adult reports XP Score.')),
                        ('score_v2_bite', models.IntegerField(default=0, help_text='Bite reports XP Score.')),
                        ('score_v2_site', models.IntegerField(default=0, help_text='Site reports XP Score.')),
                        ('score_v2_struct', models.JSONField(blank=True, encoder=numpyencoder.numpyencoder.NumpyEncoder, help_text='Full cached score data', null=True)),
                        ('last_score_update', models.DateTimeField(blank=True, help_text='Last time score was updated', null=True)),
                        ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                        ('last_location_update', models.DateTimeField(blank=True, help_text='Last time location was updated', null=True)),
                        ('locale', models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('ca', 'Català'), ('eu', 'Euskara'), ('bn', 'বাংলা'), ('sv', 'Svenska'), ('de', 'Deutsch'), ('sq', 'Shqip'), ('el', 'Ελληνικά'), ('gl', 'Galego'), ('hu', 'Magyar'), ('pt', 'Português'), ('sl', 'Slovenščina'), ('it', 'Italiano'), ('fr', 'Français'), ('bg', 'Български'), ('ro', 'Română'), ('hr', 'Hrvatski'), ('mk', 'Македонски'), ('sr', 'Српски'), ('lb', 'Lëtzebuergesch'), ('nl', 'Nederlands'), ('tr', 'Türkçe'), ('zh-CN', '中文（中国）')], default='en', help_text="The locale code representing the language preference selected by the user for displaying the interface text. Enter the locale following the BCP 47 standard in 'language' or 'language-region' format (e.g., 'en' for English, 'en-US' for English (United States), 'fr' for French). The language is a two-letter ISO 639-1 code, and the region is an optional two-letter ISO 3166-1 alpha-2 code.", max_length=16, validators=[langcodes.tag_is_valid])),
                    ],
                    options={
                        'verbose_name': 'user',
                        'verbose_name_plural': 'users',
                        'db_table': 'tigaserver_app_tigauser',
                    },
                ),
            ]
        )
    ]
