# Generated by Django 4.2.29 on 2026-04-28 12:56

from django.db import migrations, models
import django.db.models.deletion

from mosquito_alert.workspaces.models import WorkspaceMembership as WorkspaceMembershipModel

def populate_userstat_from_workspace_membership(apps, schema_editor):
    UserStat = apps.get_model("users", "UserStat")
    WorkspaceMembership = apps.get_model("workspaces", "WorkspaceMembership")

    for membership in WorkspaceMembership.objects.select_related("workspace__country").all():
        UserStat.objects.filter(user_id=membership.user_id).update(native_of=membership.workspace.country_id)

        if membership.role == WorkspaceMembershipModel.Role.SUPERVISOR:
            UserStat.objects.filter(user_id=membership.user_id).update(national_supervisor_of=membership.workspace.country)

class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_remove_europecountry_is_bounding_box_and_more'),
        ('users', '0003_tigauser'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstat',
            name='national_supervisor_of',
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=populate_userstat_from_workspace_membership),
        migrations.RenameField(
            model_name='userstat',
            old_name='native_of',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='userstat',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country in which the user operates.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.europecountry'),
        ),
    ]
