# Generated by Django 4.2.29 on 2026-06-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userstat_national_supervisor_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstat',
            name='grabbed_reports',
        ),
    ]
