# Generated by Django 4.2.30 on 2026-06-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userstat_grabbed_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier of the session. Automatically generated by server when session created.', primary_key=True, serialize=False)),
                ('session_ID', models.IntegerField(db_index=True, help_text='The session ID number. Should be an integer that increments by 1 for each session from a given user.')),
                ('session_start_time', models.DateTimeField(help_text='Date and time on phone when the session was started. Format as ECMA 262 date time string (e.g. "2014-05-17T12:34:56.123+01:00".')),
                ('session_end_time', models.DateTimeField(blank=True, help_text='Date and time on phone when the session was ended. Format as ECMA 262 date time string (e.g. "2014-05-17T12:34:56.123+01:00".', null=True)),
                ('user', models.ForeignKey(help_text='user_UUID for the user sending this report. Must be exactly 36 characters (32 hex digits plus 4 hyphens) and user must have already registered this ID.', on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='users.tigauser')),
            ],
            options={
                'db_table': 'tigaserver_app_session',
                'unique_together': {('session_ID', 'user')},
            },
        ),
    ]
