# Generated by Django 4.2.30 on 2026-08-18 14:20

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('utils', '0001_initial'),
        ('users', '0006_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='tigauser',
            name='notification_topics',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of topics for which the user has opted to receive notifications. Each topic is represented as a string, and the list can be empty if the user has not subscribed to any topics.', through='utils.UUIDTaggedItem', to='taggit.Tag', verbose_name='Notification Topics'),
        ),
    ]
