# Generated by Django 4.2.3 on 2023-07-19 06:58

from django.db import migrations, models
import django_lifecycle.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "annotation",
                "verbose_name_plural": "annotations",
            },
        ),
        migrations.CreateModel(
            name="AnnotationAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                ("label_en", models.CharField(max_length=128, null=True)),
                ("label_ca", models.CharField(max_length=128, null=True)),
                ("label_es", models.CharField(max_length=128, null=True)),
            ],
            options={
                "verbose_name": "annotation attribute",
                "verbose_name_plural": "annotation attributes",
            },
        ),
        migrations.CreateModel(
            name="AnnotationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                ("label_en", models.CharField(max_length=128, null=True)),
                ("label_ca", models.CharField(max_length=128, null=True)),
                ("label_es", models.CharField(max_length=128, null=True)),
            ],
            options={
                "verbose_name": "annotation value",
                "verbose_name_plural": "annotation values",
            },
        ),
        migrations.CreateModel(
            name="Individual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_identified", models.BooleanField(default=False, editable=False)),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True, related_name="individuals", to="images.photo"
                    ),
                ),
            ],
            options={
                "verbose_name": "individual",
                "verbose_name_plural": "individuals",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
