# Generated by Django 4.2.3 on 2023-07-19 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taxa", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("individuals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="taxon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="individuals",
                to="taxa.taxon",
            ),
        ),
        migrations.AddField(
            model_name="annotationvalue",
            name="annotation_attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="individuals.annotationattribute",
            ),
        ),
        migrations.AddField(
            model_name="annotationvalue",
            name="taxa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_values",
                to="taxa.taxon",
            ),
        ),
        migrations.AddField(
            model_name="annotationattribute",
            name="taxa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_attributes",
                to="taxa.taxon",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="annotation_attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annotations",
                to="individuals.annotationattribute",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="annotation_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annotations",
                to="individuals.annotationvalue",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="individual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="individuals.individual",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.UniqueConstraint(
                fields=("user", "individual", "annotation_attribute"),
                name="unique_user_individual_annotation-attribute",
            ),
        ),
    ]
