# Generated by Django 4.0.8 on 2023-02-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='is_identified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
