# Generated by Django 4.0.8 on 2023-01-24 12:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='is_identified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='identificationset',
            name='agreement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
