# Generated by Django 2.2.7 on 2020-06-22 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='date_given',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 13, 39, 21, 346827), help_text='Date in which the award was given'),
        ),
    ]
