# Generated by Django 2.2.7 on 2021-02-17 09:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0005_auto_20210216_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('textual_description', models.TextField(help_text='Text desription on the pin. This text is meant to be visualized as the text body of the dialog on the map')),
                ('page_url', models.URLField(help_text='URL link to the organization page')),
            ],
        ),
    ]
