# Generated by Django 2.2.7 on 2021-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0006_organizationpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ghash',
            field=models.CharField(blank=True, help_text='Geohash for point coordinates', max_length=50, null=True),
        ),
    ]
