# Generated by Django 2.2.7 on 2021-03-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0007_remove_acknowledgednotification_acknowledged'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acknowledgednotification',
            unique_together={('user', 'notification')},
        ),
    ]
