# Generated by Django 2.2.7 on 2021-03-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0008_auto_20210302_1101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('user', 'topic')},
        ),
    ]
