# Generated by Django 2.2.7 on 2021-03-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0009_auto_20210303_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Report regarding the current notification', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_notifications', to='tigaserver_app.Report'),
        ),
    ]
