# Generated by Django 2.2.7 on 2021-04-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0013_auto_20210406_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcontent',
            name='body_html_en',
            field=models.TextField(default='', help_text='Expert comment, expanded and allows html, in english'),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='body_html_es',
            field=models.TextField(blank=True, default=None, help_text='Expert comment, expanded and allows html, in spanish', null=True),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='title_en',
            field=models.TextField(default='', help_text='Title of the comment, shown in non-detail view, in english'),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='title_es',
            field=models.TextField(blank=True, default=None, help_text='Title of the comment, shown in non-detail view, in spanish', null=True),
        ),
    ]
