# Generated by Django 2.2.7 on 2021-04-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0014_auto_20210406_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcontent',
            name='native_locale',
            field=models.CharField(blank=True, default=None, help_text='Locale code for text in body_html_native and title_native', max_length=10, null=True),
        ),
    ]
