# Generated by Django 2.2.7 on 2021-04-12 07:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0015_auto_20210406_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutsEurope',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('nuts_id', models.CharField(blank=True, max_length=5, null=True)),
                ('levl_code', models.SmallIntegerField(blank=True, null=True)),
                ('cntr_code', models.CharField(blank=True, max_length=2, null=True)),
                ('name_latn', models.CharField(blank=True, max_length=70, null=True)),
                ('nuts_name', models.CharField(blank=True, max_length=106, null=True)),
                ('mount_type', models.SmallIntegerField(blank=True, null=True)),
                ('urbn_type', models.SmallIntegerField(blank=True, null=True)),
                ('coast_type', models.SmallIntegerField(blank=True, null=True)),
                ('fid', models.CharField(blank=True, max_length=5, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('europecountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nuts', to='tigaserver_app.EuropeCountry')),
            ],
            options={
                'db_table': 'nuts_europe',
                'managed': True,
            },
        ),
    ]
