# Generated by Django 2.2.7 on 2021-05-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0022_notification_acknowledged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='map_notification',
        ),
    ]
