# Generated by Django 2.2.7 on 2021-06-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0006_organizationpin'),
        ('tigaserver_app', '0023_remove_notification_map_notification'),
    ]

    operations = [
    ]
