# Generated by Django 2.2.7 on 2021-11-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0024_merge_20210615_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='europecountry',
            name='is_bounding_box',
            field=models.BooleanField(default=False, help_text='If true, this geometry acts as a bounding box. The bounding boxes act as little separate entolabs, in the sense that no reports located inside a bounding box should reach an expert outside this bounding box'),
        ),
        migrations.AddField(
            model_name='europecountry',
            name='national_supervisor_report_expires_in',
            field=models.IntegerField(blank=True, help_text='Number of days that a report in the queue is exclusively available to the nagional supervisor. For example, if the field value is 6, after report_creation_time + 6 days a report will be available to all users', null=True),
        ),
    ]
