# Generated by Django 2.2.7 on 2021-10-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0025_auto_20211025_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='europecountry',
            name='is_bounding_box',
        ),
        migrations.RemoveField(
            model_name='europecountry',
            name='national_supervisor_report_expires_in',
        ),
    ]
