# Generated by Django 2.2.7 on 2022-02-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0026_auto_20211028_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tigauser',
            name='last_score_update',
            field=models.DateTimeField(blank=True, help_text='Last time score was updated', null=True),
        ),
        migrations.AddField(
            model_name='tigauser',
            name='score_v2_struct',
            field=models.TextField(blank=True, help_text='Full cached score data', null=True),
        ),
    ]
