# Generated by Django 2.2.7 on 2021-12-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0026_auto_20211028_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cached_movelab_annotation_euro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='cached_movelab_annotation_euro_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
