# Generated by Django 2.2.7 on 2022-02-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0028_rankingdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingdata',
            old_name='user_UUID',
            new_name='user_uuid',
        ),
    ]
