# Generated by Django 2.2.7 on 2022-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0029_auto_20220204_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_version',
            field=models.BooleanField(default=True),
        ),
    ]
