# Generated by Django 2.2.7 on 2022-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0030_auto_20220317_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='alert',
            field=models.BooleanField(default=False, help_text='This report has been marked by the IA system as alert'),
        ),
    ]
