# Generated by Django 2.2.7 on 2022-03-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0030_report_last_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
