# Generated by Django 2.2.7 on 2022-04-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0031_auto_20220425_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iascore',
            name='f3_c1',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f3_c2',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f4_c1',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f4_c2',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f5_c1',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f5_c2',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f6_c1',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f6_c2',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f7_c1',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f7_c2',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f8_c1',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f8_c2',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f9_c1',
        ),
        migrations.RemoveField(
            model_name='iascore',
            name='f9_c2',
        ),
        migrations.AddField(
            model_name='iascore',
            name='f2_c3',
            field=models.FloatField(blank=True, help_text='Score for filter 2, class 3', null=True),
        ),
        migrations.AddField(
            model_name='iascore',
            name='f2_c4',
            field=models.FloatField(blank=True, help_text='Score for filter 2, class 4', null=True),
        ),
        migrations.AddField(
            model_name='iascore',
            name='f2_c5',
            field=models.FloatField(blank=True, help_text='Score for filter 2, class 5', null=True),
        ),
        migrations.AddField(
            model_name='iascore',
            name='f2_c6',
            field=models.FloatField(blank=True, help_text='Score for filter 2, class 6', null=True),
        ),
        migrations.AddField(
            model_name='iascore',
            name='f2_c7',
            field=models.FloatField(blank=True, help_text='Score for filter 2, class 7', null=True),
        ),
        migrations.AddField(
            model_name='iascore',
            name='f2_c8',
            field=models.FloatField(blank=True, help_text='Score for filter 2, class 8', null=True),
        ),
        migrations.AddField(
            model_name='iascore',
            name='f2_c9',
            field=models.FloatField(blank=True, help_text='Score for filter 2, class 9', null=True),
        ),
    ]
