# Generated by Django 2.2.7 on 2022-05-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0032_auto_20220426_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='blood_genre',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('fblood', 'Female blood'), ('dk', 'Dont know')], default='dk', max_length=10),
        ),
    ]
