# Generated by Django 2.2.7 on 2022-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0035_auto_20220531_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='blood_genre',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('fblood', 'Female blood'), ('fgravid', 'Female gravid'), ('fgblood', 'Female gravid + blood'), ('dk', 'Dont know')], default=None, max_length=20, null=True),
        ),
    ]
