# Generated by Django 2.2.7 on 2022-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0037_auto_20220616_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_label',
        ),
        migrations.AddField(
            model_name='notificationcontent',
            name='notification_label',
            field=models.CharField(blank=True, default=None, help_text='Arbitrary label used to group thematically equal notifications. Optional. ', max_length=255, null=True),
        ),
    ]
