# Generated by Django 2.2.7 on 2023-06-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0038_auto_20220616_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type_changed_on_coarse_filter',
            field=models.BooleanField(default=False, help_text='If True, indicates that the report type was flipped from adult to site or vice versa on the coarse filter'),
        ),
    ]
