# Generated by Django 2.2.7 on 2024-01-12 16:06

from django.db import migrations, models


def set_updated_at_to_upload_time(apps, schema_editor):
    Report = apps.get_model("tigaserver_app", "Report")
    # initialize the value of updated_at with the same value as server_upload_time
    Report.objects.all().update(updated_at=models.F("server_upload_time"))


def revert_updated_at_field(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tigaserver_app", "0039_auto_20230718_0857"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the report was last modified",
            ),
        ),
        migrations.RunPython(set_updated_at_to_upload_time, revert_updated_at_field),
    ]
