# Generated by Django 2.2.7 on 2024-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0039_auto_20230718_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalitiesNatCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natcode', models.CharField(max_length=11)),
                ('nameunit', models.CharField(max_length=100)),
                ('nuts_2_code', models.CharField(max_length=4)),
                ('nuts_3_code', models.CharField(max_length=5)),
                ('gisco_id', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
