# Generated by Django 2.2.7 on 2024-01-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0040_report_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='datetime_fix_offset',
            field=models.IntegerField(blank=True, default=None, editable=False, help_text="An integer representing the offset (in seconds) applied to the original datetime values for fixing. If None, it indicates that no information about the original time zone could be inferred or the timezone was already provided when posting the report. To retrieve the original values, use: original_value = current_value - datetime_fix_offset.Fields to apply (if necessary) are: 'phone_upload_time', 'creation_time' and 'version_time'.", null=True),
        ),
    ]
