# Generated by Django 2.2.7 on 2024-01-23 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0041_report_datetime_fix_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgednotification',
            name='notification',
            field=models.ForeignKey(help_text='The notification which has been acknowledged or not', on_delete=django.db.models.deletion.CASCADE, related_name='notification_acknowledgements', to='tigaserver_app.Notification'),
        ),
        migrations.AlterField(
            model_name='acknowledgednotification',
            name='user',
            field=models.ForeignKey(help_text='User which has acknowledged the notification', on_delete=django.db.models.deletion.CASCADE, related_name='user_acknowledgements', to='tigaserver_app.TigaUser'),
        ),
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category to which the award belongs. Can be blank for arbitrary awards', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_awards', to='tigaserver_app.AwardCategory'),
        ),
        migrations.AlterField(
            model_name='award',
            name='expert',
            field=models.ForeignKey(blank=True, help_text='Expert that gave the award', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_awards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='award',
            name='report',
            field=models.ForeignKey(blank=True, default=None, help_text='Report which the award refers to. Can be blank for arbitrary awards', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_award', to='tigaserver_app.Report'),
        ),
        migrations.AlterField(
            model_name='iascore',
            name='photo',
            field=models.ForeignKey(help_text='Photo to which the score refers to', on_delete=django.db.models.deletion.CASCADE, related_name='photo_iascore', to='tigaserver_app.Photo'),
        ),
        migrations.AlterField(
            model_name='iascore',
            name='report',
            field=models.ForeignKey(help_text='Report which the score refers to.', on_delete=django.db.models.deletion.CASCADE, related_name='report_iascore', to='tigaserver_app.Report'),
        ),
        migrations.AlterField(
            model_name='missionitem',
            name='mission',
            field=models.ForeignKey(help_text='Mission to which this item is associated.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tigaserver_app.Mission'),
        ),
        migrations.AlterField(
            model_name='missiontrigger',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='tigaserver_app.Mission'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expert',
            field=models.ForeignKey(blank=True, help_text='Expert sending the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_content',
            field=models.ForeignKey(blank=True, help_text='Multi language content of the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_content', to='tigaserver_app.NotificationContent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Report regarding the current notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_notifications', to='tigaserver_app.Report'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', help_text='User to which the notification will be sent', on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='tigaserver_app.TigaUser'),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='predefined_available_to',
            field=models.ForeignKey(blank=True, help_text='If this field is not null, this notification is predefined - the predefined map notifications will go here. This field indicates the expert to which the notification is available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predefined_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nutseurope',
            name='europecountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nuts', to='tigaserver_app.EuropeCountry'),
        ),
        migrations.AlterField(
            model_name='owcampaigns',
            name='country',
            field=models.ForeignKey(help_text='Country in which the campaign is taking place', on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='tigaserver_app.EuropeCountry'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='report',
            field=models.ForeignKey(help_text='Report and version to which this photo is associated (36-digit report_UUID).', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tigaserver_app.Report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tigaserver_app.EuropeCountry'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mission',
            field=models.ForeignKey(blank=True, help_text='If this report was a response to a mission, the unique id field of that mission.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tigaserver_app.Mission'),
        ),
        migrations.AlterField(
            model_name='report',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session ID for session in which this report was created ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_reports', to='tigaserver_app.Session'),
        ),
        migrations.AlterField(
            model_name='reportresponse',
            name='report',
            field=models.ForeignKey(help_text='Report to which this response is associated.', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tigaserver_app.Report'),
        ),
        migrations.AlterField(
            model_name='sentnotification',
            name='notification',
            field=models.ForeignKey(help_text='The notification which has been sent', on_delete=django.db.models.deletion.CASCADE, related_name='notification_sendings', to='tigaserver_app.Notification'),
        ),
        migrations.AlterField(
            model_name='sentnotification',
            name='sent_to_topic',
            field=models.ForeignKey(blank=True, help_text='Topic to which the notification was sent.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_sentnotifications', to='tigaserver_app.NotificationTopic'),
        ),
        migrations.AlterField(
            model_name='sentnotification',
            name='sent_to_user',
            field=models.ForeignKey(blank=True, help_text='User to which the notification was sent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sentnotifications', to='tigaserver_app.TigaUser'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(help_text='user_UUID for the user sending this report. Must be exactly 36 characters (32 hex digits plus 4 hyphens) and user must have already registered this ID.', on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='tigaserver_app.TigaUser'),
        ),
        migrations.AlterField(
            model_name='tigauser',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_devices', to='tigaserver_app.TigaProfile'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='topic',
            field=models.ForeignKey(help_text='Topics to which the user is subscribed', on_delete=django.db.models.deletion.CASCADE, related_name='topic_users', to='tigaserver_app.NotificationTopic'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(help_text='User which is subscribed to the topic', on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='tigaserver_app.TigaUser'),
        ),
        migrations.AlterField(
            model_name='award',
            name='given_to',
            field=models.ForeignKey(blank=True, help_text='User to which the notification was awarded. Usually this is the user that uploaded the report, but the report can be blank for special awards', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_awards', to='tigaserver_app.TigaUser'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(help_text='user_UUID for the user sending this report. Must be exactly 36 characters (32 hex digits plus 4 hyphens) and user must have already registered this ID.', on_delete=django.db.models.deletion.PROTECT, related_name='user_reports', to='tigaserver_app.TigaUser'),
        ),
    ]
