# Generated by Django 2.2.7 on 2024-01-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0042_auto_20240124_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='app_language',
            field=models.CharField(blank=True, help_text='Language setting, within tigatrapp, of device from which this report was submitted. 2-digit ISO-639-1 language code.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='creation_time',
            field=models.DateTimeField(help_text="Date and time on phone when first version of report was created. Format as ECMA 262 date time string (e.g. '2014-05-17T12:34:56.123+01:00'."),
        ),
        migrations.AlterField(
            model_name='report',
            name='device_manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer of device from which this report was submitted.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='device_model',
            field=models.CharField(blank=True, help_text='Model of device from which this report was submitted.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ia_filter_1',
            field=models.FloatField(blank=True, help_text='Value ranging from -1.0 to 1.0 positive values indicate possible insect, negative values indicate spam(non-insect)', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ia_filter_2',
            field=models.FloatField(blank=True, help_text='Score for best classified image. 0 indicates not classified, 1.xx indicates classified with score xx, 2.xx classified with alert with score xx.', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_choice',
            field=models.CharField(choices=[('current', "Current location detected by user's device"), ('selected', 'Location selected by user from map'), ('missing', 'No location choice submitted - should be used only for missions')], help_text="Did user indicate that report relates to current location of phone ('current') or to a location selected manually on the map ('selected')? Or is the choice missing ('missing')", max_length=8),
        ),
        migrations.AlterField(
            model_name='report',
            name='os',
            field=models.CharField(blank=True, help_text='Operating system of device from which this report was submitted.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='os_language',
            field=models.CharField(blank=True, help_text='Language setting of operating system on device from which this report was submitted. 2-digit ISO-639-1 language code.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='os_version',
            field=models.CharField(blank=True, help_text='Operating system version of device from which this report was submitted.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='package_name',
            field=models.CharField(blank=True, db_index=True, help_text='Name of tigatrapp package from which this report was submitted.', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone_upload_time',
            field=models.DateTimeField(help_text="Date and time on phone when it uploaded fix. Format as ECMA 262 date time string (e.g. '2014-05-17T12:34:56.123+01:00'."),
        ),
        migrations.AlterField(
            model_name='report',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session ID for session in which this report was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_reports', to='tigaserver_app.Session'),
        ),
        migrations.AlterField(
            model_name='report',
            name='version_time',
            field=models.DateTimeField(help_text="Date and time on phone when this version of report was created. Format as ECMA 262 date time string (e.g. '2014-05-17T12:34:56.123+01:00'."),
        ),
    ]
