# Generated by Django 2.2.7 on 2024-02-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0044_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='breeding_site_has_larvae',
            field=models.BooleanField(blank=True, help_text='Either if the user perceived larvaes the breeding site.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='breeding_site_has_near_mosquitoes',
            field=models.BooleanField(blank=True, help_text='Either if the user perceived mosquitoes near the breeding site (less than 10 meters).', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='breeding_site_has_water',
            field=models.BooleanField(blank=True, help_text='Either if the user perceived water in the breeding site.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='breeding_site_in_public_area',
            field=models.BooleanField(blank=True, help_text='Either if the breeding site is found in a public area.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='breeding_site_type',
            field=models.CharField(blank=True, choices=[('basin', 'Basin'), ('bucket', 'Bucket'), ('fountain', 'Fountain'), ('small_container', 'Small container'), ('storm_drain', 'Storm Drain'), ('well', 'Well'), ('other', 'Other')], help_text='Breedign site tpye.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='chest_bite_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the chest.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='event_environment',
            field=models.CharField(blank=True, choices=[('indoors', 'Indoors'), ('outdoors', 'Outdoors'), ('vehicle', 'Inside vehicle')], help_text='The environment where the event took place.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='event_moment',
            field=models.CharField(blank=True, choices=[('now', 'Now'), ('last_morning', 'Last morning'), ('last_midday', 'Last midday'), ('last_afternoon', 'Last afternoon'), ('last_night', 'Last night')], help_text='The moment of the day when the event took place.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='head_bite_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the head.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='left_arm_bite_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the left arm.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='left_leg_bite_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the left leg.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='right_arm_bite_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the right arm.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='right_leg_bite_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of bites reported in the right leg.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='user_perceived_mosquito_abdomen',
            field=models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The species of mosquito that the abdomen resembles, according to the user.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='user_perceived_mosquito_legs',
            field=models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The species of mosquito that the leg resembles, according to the user.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='user_perceived_mosquito_thorax',
            field=models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The species of mosquito that the thorax resembles, according to the user.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='user_perceived_mosquito_specie',
            field=models.CharField(blank=True, choices=[('albopictus', 'Aedes albopictus'), ('aegypti', 'Aedes aegypti'), ('japonicus', 'Aedes japonicus'), ('koreicus', 'Aedes koreicus'), ('culex', 'Culex pipiens'), ('other', 'Other')], help_text='The mosquito specie perceived by the user.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='bite_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total number of bites reported.', null=True),
        ),
    ]
