# Generated by Django 2.2.7 on 2024-02-05 19:01

from django.db import migrations, models
import functools
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0044_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(db_index=True, default=functools.partial(secrets.token_urlsafe, *(3,), **{}), help_text='4-digit alpha-numeric code generated on user phone to identify each unique report from that user. Digits should lbe randomly drawn from the set of all lowercase and uppercase alphabetic characters and 0-9, but excluding 0, o, and O to avoid confusion if we ever need user to be able to refer to a report ID in correspondence with MoveLab (as was previously the case when we had them sending samples).', max_length=4),
        ),
    ]
