# Generated by Django 2.2.7 on 2024-08-06 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0045_tigauser_language_iso2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAssignmentStat',
            fields=[
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tigaserver_app.EuropeCountry')),
                ('unassigned_reports', models.IntegerField(default=0)),
                ('in_progress_reports', models.IntegerField(default=0)),
                ('pending_reports', models.IntegerField(default=0)),
                ('nsqueue_reports', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(blank=True, help_text='Last time stats were updated', null=True)),
            ],
        ),
    ]
