# Generated by Django 2.2.7 on 2024-07-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0045_tigauser_language_iso2'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='flipped',
            field=models.BooleanField(default=False, help_text='If true, indicates that the report type has been changed in the coarse filter'),
        ),
        migrations.AddField(
            model_name='report',
            name='flipped_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the report was flipped', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='flipped_to',
            field=models.CharField(blank=True, help_text='Type it was flipped from, to type it was flipped to, separated by #        \n            For instance, if the report was and adult and flipped to storm_drain_water, this field would have the value adult#storm_drain_water\n        ', max_length=60, null=True),
        ),
    ]
