# Generated by Django 2.2.7 on 2024-08-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0046_globalassignmentstat'),
        ('tigaserver_app', '0046_auto_20240731_0808'),
    ]

    operations = [
    ]
