# Generated by Django 2.2.7 on 2024-02-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0048_report_non_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tigauser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='tigauser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='tigauser',
            name='user_UUID',
            field=models.CharField(editable=False, help_text='UUID randomly generated on phone to identify each unique user. Must be exactly 36 characters (32 hex digits plus 4 hyphens).', max_length=36, primary_key=True, serialize=False),
        ),
    ]
