# Generated by Django 2.2.7 on 2024-01-24 15:43

from django.db import migrations, models

from django.db.models import OuterRef, Subquery
from django.db.models.functions import Greatest

def update_report_updated_at_field(apps, schema_editor):
    HistoricalReport = apps.get_model("tigaserver_app", "HistoricalReport")
    Report = apps.get_model("tigaserver_app", "Report")

    print("Updating Report.updated_at with last modification date (if necessary)")
    Report.objects.annotate(
        last_update=Greatest(
            models.F('updated_at'),
            Subquery(
                HistoricalReport.objects.filter(
                    **{Report._meta.pk.name: OuterRef('pk')}
                ).order_by('-history_date').values('history_date')[:1]
            )
        )
    ).update(updated_at=models.F('last_update'))

class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0048_report_versioning'),
    ]

    operations = [
        migrations.RunPython(update_report_updated_at_field, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('deleted_at__isnull', True), ('version_number', 0)), models.Q(('deleted_at__isnull', False), ('version_number', -1)), _connector='OR'), name='version_number_constraint'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'type', 'report_id'], name='tigaserver__user_id_7343f3_idx'),
        ),
        # Make non editable fields.
        migrations.AlterField(
            model_name='historicalreport',
            name='creation_time',
            field=models.DateTimeField(editable=False, help_text="Date and time on phone when first version of report was created. Format as ECMA 262 date time string (e.g. '2014-05-17T12:34:56.123+01:00'."),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='type',
            field=models.CharField(choices=[('bite', 'Bite'), ('adult', 'Adult'), ('site', 'Breeding Site'), ('mission', 'Mission')], editable=False, help_text="Type of report: 'adult', 'site', or 'mission'.", max_length=7),
        ),
        migrations.AlterField(
            model_name='report',
            name='creation_time',
            field=models.DateTimeField(editable=False, help_text="Date and time on phone when first version of report was created. Format as ECMA 262 date time string (e.g. '2014-05-17T12:34:56.123+01:00'."),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone_upload_time',
            field=models.DateTimeField(editable=False, help_text="Date and time on phone when it uploaded fix. Format as ECMA 262 date time string (e.g. '2014-05-17T12:34:56.123+01:00'."),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('bite', 'Bite'), ('adult', 'Adult'), ('site', 'Breeding Site'), ('mission', 'Mission')], editable=False, help_text="Type of report: 'adult', 'site', or 'mission'.", max_length=7),
        ),
        migrations.AlterField(
            model_name='report',
            name='version_number',
            field=models.SmallIntegerField(db_index=True, default=0, editable=False, help_text='-1 if deleted, otherwise 0.'),
        ),
    ]
