# Generated by Django 2.2.7 on 2024-03-05 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0049_auto_20240228_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='europecountry',
            name='gid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='bite_count',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, help_text='Total number of bites reported.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='type',
            field=models.CharField(choices=[('bite', 'Bite'), ('adult', 'Adult'), ('site', 'Breeding Site'), ('mission', 'Mission')], help_text="Type of report: 'adult', 'site', or 'mission'.", max_length=7),
        ),
        migrations.AlterField(
            model_name='report',
            name='bite_count',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, help_text='Total number of bites reported.', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('bite', 'Bite'), ('adult', 'Adult'), ('site', 'Breeding Site'), ('mission', 'Mission')], help_text="Type of report: 'adult', 'site', or 'mission'.", max_length=7),
        ),
        migrations.AlterField(
            model_name='tigauser',
            name='user_UUID',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='UUID randomly generated on phone to identify each unique user. Must be exactly 36 characters (32 hex digits plus 4 hyphens).', max_length=36, primary_key=True, serialize=False),
        ),
    ]
