# Generated by Django 2.2.7 on 2024-03-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0051_report_non_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix',
            name='masked_lat',
            field=models.FloatField(help_text='Latitude rounded down to nearest 0.025 decimal degree.'),
        ),
        migrations.AlterField(
            model_name='fix',
            name='masked_lon',
            field=models.FloatField(help_text='Longitude rounded down to nearest 0.025 decimal degree.'),
        ),
    ]
