# Generated by Django 2.2.7 on 2024-03-11 09:11

from django.db import migrations, models
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0052_auto_20240307_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='phone_timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, help_text="The timezone corresponding to the datetime collected from the phone. Please provide values from the IANA timezone database (e.g., 'America/New_York').", null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='phone_timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, help_text="The timezone corresponding to the datetime collected from the phone. Please provide values from the IANA timezone database (e.g., 'America/New_York').", null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='version_UUID',
            field=models.CharField(db_index=True, default=uuid.uuid4, help_text='UUID randomly generated on phone to identify each unique report version. Must be exactly 36 characters (32 hex digits plus 4 hyphens).', max_length=36),
        ),
        migrations.AlterField(
            model_name='report',
            name='version_UUID',
            field=models.CharField(default=uuid.uuid4, help_text='UUID randomly generated on phone to identify each unique report version. Must be exactly 36 characters (32 hex digits plus 4 hyphens).', max_length=36, primary_key=True, serialize=False),
        ),
    ]
