# Generated by Django 2.2.7 on 2024-03-15 11:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import numpyencoder.numpyencoder

class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0052_ensure_masked_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tigauser',
            name='score_v2_struct',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=numpyencoder.numpyencoder.NumpyEncoder, help_text='Full cached score data', null=True),
        ),
    ]
