# Generated by Django 2.2.7 on 2024-10-25 12:42

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0053_tigauser_update_score_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='phone_timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, help_text="The timezone corresponding to the datetime collected from the phone. Please provide values from the IANA timezone database (e.g., 'America/New_York').", null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='phone_timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, help_text="The timezone corresponding to the datetime collected from the phone. Please provide values from the IANA timezone database (e.g., 'America/New_York').", null=True),
        ),
        migrations.AddField(
            model_name='tigauser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='tigauser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='europecountry',
            name='gid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='version_UUID',
            field=models.CharField(db_index=True, default=uuid.uuid4, help_text='UUID randomly generated on phone to identify each unique report version. Must be exactly 36 characters (32 hex digits plus 4 hyphens).', max_length=36),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.TigaUser'),
        ),
        migrations.AlterField(
            model_name='report',
            name='version_UUID',
            field=models.CharField(default=uuid.uuid4, help_text='UUID randomly generated on phone to identify each unique report version. Must be exactly 36 characters (32 hex digits plus 4 hyphens).', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tigauser',
            name='user_UUID',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='UUID randomly generated on phone to identify each unique user. Must be exactly 36 characters (32 hex digits plus 4 hyphens).', max_length=36, primary_key=True, serialize=False),
        ),
    ]
