# Generated by Django 2.2.7 on 2024-10-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0054_auto_20241025_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='hide',
            field=models.BooleanField(db_index=True, default=False, help_text='Hide this photo from public views?'),
        ),
    ]
