# Generated by Django 2.2.7 on 2024-10-30 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0055_photo_hide_dbindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
