# Generated by Django 2.2.7 on 2024-10-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0056_photo_uuid_uuidfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='europecountry',
            name='iso3_code',
            field=models.CharField(help_text='ISO 3166-1 alpha-3 country code (3-letter code, e.g., ESP).', max_length=3),
        ),
        migrations.AlterField(
            model_name='europecountry',
            name='name_engl',
            field=models.CharField(help_text='Full name of the country in English (e.g., Spain).', max_length=44),
        ),
    ]
