# Generated by Django 2.2.7 on 2024-10-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0057_auto_20241031_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['server_upload_time']},
        ),
        migrations.AlterField(
            model_name='report',
            name='server_upload_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time on server when report uploaded. (Automatically generated by server.)'),
        ),
    ]
