# Generated by Django 2.2.7 on 2024-10-29 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0022_auto_20241029_1010'),
        ('tigaserver_app', '0060_rename_phone_timezone_to_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iascore',
            old_name='f2_c1',
            new_name='ae_aegypti',
        ),
        migrations.RenameField(
            model_name='iascore',
            old_name='f2_c2',
            new_name='ae_albopictus',
        ),
        migrations.RenameField(
            model_name='iascore',
            old_name='f2_c3',
            new_name='anopheles',
        ),
        migrations.RenameField(
            model_name='iascore',
            old_name='f2_c4',
            new_name='culex',
        ),
        migrations.RenameField(
            model_name='iascore',
            old_name='f2_c5',
            new_name='culiseta',
        ),
        migrations.RenameField(
            model_name='iascore',
            old_name='f2_c6',
            new_name='ae_japonicus',
        ),
        migrations.RenameField(
            model_name='iascore',
            old_name='f2_c7',
            new_name='ae_koreicus',
        ),
        migrations.RenameField(
            model_name='iascore',
            old_name='f2_c8',
            new_name='other_species',
        ),
        migrations.RenameField(
            model_name='iascore',
            old_name='f2_c9',
            new_name='not_sure',
        ),
        migrations.RenameField(
            model_name='iascore',
            old_name='f1_c1',
            new_name='insect_confidence',
        ),
    ]
