# Generated by Django 2.2.7 on 2024-11-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0061_reports_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='given_to',
            field=models.ForeignKey(help_text='User to which the notification was awarded. Usually this is the user that uploaded the report, but the report can be blank for special awards', on_delete=django.db.models.deletion.CASCADE, related_name='user_awards', to='tigaserver_app.TigaUser'),
        ),
    ]
