# Generated by Django 2.2.7 on 2024-11-14 11:43


from django.db import migrations, models

def populate_tigaserver_device_token(apps, schema_editor):
    TigaUser = apps.get_model('tigaserver_app', 'TigaUser')
    TigaProfile = apps.get_model('tigaserver_app', 'TigaProfile')

    # Populate TigaUser.device_token
    TigaUser.objects.filter(
        device_token__isnull=True,
        profile__isnull=False,
        profile__firebase_token__isnull=False
    ).update(
        device_token=models.Subquery(
            TigaProfile.objects.filter(
                pk=models.OuterRef('profile_id')
            ).values('firebase_token')[:1]
        )
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0062_award_given_to_non_nullable'),
    ]

    operations = [
        migrations.RunPython(populate_tigaserver_device_token, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='tigauser',
            name='profile',
        ),
        migrations.DeleteModel(
            name='TigaProfile',
        ),
    ]
