# Generated by Django 2.2.7 on 2024-11-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0063_populate_tigaserver_device_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        )
    ]
