# Generated by Django 2.2.7 on 2024-11-14 11:43

import django
from django.db import migrations, models
from django.db.models.functions import Cast


def populate_mobileapp(apps, schema_editor):
    Report = apps.get_model('tigaserver_app', 'Report')
    MobileApp = apps.get_model('tigaserver_app', 'MobileApp')

    # Populate mobile version
    mobile_app_to_create = []
    for mobile_version in Report.objects.values('package_name','package_version').annotate(first_upload_time=models.Min('server_upload_time')).order_by('first_upload_time').distinct():
        mobile_app_to_create.append(
            MobileApp(
                package_name=mobile_version.get('package_name'),
                package_version=mobile_version.get('package_version'),
                created_at=mobile_version.get('first_upload_time'),
                updated_at=mobile_version.get('first_upload_time')
            )
        )
    MobileApp.objects.bulk_create(mobile_app_to_create, batch_size=2000)


def link_mobileapp_to_report(apps, schema_editor):
    Report = apps.get_model('tigaserver_app', 'Report')
    HistoricalReport = apps.get_model("tigaserver_app", "HistoricalReport")
    MobileApp = apps.get_model('tigaserver_app', 'MobileApp')

    Report.objects.update(
        mobile_app_id=models.Subquery(
            MobileApp.objects.filter(
                package_name=models.OuterRef('package_name'),
                package_version=Cast(models.OuterRef('package_version'), output_field=models.CharField()),
            ).values('pk')[:1]
        )
    )

    HistoricalReport.objects.update(
        mobile_app_id=models.Subquery(
            Report.objects.filter(
                pk=models.OuterRef('version_UUID')
            ).values('mobile_app_id')[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0064_report_remove_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=128)),
                ('package_version', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.RunPython(populate_mobileapp, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mobileapp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='mobileapp',
            constraint=models.UniqueConstraint(fields=('package_name', 'package_version'), name='unique_name_version'),
        ),
        migrations.AddField(
            model_name='report',
            name='mobile_app',
            field=models.ForeignKey(help_text='The mobile app version from where the report was sent.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='tigaserver_app.MobileApp'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='mobile_app',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The mobile app version from where the report was sent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tigaserver_app.MobileApp'),
        ),
        migrations.RunPython(link_mobileapp_to_report, migrations.RunPython.noop),
    ]
