# Generated by Django 2.2.7 on 2024-11-14 11:43

from django.db import migrations, models
import django.db.models.deletion

def link_device_to_report(apps, schema_editor):
    Report = apps.get_model('tigaserver_app', 'Report')
    HistoricalReport = apps.get_model("tigaserver_app", "HistoricalReport")
    Device = apps.get_model('tigaserver_app', 'Device')

    Report.objects.update(
        device_id=models.Subquery(
            Device.objects.filter(
                user=models.OuterRef('user'),
                date_created__lte=models.OuterRef('server_upload_time'),
                model=models.OuterRef('device_model')
            ).order_by('-date_created').values('pk')[:1]
        )
    )

    HistoricalReport.objects.update(
        device_id=models.Subquery(
            Report.objects.filter(
                pk=models.OuterRef('version_UUID')
            ).values('device_id')[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0066_add_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='device',
            field=models.ForeignKey(help_text='The device from where the report was sent.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_reports', to='tigaserver_app.Device'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The device from where the report was sent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tigaserver_app.Device'),
        ),
        migrations.RunPython(link_device_to_report, migrations.RunPython.noop),
    ]
