# Generated by Django 2.2.7 on 2024-11-14 11:43

from django.db import migrations, models

def fix_device_updated_at_field(apps, schema_editor):
    Device = apps.get_model('tigaserver_app', 'Device')
    HistoricalDevice = apps.get_model("tigaserver_app", "HistoricalDevice")

    Device.objects.update(
        updated_at=models.Subquery(
            HistoricalDevice.objects.filter(
                id=models.OuterRef('pk')
            ).order_by('-history_date').values('history_date')[:1]
        )
    )

def unfix_device_updated_at_field(apps, schema_editor):
    Device = apps.get_model('tigaserver_app', 'Device')

    Device.objects.update(
        updated_at=models.F('date_created')
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0069_add_report_uniqueconstraints'),
    ]

    operations = [
        migrations.RunPython(fix_device_updated_at_field, unfix_device_updated_at_field),
    ]
