# Generated by Django 2.2.7 on 2024-11-26 12:56

from django.db import migrations, models
import django.db.models.deletion

def link_tigauser_language(apps, schema_editor):
    TigaUser = apps.get_model('tigaserver_app', 'TigaUser')
    Language = apps.get_model('languages_plus', 'Language')

    TigaUser.objects.update(
        language_id=models.Subquery(
            Language.objects.filter(
                iso_639_1=models.OuterRef('language_iso2')
            ).values('pk')[:1]
        )
    )

def unlink_tigauser_language(apps, schema_editor):
    TigaUser = apps.get_model('tigaserver_app', 'TigaUser')
    Language = apps.get_model('languages_plus', 'Language')

    TigaUser.objects.update(
        language_iso2=models.Subquery(
            Language.objects.filter(
                pk=models.OuterRef('language_id')
            ).values('iso_639_1')[:1]
        )
    )

def fix_indonesian_language(apps, schema_editor):
    TigaUser = apps.get_model('tigaserver_app', 'TigaUser')

    # There is a bug with indonesian language
    TigaUser.objects.filter(language_iso2='in').update(language_iso2='id')

def unfix_indonesian_language(apps, schema_editor):
    TigaUser = apps.get_model('tigaserver_app', 'TigaUser')

    # There is a bug with indonesian language
    TigaUser.objects.filter(language_iso2='id').update(language_iso2='in')


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('tigaserver_app', '0069_update_device_updated_at'),
    ]

    operations = [
        migrations.RunPython(fix_indonesian_language, unfix_indonesian_language),
        migrations.AddField(
            model_name='tigauser',
            name='language',
            field=models.ForeignKey(null=True, limit_choices_to={'iso_639_1__in': ['es', 'ca', 'eu', 'bn', 'sv', 'en', 'de', 'sq', 'el', 'gl', 'hu', 'pt', 'sl', 'it', 'fr', 'bg', 'ro', 'hr', 'mk', 'sr', 'lb', 'nl', 'tr', 'zh-cn']}, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.RunPython(link_tigauser_language, unlink_tigauser_language),
        migrations.AlterField(
            model_name='tigauser',
            name='language',
            field=models.ForeignKey(limit_choices_to={'iso_639_1__in': ['es', 'ca', 'eu', 'bn', 'sv', 'en', 'de', 'sq', 'el', 'gl', 'hu', 'pt', 'sl', 'it', 'fr', 'bg', 'ro', 'hr', 'mk', 'sr', 'lb', 'nl', 'tr', 'zh-cn']}, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.RemoveField(
            model_name='tigauser',
            name='language_iso2',
        ),
    ]
