# Generated by Django 2.2.7 on 2024-11-26 12:56

from django.db import migrations, models
import langcodes
from langcodes import closest_supported_match

def standarize_locale(apps, schema_editor):
    TigaUser = apps.get_model('tigaserver_app', 'TigaUser')
    language_choices = [code for code, _ in TigaUser._meta.get_field('locale').choices]
    users_to_update = []
    for user in TigaUser.objects.all().iterator():
        closes_language = closest_supported_match(
            user.locale,
            language_choices
        ) or 'en'
        if user.locale != closes_language:
            user.locale = closes_language
            users_to_update.append(user)
    TigaUser.objects.bulk_update(users_to_update, fields=['locale'])

def undo_standarize_locale(apps, schema_editor):
    TigaUser = apps.get_model('tigaserver_app', 'TigaUser')

    TigaUser.objects.annotate(
        locale_length=models.Func(models.F('locale'), function='LENGTH'),
        language_iso=models.Func(models.F('locale'), models.Value('-'), models.Value(1), function='split_part', output_field=models.CharField())
    ).filter(locale_length__gt=2).update(
        locale=models.F('language_iso')
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0069_update_device_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tigauser',
            old_name='language_iso2',
            new_name='locale',
        ),
        migrations.AlterField(
            model_name='tigauser',
            name='locale',
            field=models.CharField(choices=[('es', 'Español'), ('ca', 'Català'), ('eu', 'Euskara'), ('bn', 'বাংলা'), ('sv', 'Svenska'), ('en', 'English'), ('de', 'Deutsch'), ('sq', 'Shqip'), ('el', 'Ελληνικά'), ('gl', 'Galego'), ('hu', 'Magyar'), ('pt', 'Português'), ('sl', 'Slovenščina'), ('it', 'Italiano'), ('fr', 'Français'), ('bg', 'Български'), ('ro', 'Română'), ('hr', 'Hrvatski'), ('mk', 'Македонски'), ('sr', 'Српски'), ('lb', 'Lëtzebuergesch'), ('nl', 'Nederlands'), ('tr', 'Türkçe'), ('zh-CN', '中文（中国）')], default='en', help_text="The locale code representing the language preference selected by the user for displaying the interface text. Enter the locale following the BCP 47 standard in 'language' or 'language-region' format (e.g., 'en' for English, 'en-US' for English (United States), 'fr' for French). The language is a two-letter ISO 639-1 code, and the region is an optional two-letter ISO 3166-1 alpha-2 code.", max_length=16, validators=[langcodes.tag_is_valid]),
        ),
        migrations.RunPython(standarize_locale, undo_standarize_locale),
    ]
