# Generated by Django 3.2.25 on 2024-11-29 16:38

from django.db import migrations, models
import numpyencoder.numpyencoder


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0070_tigauser_locale_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tigauser',
            name='score_v2_struct',
            field=models.JSONField(blank=True, encoder=numpyencoder.numpyencoder.NumpyEncoder, help_text='Full cached score data', null=True),
        ),
    ]
