# Generated by Django 3.2.25 on 2024-12-09 12:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


def populate_tigauser_last_location(apps, schema_editor):
    TigaUser = apps.get_model('tigaserver_app', 'TigaUser')
    Report = apps.get_model('tigaserver_app', 'Report')

    last_report_subquery = Report.objects.filter(
        user=models.OuterRef('pk'),
        point__isnull=False
    ).order_by('-server_upload_time')

    TigaUser.objects.update(
        last_location=models.Subquery(last_report_subquery.values('point')[:1]),
        last_location_update=models.Subquery(last_report_subquery.values('server_upload_time')[:1]),
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0072_alter_tigauser_score_v2_struct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tigauser',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='tigauser',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='Last time location was updated', null=True),
        ),
        migrations.RunPython(populate_tigauser_last_location, migrations.RunPython.noop),
    ]
