# Generated by Django 3.2.25 on 2024-12-18 16:05

from django.conf import settings
from django.db import migrations, models
from django.db.models.expressions import Func
from django.db.models.functions import Abs


def populate_report_location_is_masked(apps, schema_editor):

    Report = apps.get_model('tigaserver_app', 'Report')

    Report.objects.alias(
        latitude=Func(
            models.F('point'),
            function='ST_Y',
            output_field=models.FloatField()
        )
    ).annotate(
        latitude_abs=Abs('latitude')
    ).filter(
        models.Q(point__isnull=False) 
        & (
            models.Q(latitude_abs__gt=settings.POLAR_CIRCLE_LATITUDE)
            | models.Q(point__within=settings.OCEAN_GEOM)
        )
    ).update(
        location_is_masked=True
    )


def populate_report_history_location_is_masked(apps, schema_editor):
    Report = apps.get_model('tigaserver_app', 'Report')
    HistoricalReport = apps.get_model("tigaserver_app", "HistoricalReport")

    HistoricalReport.objects.filter(
        version_UUID__in=models.Subquery(
            Report.objects.filter(location_is_masked=True).values('pk')
        )
    ).update(
        location_is_masked=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0073_tigauser_lastlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location_is_masked',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_report_location_is_masked, migrations.RunPython.noop),
        migrations.AddField(
            model_name='historicalreport',
            name='location_is_masked',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_report_history_location_is_masked, migrations.RunPython.noop),
    ]
