# Generated by Django 3.2.25 on 2025-03-27 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0078_report_published_at'),
    ]

    operations = [
        # NutsEurope fiels can not be null
        migrations.AlterField(
            model_name='nutseurope',
            name='levl_code',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='nutseurope',
            name='name_latn',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='nutseurope',
            name='nuts_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='nutseurope',
            name='fid',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='nutseurope',
            name='nuts_name',
            field=models.CharField(max_length=106),
        ),
        # Report nuts_2 and nuts_3 can not be editable
        migrations.AlterField(
            model_name='historicalreport',
            name='nuts_2',
            field=models.CharField(blank=True, editable=False, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='nuts_3',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='nuts_2',
            field=models.CharField(blank=True, editable=False, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='nuts_3',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
        # Adding new Report FK: nuts_2_fk and nuts_3_fk
        migrations.AddField(
            model_name='report',
            name='nuts_2_fk',
            field=models.ForeignKey(limit_choices_to={'levl_code': 2}, null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tigaserver_app.nutseurope'),
        ),
        migrations.AddField(
            model_name='report',
            name='nuts_3_fk',
            field=models.ForeignKey(limit_choices_to={'levl_code': 3}, null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tigaserver_app.nutseurope'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='nuts_2_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'levl_code': 2}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tigaserver_app.nutseurope'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='nuts_3_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'levl_code': 3}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tigaserver_app.nutseurope'),
        ),
    ]
