# Generated by Django 3.2.25 on 2025-03-27 08:49

from django.db import migrations, models

def populate_nuts_fk(apps, schema_editor):
    Report = apps.get_model('tigaserver_app', 'Report')
    HistoricalReport = apps.get_model("tigaserver_app", "HistoricalReport")
    NutsEurope = apps.get_model('tigaserver_app', 'NutsEurope')

    def update_nuts_fk(model, nuts_field, fk_field):
        model.objects.filter(**{f"{nuts_field}__isnull": False}) \
            .exclude(**{nuts_field: ''}) \
            .update(
                **{
                    fk_field: models.Subquery(
                        NutsEurope.objects.filter(
                            nuts_id=models.OuterRef(nuts_field)
                        ).values('pk')[:1]
                    )
                }
            )

    # Apply updates to both Report and HistoricalReport
    for model in [Report, HistoricalReport]:
        update_nuts_fk(model, 'nuts_2', 'nuts_2_fk')
        update_nuts_fk(model, 'nuts_3', 'nuts_3_fk')


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0079_report_nuts_fk'),
    ]

    operations = [
        migrations.RunPython(populate_nuts_fk, migrations.RunPython.noop)
    ]
