# Generated by Django 3.2.25 on 2025-03-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0081_laueurope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ia_filter_1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ia_filter_2',
        ),
        migrations.DeleteModel(
            name='IAScore',
        ),
    ]
