# Generated by Django 3.2.25 on 2025-07-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0082_remove_iascore'),
    ]

    operations = [
        migrations.AddField(
            model_name='europecountry',
            name='reports_can_be_published',
            field=models.BooleanField(default=True),
        ),
    ]
