# Generated by Django 3.2.25 on 2025-08-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0084_alter_mobileapp_package_version'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_is_logged_in_device_id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='is_logged_in',
            new_name='active_session',
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('active_session', True), ('device_id__isnull', False), models.Q(('device_id__exact', ''), _negated=True)), fields=('active_session', 'device_id'), name='unique_active_session_device_id'),
        ),
    ]
