# Generated by Django 3.2.25 on 2025-10-16 13:53

from django.db import migrations, models
import tigaserver_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0085_auto_20250822_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreport',
            name='report_id',
            field=models.CharField(db_index=True, default=tigaserver_app.models.generate_report_id, help_text='4-digit alpha-numeric code generated on user phone to identify each unique report from that user. Digits should lbe randomly drawn from the set of all lowercase and uppercase alphabetic characters and 0-9, but excluding 0, o, and O to avoid confusion if we ever need user to be able to refer to a report ID in correspondence with MoveLab (as was previously the case when we had them sending samples).', max_length=4),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(db_index=True, default=tigaserver_app.models.generate_report_id, help_text='4-digit alpha-numeric code generated on user phone to identify each unique report from that user. Digits should lbe randomly drawn from the set of all lowercase and uppercase alphabetic characters and 0-9, but excluding 0, o, and O to avoid confusion if we ever need user to be able to refer to a report ID in correspondence with MoveLab (as was previously the case when we had them sending samples).', max_length=4),
        ),
    ]
