# Generated by Django 3.2.25 on 2025-10-28 14:49

from django.db import migrations, models
import tigaserver_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0086_auto_20251016_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tigauser',
            name='password',
            field=models.CharField(default=tigaserver_app.models.get_default_password_hash, max_length=128, verbose_name='password'),
        ),
    ]
