# Generated by Django 3.2.25 on 2025-11-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0087_alter_tigauser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionitem',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='missiontrigger',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='report',
            name='mission',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='MissionItem',
        ),
        migrations.DeleteModel(
            name='MissionTrigger',
        ),
    ]
