# Generated by Django 4.2.27 on 2026-01-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0090_remove_europecountry_last_crisis_report_n_update_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('hide', False), ('location_is_masked', False), ('point__isnull', False), ('published_at__isnull', False)), fields=['published_at'], name='report_visible_published_idx'),
        ),
    ]
