# Generated by Django 4.2.27 on 2026-01-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0091_alter_historicalreport_location_is_masked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uuid_tmp',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='uuid_tmp',
            field=models.UUIDField(null=True, db_index=True, editable=False),
        ),
    ]
