# Generated by Django 4.2.27 on 2026-01-27 09:01

from django.db import migrations, models
from django.db.models import F, Func
from django.db.models.functions import Cast
import uuid

def populate_uuid_tmp(apps, schema_editor):
    Report = apps.get_model('tigaserver_app', 'Report')
    Report.objects.update(uuid_tmp=Func(F('version_UUID'), function='uuid'))

def reverse_populate_uuid_tmp(apps, schema_editor):
    Report = apps.get_model('tigaserver_app', 'Report')
    Report.objects.update(version_UUID=Cast(F('uuid_tmp'), output_field=models.CharField()))

def populate_historicalreport_uuid_tmp(apps, schema_editor):
    HistoricalReport = apps.get_model('tigaserver_app', 'HistoricalReport')
    HistoricalReport.objects.update(uuid_tmp=Func(F('version_UUID'), function='uuid'))

def reverse_populate_historicalreport_uuid_tmp(apps, schema_editor):
    HistoricalReport = apps.get_model('tigaserver_app', 'HistoricalReport')
    HistoricalReport.objects.update(version_UUID=Cast(F('uuid_tmp'), output_field=models.CharField()))

class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0092_report_uuid_tmp_addition'),
    ]

    operations = [
        migrations.RunPython(populate_uuid_tmp, reverse_code=reverse_populate_uuid_tmp),
        migrations.AlterField(
            model_name='report',
            name='uuid_tmp',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(populate_historicalreport_uuid_tmp, reverse_code=reverse_populate_historicalreport_uuid_tmp),
        migrations.AlterField(
            model_name='historicalreport',
            name='uuid_tmp',
            field=models.UUIDField(default=uuid.uuid4, db_index=True, editable=False),
        ),
    ]
