# Generated by Django 4.2.27 on 2026-02-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0092_report_tag_345_mark_as_hidden'),
        ('tigacrafting', '0042_expertreportannotation_is_blood_fed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='blood_genre',
        ),
    ]
