# Generated by Django 4.2.27 on 2026-01-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0093_report_uuid_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='report_uuid',
            field=models.UUIDField(null=True),
            # field=models.ForeignKey(blank=True, default=None, help_text='Report which the award refers to. Can be blank for arbitrary awards', null=True, on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        ),
        migrations.AddField(
            model_name='notification',
            name='report_uuid',
            field=models.UUIDField(null=True),
            # field=models.ForeignKey(blank=True, help_text='Report regarding the current notification', null=True, on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        ),
        migrations.AddField(
            model_name='photo',
            name='report_uuid',
            field=models.UUIDField(null=True),
            # field=models.ForeignKey(null=True, help_text='Report and version to which this photo is associated (36-digit report_UUID).', on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        ),
        migrations.AddField(
            model_name='reportresponse',
            name='report_uuid',
            field=models.UUIDField(null=True),
            # field=models.ForeignKey(null=True, help_text='Report to which this response is associated.', on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        ),
    ]
