# Generated by Django 4.2.27 on 2026-01-27 09:16

from django.db import migrations, models
from django.db.models import F, Func
from django.db.models.functions import Cast

def populate_award_report_uuid(apps, schema_editor):
    Award = apps.get_model('tigaserver_app', 'Award')
    Award.objects.filter(report__isnull=False).update(report_uuid=Func(F('report_id'), function='uuid'))

def reverse_populate_award_report_uuid(apps, schema_editor):
    Award = apps.get_model('tigaserver_app', 'Award')
    Award.objects.filter(report_uuid__isnull=False).update(report_id=Cast(F('report_uuid'), output_field=models.CharField()))

def populate_notification_report_uuid(apps, schema_editor):
    Notification = apps.get_model('tigaserver_app', 'Notification')
    Notification.objects.filter(report__isnull=False).update(report_uuid=Func(F('report_id'), function='uuid'))

def reverse_populate_notification_report_uuid(apps, schema_editor):
    Notification = apps.get_model('tigaserver_app', 'Notification')
    Notification.objects.filter(report_uuid__isnull=False).update(report_id=Cast(F('report_uuid'), output_field=models.CharField()))

def populate_photo_report_uuid(apps, schema_editor):
    Photo = apps.get_model('tigaserver_app', 'Photo')
    Photo.objects.update(report_uuid=Func(F('report_id'), function='uuid'))

def reverse_populate_photo_report_uuid(apps, schema_editor):
    Photo = apps.get_model('tigaserver_app', 'Photo')
    Photo.objects.update(report_id=Cast(F('report_uuid'), output_field=models.CharField()))

def populate_reportresponse_report_uuid(apps, schema_editor):
    ReportResponse = apps.get_model('tigaserver_app', 'ReportResponse')
    ReportResponse.objects.update(report_uuid=Func(F('report_id'), function='uuid'))

def reverse_populate_reportresponse_report_uuid(apps, schema_editor):
    ReportResponse = apps.get_model('tigaserver_app', 'ReportResponse')
    ReportResponse.objects.update(report_id=Cast(F('report_uuid'), output_field=models.CharField()))

class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0094_addition_report_uuid_fk'),
    ]

    operations = [
        migrations.RunPython(populate_award_report_uuid, reverse_code=reverse_populate_award_report_uuid),
        migrations.RunPython(populate_notification_report_uuid, reverse_code=reverse_populate_notification_report_uuid),
        migrations.RunPython(populate_photo_report_uuid, reverse_code=reverse_populate_photo_report_uuid),
        migrations.AlterField(
            model_name='photo',
            name='report_uuid',
            field=models.UUIDField(),
            # field=models.ForeignKey(help_text='Report and version to which this photo is associated (36-digit report_UUID).', on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        ),
        migrations.RunPython(populate_reportresponse_report_uuid, reverse_code=reverse_populate_reportresponse_report_uuid),
        migrations.AlterField(
            model_name='reportresponse',
            name='report_uuid',
            field=models.UUIDField(),
            # field=models.ForeignKey(help_text='Report to which this response is associated.', on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.report', to_field='uuid_tmp'),
        )
    ]
