# Generated by Django 4.2.27 on 2026-01-27 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tigacrafting', '0044_alter_expertreportannotation_report_uuid_and_more'),
        ('tigaserver_app', '0095_populate_report_uuid_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='report',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='report',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportresponse',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='version_UUID',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='uuid_tmp',
            new_name='version_UUID',
        ),
        migrations.AlterField(
            model_name='report',
            name='version_UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='historicalreport',
            name='version_UUID',
        ),
    ]
