# Generated by Django 4.2.27 on 2026-01-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0096_remove_historicalreport_version_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='report_uuid',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='report_uuid',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='report_uuid',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='reportresponse',
            old_name='report_uuid',
            new_name='report',
        )
    ]
