# Generated by Django 4.2.27 on 2026-01-27 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tigaserver_app', '0097_remove_award_report_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalreport',
            old_name='uuid_tmp',
            new_name='version_UUID',
        ),
        migrations.AlterField(
            model_name='award',
            name='report',
            field=models.ForeignKey(blank=True, default=None, help_text='Report which the award refers to. Can be blank for arbitrary awards', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_award', to='tigaserver_app.report'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Report regarding the current notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_notifications', to='tigaserver_app.report'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='report',
            field=models.ForeignKey(help_text='Report and version to which this photo is associated (36-digit report_UUID).', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tigaserver_app.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='version_UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportresponse',
            name='report',
            field=models.ForeignKey(help_text='Report to which this response is associated.', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tigaserver_app.report'),
        ),
    ]
