# Generated by Django 4.2.29 on 2026-03-20 15:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='EuropeCountry',
                    fields=[
                        ('gid', models.AutoField(primary_key=True, serialize=False)),
                        ('cntr_id', models.CharField(blank=True, max_length=2)),
                        ('name_engl', models.CharField(help_text='Full name of the country in English (e.g., Spain).', max_length=44)),
                        ('iso3_code', models.CharField(help_text='ISO 3166-1 alpha-3 country code (3-letter code, e.g., ESP).', max_length=3)),
                        ('fid', models.CharField(blank=True, max_length=2)),
                        ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                        ('x_min', models.FloatField(blank=True, null=True)),
                        ('x_max', models.FloatField(blank=True, null=True)),
                        ('y_min', models.FloatField(blank=True, null=True)),
                        ('y_max', models.FloatField(blank=True, null=True)),
                        ('is_bounding_box', models.BooleanField(db_index=True, default=False, help_text='If true, this geometry acts as a bounding box. The bounding boxes act as little separate entolabs, in the sense that no reports located inside a bounding box should reach an expert outside this bounding box')),
                        ('national_supervisor_report_expires_in', models.IntegerField(db_index=True, default=14, help_text='Number of days that a report in the queue is exclusively available to the nagional supervisor. For example, if the field value is 6, after report_creation_time + 6 days a report will be available to all users')),
                        ('reports_can_be_published', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'europe_countries',
                        'ordering': ['name_engl'],
                    },
                ),
                migrations.CreateModel(
                    name='LauEurope',
                    fields=[
                        ('gid', models.AutoField(primary_key=True, serialize=False)),
                        ('lau_id', models.CharField(max_length=13)),
                        ('lau_name', models.CharField(max_length=80)),
                        ('gisco_id', models.CharField(blank=True, max_length=16, null=True)),
                        ('cntr_id', models.CharField(blank=True, max_length=2, null=True)),
                        ('fid', models.CharField(max_length=16, unique=True)),
                        ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                    ],
                    options={
                        'db_table': 'lau_rg_01m_2018_4326',
                    },
                ),
                migrations.CreateModel(
                    name='NutsEurope',
                    fields=[
                        ('gid', models.AutoField(primary_key=True, serialize=False)),
                        ('nuts_id', models.CharField(max_length=5)),
                        ('levl_code', models.SmallIntegerField()),
                        ('cntr_code', models.CharField(blank=True, max_length=2, null=True)),
                        ('name_latn', models.CharField(max_length=70)),
                        ('nuts_name', models.CharField(max_length=106)),
                        ('mount_type', models.SmallIntegerField(blank=True, null=True)),
                        ('urbn_type', models.SmallIntegerField(blank=True, null=True)),
                        ('coast_type', models.SmallIntegerField(blank=True, null=True)),
                        ('fid', models.CharField(max_length=5, unique=True)),
                        ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                        ('europecountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nuts', to='geo.europecountry')),
                    ],
                    options={
                        'db_table': 'nuts_europe',
                    },
                ),
            ],
        )
    ]
