# Generated by Django 4.2.29 on 2026-05-27 12:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='europecountry',
            old_name='gid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='europecountry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='europecountry',
            name='cntr_id',
        ),
        migrations.RemoveField(
            model_name='europecountry',
            name='fid',
        ),
        migrations.AlterField(
            model_name='europecountry',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='europecountry',
            name='iso3_code',
            field=models.CharField(help_text='ISO 3166-1 alpha-3 country code (3-letter code, e.g., ESP).', max_length=3, unique=True),
        ),
        migrations.RemoveField(
            model_name='europecountry',
            name='x_max',
        ),
        migrations.RemoveField(
            model_name='europecountry',
            name='x_min',
        ),
        migrations.RemoveField(
            model_name='europecountry',
            name='y_max',
        ),
        migrations.RemoveField(
            model_name='europecountry',
            name='y_min',
        ),
    ]
