# Generated by Django 4.0.8 on 2023-02-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundarygeometry',
            name='id',
        ),
        migrations.AlterField(
            model_name='boundarygeometry',
            name='boundary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='geometry_model', serialize=False, to='geo.boundary'),
        ),
    ]
