# Generated by Django 4.2.29 on 2026-04-28 12:48

from django.db import migrations

def populate_national_supervisor_report_expires_in_from_workspace(apps, schema_editor):
    Workspace = apps.get_model("workspaces", "Workspace")

    for workspace in Workspace.objects.all():
        country = workspace.country
        country.national_supervisor_report_expires_in = workspace.supervisor_exclusivity_days
        country.save()

def populate_reports_can_be_published_from_workspace(apps, schema_editor):
    Workspace = apps.get_model("workspaces", "Workspace")

    for workspace in Workspace.objects.all():
        country = workspace.country
        country.reports_can_be_published = workspace.is_public
        country.save()

class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='europecountry',
            name='is_bounding_box',
        ),
        migrations.RemoveField(
            model_name='europecountry',
            name='national_supervisor_report_expires_in',
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=populate_national_supervisor_report_expires_in_from_workspace),
        migrations.RemoveField(
            model_name='europecountry',
            name='reports_can_be_published',
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=populate_reports_can_be_published_from_workspace),
    ]
