# Generated by Django 4.2.29 on 2026-05-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_remove_europecountry_is_bounding_box_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='europecountry',
            old_name='gid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='europecountry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
