# Generated by Django 4.2.29 on 2026-05-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('reports', '0001_initial'),
        ('geo', '0002_remove_unecessary_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EuropeCountry',
            new_name='Country',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name_engl'], 'verbose_name_plural': 'countries'},
        ),
    ]
