# Generated by Django 4.2.3 on 2023-11-30 17:10

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0002_alter_boundary_created_at_alter_boundary_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(blank=True, editable=False, null=True),
        ),
    ]
