# Generated by Django 4.2.29 on 2026-05-27 12:41

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_rename_europecountry_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subregion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(choices=[('africa', 'Africa'), ('antarctica', 'Antarctica'), ('asia', 'Asia'), ('europe', 'Europe'), ('north_america', 'North America'), ('oceania', 'Oceania'), ('south_america', 'South America'), ('seven_seas', 'Seven Seas (open ocean)')], max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='geo.subregion'),
        ),
    ]
