# Generated by Django 4.2.29 on 2026-05-27 12:41

from django.db import migrations, models
import django.db.models.deletion

from mosquito_alert.geo.models import Continent

def populate_subregion(apps, schema_editor):
    Country = apps.get_model('geo', 'Country')
    Subregion = apps.get_model('geo', 'Subregion')

    for country in Country.objects.all():
        if country.subregion_name and country.continent_name:
            subregion, _ = Subregion.objects.get_or_create(
                name=country.subregion_name,
                continent=Continent.get_by_most_similar_name(country.continent_name),
            )
            country.subregion = subregion
            country.save()

def undo_populate_subregion(apps, schema_editor):
    Country = apps.get_model('geo', 'Country')
    Subregion = apps.get_model('geo', 'Subregion')

    for country in Country.objects.all():
        if country.subregion:
            country.subregion_name = country.subregion.name
            country.continent_name = country.subregion.continent
            country.save()

    Subregion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_populate_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subregion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(choices=[('africa', 'Africa'), ('antarctica', 'Antarctica'), ('asia', 'Asia'), ('europe', 'Europe'), ('north_america', 'North America'), ('oceania', 'Oceania'), ('south_america', 'South America'), ('seven_seas', 'Seven Seas (open ocean)')], max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='geo.subregion'),
        ),
        migrations.RunPython(populate_subregion, reverse_code=undo_populate_subregion),
        migrations.RemoveField(
            model_name='country',
            name='continent_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='subregion_name',
        ),
    ]
