# Generated by Django 4.2.29 on 2026-05-27 12:41

from django.contrib.gis.gdal import DataSource
from django.contrib.gis.geos import MultiPolygon
from django.db import migrations

from pathlib import Path



def populate_countries(apps, schema_editor):
    Country = apps.get_model('geo', 'Country')

    world_gpkg = "/vsizip/" + str(Path(__file__).parent.parent / "fixtures" / "ne_10m_admin_0_countries.zip")

    # Need to clear the geom field before populating it,
    # otherwise the unique constraint on iso3_code will cause issues when trying to update the geom field for existing records
    ds = DataSource(world_gpkg)
    layer = ds[0]

    for feature in layer:
        geom = feature.geom.geos if feature.geom else None

        # Convert Polygon -> MultiPolygon
        if geom and geom.geom_type == "Polygon":
            geom = MultiPolygon(geom)

        iso3 = feature.get('ISO_A3_EH')
        if iso3 == "-99":
            iso3 = feature.get('ADM0_A3')

        Country.objects.update_or_create(
            iso3_code=iso3,
            defaults={
                'name_engl': feature.get('NAME_LONG'),
                'geom': geom,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_rename_europecountry_country'),
    ]

    operations = [
        migrations.RunPython(
            populate_countries, reverse_code=migrations.RunPython.noop
        ),
    ]
