# Generated by Django 4.2.29 on 2026-05-28 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_remove_europecountry_is_bounding_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='wikidata_id',
            field=models.CharField(max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Wikidata ID must start with 'Q' followed by digits (e.g., Q29).", regex='^Q\\d+$')]),
        ),
    ]
