# Generated by Django 4.2.29 on 2026-05-28 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_country_wikidata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='wikidata_id',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Wikidata ID must start with 'Q' followed by digits (e.g., Q29).", regex='^Q\\d+$')]),
        ),
    ]
