# Generated by Django 2.2.7 on 2020-08-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stormdrain',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stormdrainuserversions',
            options={'managed': False},
        ),
    ]
