# Generated by Django 2.2.7 on 2020-06-22 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stormdrain',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 22, 13, 39, 21, 353176), null=True),
        ),
        migrations.AlterField(
            model_name='stormdrainuserversions',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 13, 39, 21, 355669)),
        ),
    ]
