# Generated by Django 2.2.7 on 2021-02-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0002_auto_20200807_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irideon',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('record_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('classification', models.CharField(blank=True, max_length=255, null=True)),
                ('client_name', models.CharField(blank=True, max_length=30, null=True)),
                ('client_type', models.CharField(blank=True, max_length=20, null=True)),
                ('lon', models.FloatField(db_column='lng')),
                ('lat', models.FloatField()),
                ('nice_name', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
