# Generated by Django 2.2.7 on 2024-03-04 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0003_irideon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Userfixes',
        ),
        migrations.AlterField(
            model_name='epidemiology',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observationnotifications',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observationnotifications',
            name='notification_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.NotificationContent'),
        ),
        migrations.AlterField(
            model_name='predefinednotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='NotificationContent',
        ),
    ]
