# Generated by Django 2.2.7 on 2024-03-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0003_irideon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Userfixes',
        ),
        migrations.AlterModelOptions(
            name='mapauxreports',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='observationnotifications',
            name='notification_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigaserver_app.NotificationContent'),
        ),
        migrations.DeleteModel(
            name='NotificationContent',
        ),
    ]
