# Generated by Django 2.2.7 on 2024-08-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0004_auto_20240315_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapauxreports',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stormdrain',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stormdrainuserversions',
            options={'managed': True},
        ),
    ]
