# Generated by Django 2.2.7 on 2019-11-08 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0004_auto_20191108_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stormdrain',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 8, 14, 30, 57, 387783), null=True),
        ),
        migrations.AlterField(
            model_name='stormdrainuserversions',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 14, 30, 57, 390308)),
        ),
    ]
