# Generated by Django 2.2.7 on 2024-10-23 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0004_auto_20240315_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stormdrain',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='stormdrainuserversions',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
