# Generated by Django 2.2.7 on 2024-03-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0004_auto_20240304_1225'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='irideon',
        #     options={'managed': True},
        # ),
        # migrations.AlterModelOptions(
        #     name='reportsmapdata',
        #     options={'managed': True},
        # ),
        migrations.AlterModelOptions(
            name='stormdrain',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stormdrainuserversions',
            options={'managed': True},
        ),
    ]
