# Generated by Django 2.2.7 on 2019-11-08 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0005_auto_20191108_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stormdrain',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='stormdrainuserversions',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 14, 32, 3, 157182)),
        ),
    ]
