# Generated by Django 2.2.7 on 2024-08-16 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0005_auto_20240816_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapauxreports',
            name='version_uuid',
            field=models.OneToOneField(db_column='version_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='map_aux_report', to='tigaserver_app.Report'),
        ),
        migrations.AlterField(
            model_name='stormdrain',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='stormdrainuserversions',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
