# Generated by Django 2.2.7 on 2024-10-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0005_auto_20241023_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymoususer',
            options={},
        ),
    ]
