# Generated by Django 2.2.7 on 2019-11-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0006_auto_20191108_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stormdrainuserversions',
            options={'managed': False},
        ),
    ]
