# Generated by Django 2.2.7 on 2024-03-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0006_auto_20240305_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapauxreports',
            options={'managed': False},
        ),
    ]
