# Generated by Django 2.2.7 on 2024-03-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0007_auto_20240312_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapauxreports',
            options={'managed': True},
        ),
    ]
