# Generated by Django 2.2.7 on 2024-03-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigapublic', '0008_auto_20240312_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapauxreports',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mapauxreports',
            name='version_uuid',
            field=models.OneToOneField(db_column='version_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='map_aux_report', to='tigaserver_app.Report'),
        ),
    ]
