# Generated by Django 4.0.8 on 2023-01-20 14:24

from django.db import migrations, models
import django.utils.timezone
import mosquito_alert.images.fields
import mosquito_alert.images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', mosquito_alert.images.fields.ProcessedImageField(upload_to=mosquito_alert.images.models.image_upload_to)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['-created_at'],
                'permissions': [('view_exif', 'Can view exif metadata')],
            },
        ),
    ]
