# Generated by Django 4.0.8 on 2023-03-01 13:06

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mosquito_alert.images.fields
import mosquito_alert.images.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "image",
                    mosquito_alert.images.fields.ProcessedImageField(
                        upload_to=mosquito_alert.images.models.image_upload_to
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "photo",
                "verbose_name_plural": "photos",
                "ordering": ["-created_at"],
                "permissions": [("view_exif", "Can view exif metadata")],
            },
        ),
    ]
