# Generated by Django 4.0.8 on 2023-03-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_photo_taken_at_alter_photo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='taken_at',
        ),
    ]
