# Generated by Django 4.2.29 on 2026-03-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='RankingData',
                    fields=[
                        ('user_uuid', models.CharField(help_text='User identifier uuid', max_length=36, primary_key=True, serialize=False)),
                        ('class_value', models.CharField(max_length=60)),
                        ('rank', models.IntegerField()),
                        ('score_v2', models.IntegerField()),
                        ('last_update', models.DateTimeField(blank=True, help_text='Last time ranking data was updated', null=True)),
                    ],
                    options={
                        'db_table': 'tigaserver_app_rankingdata',
                    },
                ),
            ]
        )
    ]
