# Generated by Django 4.0.8 on 2023-01-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('SD', 'Storm drain')], max_length=2, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='geo.location')),
            ],
            options={
                'verbose_name': 'breeding site',
                'verbose_name_plural': 'breeding sites',
            },
        ),
    ]
