# Generated by Django 4.2.29 on 2026-03-20 08:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tigaserver_app', '0094_alter_tigauser_locale'),
        ('tigacrafting', '0058_remove_identificationtask_assignees_and_more'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='IdentificationTask',
                    fields=[
                        ('report', models.OneToOneField(limit_choices_to={'type': 'adult'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='identification_task', serialize=False, to='tigaserver_app.report')),
                        ('status', models.CharField(choices=[('open', 'Open'), ('conflict', 'Conflict'), ('review', 'Review'), ('done', 'Done'), ('archived', 'Archived')], db_index=True, default='open', max_length=16)),
                        ('is_flagged', models.BooleanField(default=False, editable=False)),
                        ('is_safe', models.BooleanField(default=False, editable=False, help_text='Indicates if the content is safe for publication.')),
                        ('public_note', models.TextField(blank=True, editable=False, null=True)),
                        ('message_for_user', models.TextField(blank=True, editable=False, null=True)),
                        ('total_annotations', models.PositiveSmallIntegerField(default=0, editable=False)),
                        ('total_finished_annotations', models.PositiveSmallIntegerField(default=0, editable=False)),
                        ('result_source', models.CharField(blank=True, choices=[('expert', 'Expert'), ('ai', 'Artificial Intelligence')], editable=False, max_length=8, null=True)),
                        ('review_type', models.CharField(blank=True, choices=[('agree', 'Agreed with experts'), ('overwrite', 'Overwritten')], default=None, editable=False, max_length=16, null=True)),
                        ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                        ('pred_insect_confidence', models.FloatField(blank=True, editable=False, help_text='The insect confidence from the predictions.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('confidence', models.DecimalField(decimal_places=6, default=Decimal('0'), editable=False, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                        ('uncertainty', models.FloatField(default=1.0, editable=False, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('agreement', models.FloatField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default=None, editable=False, max_length=10, null=True)),
                        ('is_blood_fed', models.BooleanField(blank=True, default=None, editable=False, null=True)),
                        ('is_gravid', models.BooleanField(blank=True, default=None, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('assignees', models.ManyToManyField(through='identification_tasks.ExpertReportAnnotation', to=settings.AUTH_USER_MODEL)),
                        ('photo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='identification_tasks', to='tigaserver_app.photo')),
                        ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_tasks_reviewed', to=settings.AUTH_USER_MODEL)),
                        ('taxon', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxa.taxon')),
                    ],
                    options={
                        'db_table': 'tigacrafting_identificationtask',
                        'permissions': [('view_archived_identificationtasks', 'Can view archived records'), ('add_review', 'Can review')],
                    },
                ),
                migrations.AddIndex(
                    model_name='identificationtask',
                    index=models.Index(fields=['taxon', 'report'], name='tigacraftin_taxon_i_d594e3_idx'),
                ),
                migrations.AddConstraint(
                    model_name='identificationtask',
                    constraint=models.CheckConstraint(check=models.Q(('review_type__isnull', True), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='review_requires_fields_if_set'),
                ),
                migrations.AddConstraint(
                    model_name='identificationtask',
                    constraint=models.CheckConstraint(check=models.Q(('total_finished_annotations__lte', models.F('total_annotations'))), name='total_finished_annotations_lte_total_annotations'),
                ),
                migrations.CreateModel(
                    name='ExpertReportAnnotation',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.IntegerField(choices=[(1, 'Public'), (0, 'Flagged'), (-1, 'Hidden')], default=1, help_text='Whether report should be displayed on public map, flagged for further checking before public display), or hidden.', verbose_name='Status')),
                        ('internal_note', models.TextField(blank=True, help_text='Internal notes for yourself or other experts', null=True)),
                        ('public_note', models.TextField(blank=True, help_text='Notes to display on public map', null=True)),
                        ('message_for_user', models.TextField(blank=True, help_text='Message that user will receive when viewing report on phone', null=True)),
                        ('is_finished', models.BooleanField(db_index=True, default=True, help_text='Mark this when you have completed your review and are ready for your annotation to be displayed to public.')),
                        ('linked_id', models.CharField(blank=True, help_text='Use this field to add any other ID that you want to associate the record with (e.g., from some other database).', max_length=10, verbose_name='Linked ID')),
                        ('is_simplified', models.BooleanField(default=False, help_text='If True, the report annotation interface shows less input controls')),
                        ('decision_level', models.CharField(choices=[('normal', 'Normal'), ('executive', 'Executive'), ('final', 'Final')], default='normal', max_length=16)),
                        ('is_favourite', models.BooleanField(default=False)),
                        ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=10, null=True)),
                        ('is_blood_fed', models.BooleanField(blank=True, default=None, null=True)),
                        ('is_gravid', models.BooleanField(blank=True, default=None, null=True)),
                        ('created', models.DateTimeField(auto_now_add=True)),
                        ('last_modified', models.DateTimeField(auto_now=True)),
                        ('best_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_report_annotations', to='tigaserver_app.photo')),
                        ('identification_task', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='expert_report_annotations', to='identification_tasks.identificationtask')),
                        ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxa.taxon')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_report_annotations', to=settings.AUTH_USER_MODEL))
                    ],
                    options={
                        'db_table': 'tigacrafting_expertreportannotation',
                    },
                ),
                migrations.AddField(
                    model_name='expertreportannotation',
                    name='tags',
                    field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
                ),
                migrations.AddConstraint(
                    model_name='expertreportannotation',
                    constraint=models.UniqueConstraint(fields=('user', 'identification_task'), name='unique_assignation'),
                ),
                migrations.AddConstraint(
                    model_name='expertreportannotation',
                    constraint=models.CheckConstraint(check=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='expertreportannotation_confidence_between_0_and_1'),
                ),
                migrations.AddConstraint(
                    model_name='expertreportannotation',
                    constraint=models.CheckConstraint(check=models.Q(('sex', 'male'), ('is_blood_fed', True), _negated=True), name='expertreportannotation_blood_fed_only_if_female'),
                ),
                migrations.AddConstraint(
                    model_name='expertreportannotation',
                    constraint=models.CheckConstraint(check=models.Q(('sex', 'male'), ('is_gravid', True), _negated=True), name='expertreportannotation_gravid_only_if_female'),
                ),
                migrations.CreateModel(
                    name='PhotoPrediction',
                    fields=[
                        ('photo', models.OneToOneField(help_text='Photo to which the score refers to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prediction', serialize=False, to='tigaserver_app.photo')),
                        ('classifier_version', models.CharField(choices=[('v2023.1', 'v2023.1'), ('v2024.1', 'v2024.1'), ('v2025.1', 'v2025.1'), ('v2025.2', 'v2025.2'), ('v2025.3', 'v2025.3'), ('v2025.4', 'v2025.4')], max_length=16)),
                        ('is_decisive', models.BooleanField(default=False, help_text='Indicates if this prediction can close the identification task.')),
                        ('insect_confidence', models.FloatField(help_text='Insect confidence', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('predicted_class', models.CharField(choices=[('ae_albopictus', 'Aedes albopictus'), ('ae_aegypti', 'Aedes aegypti'), ('ae_japonicus', 'Aedes japonicus'), ('ae_koreicus', 'Aedes koreicus'), ('culex', 'Culex (s.p)'), ('anopheles', 'Anopheles (s.p.)'), ('culiseta', 'Culiseta (s.p.)'), ('other_species', 'Ohter species'), ('not_sure', 'Unidentifiable')], default='not_sure', max_length=32, null=True)),
                        ('threshold_deviation', models.FloatField(validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('x_tl', models.FloatField(help_text='photo bounding box relative coordinates top left x', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('x_br', models.FloatField(help_text='photo bounding box relative coordinates bottom right x', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('y_tl', models.FloatField(help_text='photo bounding box relative coordinates top left y', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('y_br', models.FloatField(help_text='photo bounding box relative coordinates bottom right y', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('ae_albopictus_score', models.FloatField(help_text='Score value for the class Aedes albopictus', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('ae_aegypti_score', models.FloatField(help_text='Score value for the class Aedes aegypti', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('ae_japonicus_score', models.FloatField(help_text='Score value for the class Aedes japonicus', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('ae_koreicus_score', models.FloatField(help_text='Score value for the class Aedes koreicus', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('culex_score', models.FloatField(help_text='Score value for the class Culex (s.p)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('anopheles_score', models.FloatField(help_text='Score value for the class Anopheles (s.p.)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('culiseta_score', models.FloatField(help_text='Score value for the class Culiseta (s.p.)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('other_species_score', models.FloatField(help_text='Score value for the class Ohter species', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('not_sure_score', models.FloatField(help_text='Score value for the class Unidentifiable', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                        ('identification_task', models.ForeignKey(help_text='Identification task to which the photo belongs', on_delete=django.db.models.deletion.CASCADE, related_name='photo_predictions', to='identification_tasks.identificationtask')),
                        ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxa.taxon')),
                    ],
                    options={
                        'db_table': 'tigacrafting_photoprediction',
                    },
                ),
                migrations.AddConstraint(
                    model_name='photoprediction',
                    constraint=models.CheckConstraint(check=models.Q(('x_tl__lte', models.F('x_br'))), name='x_tl_less_equal_x_br'),
                ),
                migrations.AddConstraint(
                    model_name='photoprediction',
                    constraint=models.CheckConstraint(check=models.Q(('y_tl__lte', models.F('y_br'))), name='y_tl_less_equal_y_br'),
                ),
                migrations.AddConstraint(
                    model_name='photoprediction',
                    constraint=models.UniqueConstraint(condition=models.Q(('is_decisive', True)), fields=('identification_task',), name='unique_final_prediction_per_task'),
                ),
                migrations.AddConstraint(
                    model_name='photoprediction',
                    constraint=models.UniqueConstraint(fields=('photo', 'identification_task'), name='unique_photo_identification_task'),
                ),
            ],
        ),
        # Rename constraints to follow new naming convention
        
        migrations.AddConstraint(
            model_name='identificationtask',
            constraint=models.CheckConstraint(check=models.Q(('confidence__range', (Decimal('0'), Decimal('1')))), name='identification_tasks_identificationtask_confidence_between_0_and_1'),
        ),
        
        migrations.AddConstraint(
            model_name='identificationtask',
            constraint=models.CheckConstraint(check=models.Q(('uncertainty__range', (0, 1))), name='identification_tasks_identificationtask_uncertainty_between_0_and_1'),
        ),
        
        migrations.AddConstraint(
            model_name='identificationtask',
            constraint=models.CheckConstraint(check=models.Q(('agreement__range', (0, 1))), name='identification_tasks_identificationtask_agreement_between_0_and_1'),
        ),
        
        migrations.AddConstraint(
            model_name='identificationtask',
            constraint=models.CheckConstraint(check=models.Q(('sex', 'male'), ('is_blood_fed', True), _negated=True), name='identification_tasks_identificationtask_blood_fed_only_if_female'),
        ),
        
        migrations.AddConstraint(
            model_name='identificationtask',
            constraint=models.CheckConstraint(check=models.Q(('sex', 'male'), ('is_gravid', True), _negated=True), name='identification_tasks_identificationtask_gravid_only_if_female'),
        ),
        
        migrations.AddConstraint(
            model_name='photoprediction',
            constraint=models.CheckConstraint(check=models.Q(('x_tl__range', (0, 1))), name='identification_tasks_photoprediction_x_tl_between_0_and_1'),
        ),
        
        migrations.AddConstraint(
            model_name='photoprediction',
            constraint=models.CheckConstraint(check=models.Q(('x_br__range', (0, 1))), name='identification_tasks_photoprediction_x_br_between_0_and_1'),
        ),
        
        migrations.AddConstraint(
            model_name='photoprediction',
            constraint=models.CheckConstraint(check=models.Q(('y_tl__range', (0, 1))), name='identification_tasks_photoprediction_y_tl_between_0_and_1'),
        ),
        
        migrations.AddConstraint(
            model_name='photoprediction',
            constraint=models.CheckConstraint(check=models.Q(('y_br__range', (0, 1))), name='identification_tasks_photoprediction_y_br_between_0_and_1'),
        ),
    ]
