# Generated by Django 4.2.29 on 2026-03-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('identification_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertreportannotation',
            name='best_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_report_annotations', to='reports.photo'),
        ),
        migrations.AlterField(
            model_name='identificationtask',
            name='photo',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='identification_tasks', to='reports.photo'),
        ),
        migrations.AlterField(
            model_name='identificationtask',
            name='report',
            field=models.OneToOneField(limit_choices_to={'type': 'adult'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='identification_task', serialize=False, to='reports.report'),
        ),
        migrations.AlterField(
            model_name='photoprediction',
            name='photo',
            field=models.OneToOneField(help_text='Photo to which the score refers to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prediction', serialize=False, to='reports.photo'),
        ),
    ]
