# Generated by Django 4.2.30 on 2026-09-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprediction',
            name='classifier_version',
            field=models.CharField(choices=[('v2023.1', 'v2023.1'), ('v2024.1', 'v2024.1'), ('v2025.1', 'v2025.1'), ('v2025.2', 'v2025.2'), ('v2025.3', 'v2025.3'), ('v2025.4', 'v2025.4'), ('v2026.1', 'v2026.1')], max_length=16),
        ),
    ]
