data = {
    "es": {
        "question_1": "¿Cuántas picaduras tienes y en qué parte del cuerpo?",
        "question_1_answer_11": "",
        "question_2": "¿Donde te han picado?",
        "question_2_answer_21": "Cabeza",
        "question_2_answer_22": "Brazo izquierdo",
        "question_2_answer_23": "Brazo derecho",
        "question_2_answer_24": "Pecho",
        "question_2_answer_25": "Pierna izquierda",
        "question_2_answer_26": "Pierna derecha",
        "question_3": "¿En qué momento ha sido?",
        "question_3_answer_31": "Mañana",
        "question_3_answer_32": "Mediodía",
        "question_3_answer_33": "Tarde",
        "question_3_answer_34": "Noche",
        "question_4": "¿Dónde te han picado?",
        "question_4_answer_41": "Dentro de un vehículo",
        "question_4_answer_42": "Dentro de un edificio",
        "question_5": "¿Cuando te han picado?",
        "question_5_answer_51": "Ahora mismo",
        "question_5_answer_52": "En las últimas 24h",
        "question_6": "¿Qué tipo de mosquito crees que es?",
        "question_6_answer_61": "Aedes invasor",
        "question_6_answer_62": "Mosquito común",
        "question_6_answer_63": "Otro",
        "question_6_answer_64": "No lo sé",
        "question_7": "¿Cómo es el mosquito?",
        "question_7_answer_711": "Tórax 1",
        "question_7_answer_712": "Tórax 2",
        "question_7_answer_713": "Tórax 3",
        "question_7_answer_714": "Tórax 4",
        "question_7_answer_721": "Abdomen 1",
        "question_7_answer_722": "Abdomen 2",
        "question_7_answer_723": "Abdomen 3",
        "question_7_answer_724": "Abdomen 4",
        "question_7_answer_731": "Pata 1",
        "question_7_answer_732": "Pata 2",
        "question_7_answer_733": "Pata 3",
        "question_7_answer_734": "Pata 4",
        "question_8": "¿Te ha picado el mosquito?",
        "question_8_answer_81": "No",
        "question_8_answer_82": "Si",
        "question_10": "¿Tiene agua?",
        "question_10_answer_101": "Sí",
        "question_10_answer_102": "No",
        "question_12": "¿Cómo es el lugar de cría detectado en la vía pública?",
        "question_12_answer_121": "Imbornal",
        "question_12_answer_122": "Otro tipo",
        "question_13": "¿Dónde has encontrado el mosquito?",
        "question_13_answer_131": "Dentro de un vehículo",
        "question_13_answer_132": "Dentro de un edificio",
        "question_13_answer_133": "En el exterior",
        "question_14": "¿Dónde te encontrabas cuando te han picado?",
        "question_15": "¿Dónde has encontrado el mosquito?",
        "question_16": "¿Dónde se encuentra el lugar de cría?",
        "question_4_answer_43": "En el exterior",
        "question_4_answer_44": "No lo sé",
    },
    "en": {
        "question_1": "How many bites do you have and where are they on your body?",
        "question_1_answer_11": "",
        "question_2": "Where did they bite you?",
        "question_2_answer_21": "Head",
        "question_2_answer_22": "Left arm",
        "question_2_answer_23": "Right arm",
        "question_2_answer_24": "Chest",
        "question_2_answer_25": "Left leg",
        "question_2_answer_26": "Right leg",
        "question_3": "What time was it?",
        "question_3_answer_31": "Morning",
        "question_3_answer_32": "Midday",
        "question_3_answer_33": "Afternoon",
        "question_3_answer_34": "Night",
        "question_4": "Where did they bite you?",
        "question_4_answer_41": "Inside a vehicle?",
        "question_4_answer_42": "Inside a building",
        "question_5": "When were you bitten?",
        "question_5_answer_51": "Just now",
        "question_5_answer_52": "In the last 24 hours",
        "question_6": "What type of mosquito do you think it was?",
        "question_6_answer_61": "Invasive Aedes",
        "question_6_answer_62": "Common mosquito",
        "question_6_answer_63": "Other",
        "question_6_answer_64": "I don't know",
        "question_7": "What does the mosquito look like?",
        "question_7_answer_711": "Thorax 1",
        "question_7_answer_712": "Thorax 2",
        "question_7_answer_713": "Thorax 3",
        "question_7_answer_714": "Thorax 4",
        "question_7_answer_721": "Abdomen 1",
        "question_7_answer_722": "Abdomen 2",
        "question_7_answer_723": "Abdomen 3",
        "question_7_answer_724": "Abdomen 4",
        "question_7_answer_731": "Leg 1",
        "question_7_answer_732": "Leg 2",
        "question_7_answer_733": "Leg 3",
        "question_7_answer_734": "Leg 4",
        "question_8": "Did the mosquito bite you?",
        "question_8_answer_81": "No",
        "question_8_answer_82": "Yes",
        "question_10": "Is there water?",
        "question_10_answer_101": "Yes",
        "question_10_answer_102": "No",
        "question_12": "What type of breeding site have you found in a public place?",
        "question_12_answer_121": "Storm drain",
        "question_12_answer_122": "Other",
        "question_13": "Where did you find the mosquito?",
        "question_13_answer_131": "Inside a vehicle",
        "question_13_answer_132": "In a building",
        "question_13_answer_133": "Outdoors",
        "question_14": "Where were you when you were bitten?",
        "question_15": "Where did you find the mosquito?",
        "question_16": "Where is the breeding site?",
        "question_4_answer_43": "Outdoors",
        "question_4_answer_44": "I don't know",
    },
    "ca": {
        "question_1": "Quantes picades tens i en quina part del cos?",
        "question_1_answer_11": "",
        "question_2": "On t'han picat?",
        "question_2_answer_21": "Cap",
        "question_2_answer_22": "Braç esquerre",
        "question_2_answer_23": "Braç dret",
        "question_2_answer_24": "Pit",
        "question_2_answer_25": "Cama esquerra",
        "question_2_answer_26": "Cama dreta",
        "question_3": "En quin moment ha estat?",
        "question_3_answer_31": "Matí",
        "question_3_answer_32": "Migdia",
        "question_3_answer_33": "Tarda",
        "question_3_answer_34": "Nit",
        "question_4": "On t'han picat?",
        "question_4_answer_41": "Dins d'un vehicle",
        "question_4_answer_42": "Dins d'un edifici",
        "question_5": "Quan t'han picat?",
        "question_5_answer_51": "Ara mateix",
        "question_5_answer_52": "En les últimes 24h",
        "question_6": "Quin tipus de mosquit creus que és?",
        "question_6_answer_61": "Aedes invasor",
        "question_6_answer_62": "Mosquit comú",
        "question_6_answer_63": "Altre",
        "question_6_answer_64": "No ho sé",
        "question_7": "Com és el mosquit?",
        "question_7_answer_711": "Tòrax 1",
        "question_7_answer_712": "Tòrax 2",
        "question_7_answer_713": "Tòrax 3",
        "question_7_answer_714": "Tòrax 4",
        "question_7_answer_721": "Abdomen 1",
        "question_7_answer_722": "Abdomen 2",
        "question_7_answer_723": "Abdomen 3",
        "question_7_answer_724": "Abdomen 4",
        "question_7_answer_731": "Pota 1",
        "question_7_answer_732": "Pota 2",
        "question_7_answer_733": "Pota 3",
        "question_7_answer_734": "Pota 4",
        "question_8": "T'ha picat el mosquit?",
        "question_8_answer_81": "No",
        "question_8_answer_82": "Sí",
        "question_10": "Té aigua?",
        "question_10_answer_101": "Sí",
        "question_10_answer_102": "No",
        "question_12": "Com és el lloc de cria detectat a la via pública?",
        "question_12_answer_121": "Embornal",
        "question_12_answer_122": "Un altre tipus",
        "question_13": "On has trobat el mosquit?",
        "question_13_answer_131": "Dins d'un vehicle",
        "question_13_answer_132": "Dins d'un edifici",
        "question_13_answer_133": "A l'exterior",
        "question_14": "On et trobaves quan t'han picat?",
        "question_15": "On has trobat el mosquit?",
        "question_16": "On es troba el lloc de cria?",
        "question_4_answer_43": "A l'exterior",
        "question_4_answer_44": "No ho sé",
    },
    "it": {
        "question_1": "Quante punture hai ricevuto e in che parte del corpo?",
        "question_1_answer_11": "domanda_1_risposta_11",
        "question_2": "Dove ti hanno punto?",
        "question_2_answer_21": "Testa",
        "question_2_answer_22": "Braccio sinistro",
        "question_2_answer_23": "Braccio destro",
        "question_2_answer_24": "Torace",
        "question_2_answer_25": "Gamba sinistra",
        "question_2_answer_26": "Gamba destra",
        "question_3": "Quando è successo?",
        "question_3_answer_31": "Mattina",
        "question_3_answer_32": "Mezzogiorno",
        "question_3_answer_33": "Pomeriggio",
        "question_3_answer_34": "Sera-Notte",
        "question_4": "Dove eri quando ti hanno punto?",
        "question_4_answer_41": "In un veicolo",
        "question_4_answer_42": "In un edificio",
        "question_5": "Quando ti hanno punto?",
        "question_5_answer_51": "Adesso",
        "question_5_answer_52": "Nelle ultime 24 ore",
        "question_6": "Che tipo di zanzare credi sia stata?",
        "question_6_answer_61": "Aedes aliena",
        "question_6_answer_62": "Zanzara comune",
        "question_6_answer_63": "Un'altra",
        "question_6_answer_64": "Non saprei",
        "question_7": "Com'è la zanzara?",
        "question_7_answer_711": "Torace 1",
        "question_7_answer_712": "Torace 2",
        "question_7_answer_713": "Torace 3",
        "question_7_answer_714": "Torace 4",
        "question_7_answer_721": "Addome 1",
        "question_7_answer_722": "Addome 2",
        "question_7_answer_723": "Addome 3",
        "question_7_answer_724": "Addome 4",
        "question_7_answer_731": "Zampa 1",
        "question_7_answer_732": "Zampa 1",
        "question_7_answer_733": "Zampa 3",
        "question_7_answer_734": "Zampa 4",
        "question_8": "La zanzara ti ha punto?",
        "question_8_answer_81": "No",
        "question_8_answer_82": "Si",
        "question_10": "C'è dell'acqua?",
        "question_10_answer_101": "Sì",
        "question_10_answer_102": "No",
        "question_12": "Che tipo di sito di riproduzione hai trovato nella zona pubblica?",
        "question_12_answer_121": "Tombino",
        "question_12_answer_122": "Un altro tipo",
        "question_13": "Dove hai trovato la zanzara?",
        "question_13_answer_131": "In un veicolo",
        "question_13_answer_132": "In un edificio",
        "question_13_answer_133": "All'aperto",
        "question_14": "Dove e quando sei stato punto?",
        "question_15": "Dove hai trovato la zanzara?",
        "question_16": "Dov'è il sito di riproduzione?",
        "question_4_answer_43": "All'aperto",
        "question_4_answer_44": "Non so",
    },
    "el": {
        "question_1": "Αριθμός τσιμπημάτων και σε ποια σημεία του σώματος σας;",
        "question_1_answer_11": "ερώτηση_1_απάντηση_11",
        "question_2": "Που σας έχουν τσιμπήσει;",
        "question_2_answer_21": "Κεφάλι",
        "question_2_answer_22": "Αριστερό χέρι",
        "question_2_answer_23": "Δεξί χέρι",
        "question_2_answer_24": "Θώρακας",
        "question_2_answer_25": "Αριστερό πόδι",
        "question_2_answer_26": "Δεξί πόδι",
        "question_3": "Τι ώρα συνέβη;",
        "question_3_answer_31": "Πρωί",
        "question_3_answer_32": "Μεσημέρι",
        "question_3_answer_33": "Απόγευμα",
        "question_3_answer_34": "Βράδυ",
        "question_4": "Που βρισκόσασταν όταν σας τσίμπησαν;",
        "question_4_answer_41": "Εντός του αυτοκινήτου;",
        "question_4_answer_42": "Μέσα σε χώρο κτηρίου",
        "question_5": "Πότε δεχτήκατε το τσίμπημα;",
        "question_5_answer_51": "Αυτή τη στιγμή",
        "question_5_answer_52": "Το τελευταίο 24ωρο",
        "question_6": "Τι είδος κουνουπιού νομίζετε ότι ήταν;",
        "question_6_answer_61": "Aedes εισβάλλον χωροκατακτητικό",
        "question_6_answer_62": "Κοινό κουνούπι",
        "question_6_answer_63": "Άλλο",
        "question_6_answer_64": "Δεν γνωρίζω",
        "question_7": "Πώς μοιάζει το κουνούπι;",
        "question_7_answer_711": "Θώρακας 1",
        "question_7_answer_712": "Θώρακας 2",
        "question_7_answer_713": "Θώρακας 3",
        "question_7_answer_714": "Θώρακας 4",
        "question_7_answer_721": "Κοιλία 1",
        "question_7_answer_722": "Κοιλία 2",
        "question_7_answer_723": "Κοιλία 3",
        "question_7_answer_724": "Κοιλία 4",
        "question_7_answer_731": "Πόδι 1",
        "question_7_answer_732": "Πόδι 2",
        "question_7_answer_733": "Πόδι 3",
        "question_7_answer_734": "Πόδι 4",
        "question_8": "Σας τσίμπησε το κουνούπι;",
        "question_8_answer_81": "Όχι",
        "question_8_answer_82": "Ναι",
        "question_10": "Υπάρχει νερό/εστία νερού;",
        "question_10_answer_101": "Ναι",
        "question_10_answer_102": "Όχι",
        "question_12": "Τι είδος είναι η εστία ανάπτυξης/αναπαραγωγής κουνουπιών που βρήκατε σε δημόσιο χώρο;",
        "question_12_answer_121": "Αποχετευτικό σύστημα",
        "question_12_answer_122": "Άλλου είδους",
        "question_13": "Πού εντοπίσατε το κουνούπι;",
        "question_13_answer_131": "Μέσα σ' ένα αυτοκίνητο",
        "question_13_answer_132": "Στον εσωτερικό χώρο ενός κτηρίου",
        "question_13_answer_133": "Σε εξωτερικό χώρο",
        "question_14": "Πού βρισκόσασταν όταν σας τσίμπησαν;",
        "question_15": "Πού εντοπίσατε το κουνούπι;",
        "question_16": "Πού εντοπίσατε την εστία ανάπτυξης/αναπαραγωγής του;",
        "question_4_answer_43": "Σε εξωτερικό χώρο",
        "question_4_answer_44": "Δεν το γνωρίζω",
    },
    "tr": {
        "question_1": "Kaç tane ısırığınız var ve bunlar vücudunuzun neresinde?",
        "question_1_answer_11": "",
        "question_2": "Sivrisinek nerenizi soktu?",
        "question_2_answer_21": "Baş",
        "question_2_answer_22": "Sol kol",
        "question_2_answer_23": "Sağ kol",
        "question_2_answer_24": "Göğüs",
        "question_2_answer_25": "Sol bacak",
        "question_2_answer_26": "Sağ bacak",
        "question_3": "Saat kaçta?",
        "question_3_answer_31": "Sabah",
        "question_3_answer_32": "Gün ortası",
        "question_3_answer_33": "Öğleden sonra",
        "question_3_answer_34": "Gece",
        "question_4": "Sivrisinek sizi nerede soktu?",
        "question_4_answer_41": "Bir aracın içinde",
        "question_4_answer_42": "Bir binanın içinde",
        "question_5": "Sivrisinek sizi ne zaman soktu?",
        "question_5_answer_51": "Şimdi",
        "question_5_answer_52": "Son 24 saat içinde",
        "question_6": "Sizce ne tip bir sivrisinekti?",
        "question_6_answer_61": "İstilacı Aedes",
        "question_6_answer_62": "Sıradan sivrisinek",
        "question_6_answer_63": "Diğer",
        "question_6_answer_64": "Bilmiyorum",
        "question_7": "Sivrisinek nasıl görünüyor?",
        "question_7_answer_711": "Toraks 1",
        "question_7_answer_712": "Toraks 2",
        "question_7_answer_713": "Toraks 3",
        "question_7_answer_714": "Toraks 4",
        "question_7_answer_721": "Abdomen 1",
        "question_7_answer_722": "Abdomen 2",
        "question_7_answer_723": "Abdomen 3",
        "question_7_answer_724": "Abdomen 4",
        "question_7_answer_731": "Bacak 1",
        "question_7_answer_732": "Bacak 2",
        "question_7_answer_733": "Bacak 3",
        "question_7_answer_734": "Bacak 4",
        "question_8": "Sivrisinek sizi soktu mu?",
        "question_8_answer_81": "Hayır",
        "question_8_answer_82": "Evet",
        "question_10": "Çevrenizde su birikintisi var mı?",
        "question_10_answer_101": "Evet",
        "question_10_answer_102": "Hayır",
        "question_12": "Kamuya açık alanda ne tür bir üreme alanı buldunuz?",
        "question_12_answer_121": "Mazgal",
        "question_12_answer_122": "Diğer",
        "question_13": "Sivrisineği nerede buldunuz?",
        "question_13_answer_131": "Bir aracın içinde",
        "question_13_answer_132": "Bir binanın içinde",
        "question_13_answer_133": "Açık havada",
        "question_14": "Nerede ve ne zaman ısırıldınız?",
        "question_15": "Sivrisineği nerede buldunuz?",
        "question_16": "Üreme alanı nerede?",
        "question_4_answer_43": "Açık havada",
        "question_4_answer_44": "Bilmiyorum",
    },
    "hr": {
        "question_1": "Koliko uboda imate i gdje se nalaze na vašem tijelu?",
        "question_1_answer_11": "pitanje_1_odgovor_11",
        "question_2": "U koji dio tijela ste ubodeni?",
        "question_2_answer_21": "Glava",
        "question_2_answer_22": "Lijeva ruka",
        "question_2_answer_23": "Desna ruka",
        "question_2_answer_24": "Prsa",
        "question_2_answer_25": "Lijeva noga",
        "question_2_answer_26": "Desna noga",
        "question_3": "U koje doba dana?",
        "question_3_answer_31": "Jutro",
        "question_3_answer_32": "Sredina dana",
        "question_3_answer_33": "Poslijepodne",
        "question_3_answer_34": "Noću",
        "question_4": "Gdje ste se nalazili dok su vas boli komarci?",
        "question_4_answer_41": "U vozilu?",
        "question_4_answer_42": "U zgradi",
        "question_5": "Kad ste ubodeni?",
        "question_5_answer_51": "Upravo sada",
        "question_5_answer_52": "U posljednja 24 sata",
        "question_6": "Što mislite, koja je to bila vrsta komarca?",
        "question_6_answer_61": "Invazivni komarac",
        "question_6_answer_62": "Domaći komarac",
        "question_6_answer_63": "Druga vrsta kukca",
        "question_6_answer_64": "Ne znam",
        "question_7": "Kako izgleda komarac?",
        "question_7_answer_711": "Prsa 1",
        "question_7_answer_712": "Prsa 2",
        "question_7_answer_713": "Prsa 3",
        "question_7_answer_714": "Prsa 4",
        "question_7_answer_721": "Zadak 1",
        "question_7_answer_722": "Zadak 2",
        "question_7_answer_723": "Zadak 3",
        "question_7_answer_724": "Zadak 4",
        "question_7_answer_731": "Noga 1",
        "question_7_answer_732": "Noga 2",
        "question_7_answer_733": "Noga 3",
        "question_7_answer_734": "Noga 4",
        "question_8": "Imate li ubod komarca?",
        "question_8_answer_81": "Ne",
        "question_8_answer_82": "Da",
        "question_10": "Ima li vode u okolini?",
        "question_10_answer_101": "Da",
        "question_10_answer_102": "Ne",
        "question_12": "Kakvo leglo komaraca ste pronašli na javnoj površini?",
        "question_12_answer_121": "Slivnik",
        "question_12_answer_122": "Drugo",
        "question_13": "Gdje ste pronašli komarca?",
        "question_13_answer_131": "U vozilu",
        "question_13_answer_132": "U zgradi",
        "question_13_answer_133": "Na otvorenom",
        "question_14": "Gdje ste se nalazili kada ste bili ubodeni?",
        "question_15": "Gdje ste pronašli komarca?",
        "question_16": "Gdje se nalazi leglo komaraca?",
        "question_4_answer_43": "Na otvorenom",
        "question_4_answer_44": "Ne znam",
    },
    "de": {
        "question_1": "Wie oft wurdest du gestochen und an welchem Körperteil?",
        "question_1_answer_11": "question_1_answer_11",
        "question_2": "Wo hat sie dich gestochen?",
        "question_2_answer_21": "Kopf",
        "question_2_answer_22": "Linkter Arm",
        "question_2_answer_23": "Rechter Arm",
        "question_2_answer_24": "Brust/Bauch/Rücken",
        "question_2_answer_25": "Linkes Bein",
        "question_2_answer_26": "Rechtes Bein",
        "question_3": "Zu welcher Uhrzeit?",
        "question_3_answer_31": "Morgens",
        "question_3_answer_32": "Mittags",
        "question_3_answer_33": "Abends",
        "question_3_answer_34": "Nachts",
        "question_4": "Wo hat sie dich gestochen?",
        "question_4_answer_41": "Im Inneren eines Fahrzeugs?",
        "question_4_answer_42": "Im Inneren eines Gebäudes",
        "question_5": "Wann wurdest du gestochen?",
        "question_5_answer_51": "Gerade eben",
        "question_5_answer_52": "In den letzen 24 Stunden",
        "question_6": "Welche Stechmückenart war es deiner Meinung nach?",
        "question_6_answer_61": "Invasive Aedes",
        "question_6_answer_62": "Gemeine Hausmücke",
        "question_6_answer_63": "Andere",
        "question_6_answer_64": "Ich weiß nicht",
        "question_7": "Wie sieht die Stechmücke aus?",
        "question_7_answer_711": "Thorax 1",
        "question_7_answer_712": "Thorax 3",
        "question_7_answer_713": "Thorax 3",
        "question_7_answer_714": "Thorax 4",
        "question_7_answer_721": "Abdomen 1",
        "question_7_answer_722": "Abdomen 2",
        "question_7_answer_723": "Abdomen 3",
        "question_7_answer_724": "Abdomen 4",
        "question_7_answer_731": "Bein 1",
        "question_7_answer_732": "Bein 2",
        "question_7_answer_733": "Bein 3",
        "question_7_answer_734": "Bein 4",
        "question_8": "Hat dich die Stechmücke gebissen?",
        "question_8_answer_81": "Nein",
        "question_8_answer_82": "Ja",
        "question_10": "Ist dort Wasser?",
        "question_10_answer_101": "Ja",
        "question_10_answer_102": "Nein",
        "question_12": "Welche Art von Brutgewässer hast du in einem Öffentlichen Bereich gefunden?",
        "question_12_answer_121": "Gully",
        "question_12_answer_122": "Andere",
        "question_13": "Wo hast du die Stechmücke gefunden?",
        "question_13_answer_131": "Im Inneren eines Fahrzeugs",
        "question_13_answer_132": "In einem Gebäude",
        "question_13_answer_133": "Im Freien",
        "question_14": "Wo warst du, als du geschtochen wurdest?",
        "question_15": "Wo hast du die Stechmücke gefunden?",
        "question_16": "Wo ist die Brutstätte?",
        "question_4_answer_43": "Im Freien",
        "question_4_answer_44": "Ich weiß nicht",
    },
    "sl": {
        "question_1": "Koliko vbodov imate in kje so na telesu telesu?",
        "question_1_answer_11": "question_1answer_11",
        "question_2": "Kje so te vbodli?",
        "question_2_answer_21": "Glava",
        "question_2_answer_22": "Leva roka",
        "question_2_answer_23": "Desna roka",
        "question_2_answer_24": "Oprsje",
        "question_2_answer_25": "Leva noga",
        "question_2_answer_26": "Desna noga",
        "question_3": "Kdaj so te vbodli?",
        "question_3_answer_31": "Zjutraj",
        "question_3_answer_32": "Opoldne",
        "question_3_answer_33": "Popoldne",
        "question_3_answer_34": "Ponoči",
        "question_4": "Kje so te vbodli?",
        "question_4_answer_41": "V avtomobilu",
        "question_4_answer_42": "V stavbi",
        "question_5": "Kdaj so te vbodli?",
        "question_5_answer_51": "Pravkar",
        "question_5_answer_52": "V zadnjih 24ih urah",
        "question_6": "Kateri vrsti mislite da pripada opaženi komar?",
        "question_6_answer_61": "Invaziven komar iz rodu Aedes",
        "question_6_answer_62": "Navaden komar",
        "question_6_answer_63": "Ostalo",
        "question_6_answer_64": "Ne vem",
        "question_7": "Kako je izgledal komar?",
        "question_7_answer_711": "Oprsje 1",
        "question_7_answer_712": "Oprsje 2",
        "question_7_answer_713": "Oprsje 3",
        "question_7_answer_714": "Oprsje 4",
        "question_7_answer_721": "Zadek 1",
        "question_7_answer_722": "Zadek 1",
        "question_7_answer_723": "Zadek 3",
        "question_7_answer_724": "Zadek 4",
        "question_7_answer_731": "Noga 1",
        "question_7_answer_732": "Noga 2",
        "question_7_answer_733": "Noga 3",
        "question_7_answer_734": "Noga 4",
        "question_8": "Ali vas je komar vbodel?",
        "question_8_answer_81": "Ne",
        "question_8_answer_82": "Da",
        "question_10": "Je tam voda?",
        "question_10_answer_101": "Da",
        "question_10_answer_102": "Ne",
        "question_12": "Kakšno vrsto habitata ličink ste našli na javnem mestu?",
        "question_12_answer_121": "Odtok meteornih voda",
        "question_12_answer_122": "Ostalo",
        "question_13": "Kje ste našli komarja?",
        "question_13_answer_131": "V avtomobilu",
        "question_13_answer_132": "V stavbi",
        "question_13_answer_133": "Na prostem",
        "question_14": "Kje ste bili, ko vas je vbodel?",
        "question_15": "Kje ste našli komarja?",
        "question_16": "Kje je mesto razvoja ličink?",
        "question_4_answer_43": "Na prostem",
        "question_4_answer_44": "Ne vem",
    },
    "hu": {
        "question_1": "Mennyi csípésed van és a tested melyik részén?",
        "question_1_answer_11": "kérdés_1_válasz_11",
        "question_2": "Hol csíptek meg?",
        "question_2_answer_21": "Fej",
        "question_2_answer_22": "Bal kar",
        "question_2_answer_23": "Jobb kar",
        "question_2_answer_24": "Mellkas",
        "question_2_answer_25": "Bal láb",
        "question_2_answer_26": "Jobb láb",
        "question_3": "Mikor volt ez?",
        "question_3_answer_31": "Reggel",
        "question_3_answer_32": "Délben",
        "question_3_answer_33": "Délután",
        "question_3_answer_34": "Éjjel",
        "question_4": "Hol csíptek meg?",
        "question_4_answer_41": "Egy járműn belül?",
        "question_4_answer_42": "Egy épületen belül",
        "question_5": "Mikor csíptek meg?",
        "question_5_answer_51": "Pont most",
        "question_5_answer_52": "Az elmúlt 24 órában",
        "question_6": "Mit gondolsz milyen szúnyog volt?",
        "question_6_answer_61": "Invazív Aedes",
        "question_6_answer_62": "Közönséges szúnyog",
        "question_6_answer_63": "Egyéb",
        "question_6_answer_64": "Nem tudom",
        "question_7": "Hogy néz ki a szúnyog?",
        "question_7_answer_711": "Tor 1",
        "question_7_answer_712": "Tor 2",
        "question_7_answer_713": "Tor 3",
        "question_7_answer_714": "Tor 4",
        "question_7_answer_721": "Potroh 1",
        "question_7_answer_722": "Potroh 2",
        "question_7_answer_723": "Potroh 3",
        "question_7_answer_724": "Potroh 4",
        "question_7_answer_731": "Láb 1",
        "question_7_answer_732": "Láb 2",
        "question_7_answer_733": "Láb 3",
        "question_7_answer_734": "Láb 4",
        "question_8": "Megcsípett a szúnyog?",
        "question_8_answer_81": "Nem",
        "question_8_answer_82": "Igen",
        "question_10": "Van ott víz?",
        "question_10_answer_101": "Igen",
        "question_10_answer_102": "Nem",
        "question_12": "Milyen jellegű tenyészőhelyet talált a közterületen?",
        "question_12_answer_121": "Eső összefolyó csatorna",
        "question_12_answer_122": "Egyéb",
        "question_13": "Hol találtad a szúnyogot?",
        "question_13_answer_131": "Egy járművön belül",
        "question_13_answer_132": "Egy épületben",
        "question_13_answer_133": "Szabadtéren",
        "question_14": "Hol voltál, amikor megcsípett?",
        "question_15": "Hol találtad a szúnyogot?",
        "question_16": "Hol található a tenyészőhely?",
        "question_4_answer_43": "Szabadtér",
        "question_4_answer_44": "Nem tudom",
    },
    "mk": {
        "question_1": "Колку убоди имате и каде се наоѓаат на Вашето тело?",
        "question_1_answer_11": "question_1_answer_11",
        "question_2": "Каде Ве каснаа?",
        "question_2_answer_21": "Глава",
        "question_2_answer_22": "Лева рака",
        "question_2_answer_23": "Десна рака",
        "question_2_answer_24": "Гради",
        "question_2_answer_25": "Лева нога",
        "question_2_answer_26": "Десна нога",
        "question_3": "Кое време?",
        "question_3_answer_31": "Наутро",
        "question_3_answer_32": "Претпладне",
        "question_3_answer_33": "Попладне",
        "question_3_answer_34": "Ноќе",
        "question_4": "Каде Ве каснаа?",
        "question_4_answer_41": "Во возило?",
        "question_4_answer_42": "Во зграда",
        "question_5": "Кога бевте каснати?",
        "question_5_answer_51": "Во моментов",
        "question_5_answer_52": "Во последните 24 часа",
        "question_6": "Каков вид на комарец мислите дека беше?",
        "question_6_answer_61": "Инвазивен Aedes",
        "question_6_answer_62": "Домашен комарец",
        "question_6_answer_63": "Друго",
        "question_6_answer_64": "Не знам",
        "question_7": "Како изгледа комарецот?",
        "question_7_answer_711": "Граден кош 1",
        "question_7_answer_712": "Граден кош 2",
        "question_7_answer_713": "Граден кош 3",
        "question_7_answer_714": "Граден кош 4",
        "question_7_answer_721": "Абдомен 1",
        "question_7_answer_722": "Абдомен 2",
        "question_7_answer_723": "Абдомен 3",
        "question_7_answer_724": "Абдомен 4",
        "question_7_answer_731": "Нога 1",
        "question_7_answer_732": "Нога 2",
        "question_7_answer_733": "Нога 3",
        "question_7_answer_734": "Нога 4",
        "question_8": "Дали комарецот Ве касна?",
        "question_8_answer_81": "Не",
        "question_8_answer_82": "Да",
        "question_10": "Дали има вода?",
        "question_10_answer_101": "Да",
        "question_10_answer_102": "Не",
        "question_12": "Каков вид на место за размножување пронајдовте на јавен простор?",
        "question_12_answer_121": "Улична шахта",
        "question_12_answer_122": "Друго",
        "question_13": "Каде го најдовте комарецот?",
        "question_13_answer_131": "Внатре во возилото",
        "question_13_answer_132": "Во зграда/куќа",
        "question_13_answer_133": "Надвор",
        "question_14": "Каде се наоѓавте кога бевте каснати?",
        "question_15": "Каде го најдовте комарецот?",
        "question_16": "Каде е местото за размножување?",
        "question_4_answer_43": "Надвор",
        "question_4_answer_44": "Не знам",
    },
    "sq": {
        "question_1": "Sa herë jeni pickuar dhe në cilën pjesë të trupit?",
        "question_1_answer_11": "pyetja_1_përgjigja_11",
        "question_2": "Ku ju pickuan?",
        "question_2_answer_21": "Kokë",
        "question_2_answer_22": "Krahu majtë",
        "question_2_answer_23": "Krahu djathtë",
        "question_2_answer_24": "Kraharor",
        "question_2_answer_25": "Këmbën e majtë",
        "question_2_answer_26": "Këmbën e djathtë",
        "question_3": "Në çfarë ore?",
        "question_3_answer_31": "Mëngjes",
        "question_3_answer_32": "Mesditë",
        "question_3_answer_33": "Pasdite",
        "question_3_answer_34": "Natën",
        "question_4": "Ku ju pickuan?",
        "question_4_answer_41": "Brenda automjetit?",
        "question_4_answer_42": "Brenda një ndërtese",
        "question_5": "Kur jeni pickuar?",
        "question_5_answer_51": "Tani",
        "question_5_answer_52": "Brenda 24 orëve",
        "question_6": "Çfarë lloj mushkonje mendoni se ishte?",
        "question_6_answer_61": "Aedes invazive",
        "question_6_answer_62": "Mushkonja e zakonshme",
        "question_6_answer_63": "Të tjera",
        "question_6_answer_64": "Nuk e di",
        "question_7": "Si duket mushkonja?",
        "question_7_answer_711": "Kraharori 1",
        "question_7_answer_712": "Kraharori 2",
        "question_7_answer_713": "Kraharori 3",
        "question_7_answer_714": "Kraharori 4",
        "question_7_answer_721": "Abdomeni 1",
        "question_7_answer_722": "Abdomeni 2",
        "question_7_answer_723": "Abdomeni 3",
        "question_7_answer_724": "Abdomeni 4",
        "question_7_answer_731": "Këmba 1",
        "question_7_answer_732": "Këmba 2",
        "question_7_answer_733": "Këmba 3",
        "question_7_answer_734": "Këmba 4",
        "question_8": "A ju pickoi mushkonja?",
        "question_8_answer_81": "Jo",
        "question_8_answer_82": "Po",
        "question_10": "A ka ujë?",
        "question_10_answer_101": "Po",
        "question_10_answer_102": "Jo",
        "question_12": "Çfarë tip vendrritje nmushkonjat keni gjetur në zonat publike?",
        "question_12_answer_121": "Puseta/kanalizime",
        "question_12_answer_122": "Të tjera",
        "question_13": "Ku e gjetët mushkonjën?",
        "question_13_answer_131": "Brenda një automjeti",
        "question_13_answer_132": "Në një ndërtesë",
        "question_13_answer_133": "Në mjedis të jashtëm",
        "question_14": "Ku ishit kur u pickuat?",
        "question_15": "Ku e gjetët mushkonjën?",
        "question_16": "Ku është vendrritja e mushkonjave?",
        "question_4_answer_43": "Mjedis i jashtëm",
        "question_4_answer_44": "Nuk e di",
    },
    "sr": {
        "question_1": "Koliko uboda imate i na kom delu Vašeg tela se nalaze?",
        "question_1_answer_11": "pitanje_1_odgovor_11",
        "question_2": "Gde su Vas uboli?",
        "question_2_answer_21": "Glava",
        "question_2_answer_22": "Leva ruka",
        "question_2_answer_23": "Desna ruka",
        "question_2_answer_24": "Grudi",
        "question_2_answer_25": "Leva noga",
        "question_2_answer_26": "Desna noga",
        "question_3": "U koje vreme?",
        "question_3_answer_31": "Jutro",
        "question_3_answer_32": "Sredina dana",
        "question_3_answer_33": "Poslepodne",
        "question_3_answer_34": "Noć",
        "question_4": "Gde su Vas uboli?",
        "question_4_answer_41": "U autu?",
        "question_4_answer_42": "U zgradi/kući?",
        "question_5": "Kada ste ubodeni?",
        "question_5_answer_51": "Upravo sada",
        "question_5_answer_52": "U poslednja 24h",
        "question_6": "Koji tip komarca mislite da je to bio?",
        "question_6_answer_61": "Invazivni Aedes ",
        "question_6_answer_62": "Kućni komarac",
        "question_6_answer_63": "Drugo",
        "question_6_answer_64": "Ne znam",
        "question_7": "Kako izgleda komarac?",
        "question_7_answer_711": "Grudi 1",
        "question_7_answer_712": "Grudi 2",
        "question_7_answer_713": "Grudi 3",
        "question_7_answer_714": "Grudi 4",
        "question_7_answer_721": "Stomak 1",
        "question_7_answer_722": "Stomak 2",
        "question_7_answer_723": "Stomak 3",
        "question_7_answer_724": "Stomak 4",
        "question_7_answer_731": "Noga 1",
        "question_7_answer_732": "Noga 2",
        "question_7_answer_733": "Noga 3",
        "question_7_answer_734": "Noga 4",
        "question_8": "Da li Vas je ubo komarac?",
        "question_8_answer_81": "Ne",
        "question_8_answer_82": "Da",
        "question_10": "Da li se tu nalazi voda?",
        "question_10_answer_101": "Da",
        "question_10_answer_102": "Ne",
        "question_12": "Koji tip razvojnog staništa ste našli na javnoj površini?",
        "question_12_answer_121": "Ulični šaht",
        "question_12_answer_122": "Drugo",
        "question_13": "Gde ste našli komarca?",
        "question_13_answer_131": "U automobilu/vozilu",
        "question_13_answer_132": "U zgradi/kući",
        "question_13_answer_133": "Napolju",
        "question_14": "Gde ste se nalazili kada ste ubodeni?",
        "question_15": "Gde ste pronašli komarca?",
        "question_16": "Gde se nalazi razvojno stanište?",
        "question_4_answer_43": "Napolju",
        "question_4_answer_44": "Ne znam",
    },
    "fr": {
        "question_1": "Combien de piqûres avez-vous et où se trouvent-elles sur votre corps ?",
        "question_1_answer_11": "",
        "question_2": "Où vous ont-ils piqué ?",
        "question_2_answer_21": "Tête",
        "question_2_answer_22": "Bras gauche",
        "question_2_answer_23": "Bras droit",
        "question_2_answer_24": "Poitrine",
        "question_2_answer_25": "Jambe gauche",
        "question_2_answer_26": "Jambe droite",
        "question_3": "À quelle heure?",
        "question_3_answer_31": "Matinée",
        "question_3_answer_32": "Midi",
        "question_3_answer_33": "Après-midi",
        "question_3_answer_34": "Nuit",
        "question_4": "Où vous ont-ils piqué ?",
        "question_4_answer_41": "Dans un véhicule",
        "question_4_answer_42": "Dans un bâtiment",
        "question_5": "Quand avez-vous été piqué?",
        "question_5_answer_51": "Maintenant",
        "question_5_answer_52": "Dans les dernières 24 heures",
        "question_6": "Selon vous, de quelle espèce de moustique s'agissait-il?",
        "question_6_answer_61": "Aedes envahissant",
        "question_6_answer_62": "Moustique commun",
        "question_6_answer_63": "Autre",
        "question_6_answer_64": "Je ne sais pas",
        "question_7": "De quoi a l'air le moustique?",
        "question_7_answer_711": "Thorax 1",
        "question_7_answer_712": "Thorax 2",
        "question_7_answer_713": "Thorax 3",
        "question_7_answer_714": "Thorax 4",
        "question_7_answer_721": "Abdomen 1",
        "question_7_answer_722": "Abdomen 2",
        "question_7_answer_723": "Abdomen 3",
        "question_7_answer_724": "Abdomen 4",
        "question_7_answer_731": "Jambe 1",
        "question_7_answer_732": "Jambe 2",
        "question_7_answer_733": "Jambe 3",
        "question_7_answer_734": "Jambe 4",
        "question_8": "Le moustique vous a-t-il piqué?",
        "question_8_answer_81": "Non",
        "question_8_answer_82": "Oui",
        "question_10": "Y-a-t-il de l'eau?",
        "question_10_answer_101": "Oui",
        "question_10_answer_102": "Non",
        "question_12": "Quel type de site de reproduction avez-vous trouvé dans l'espace public ?",
        "question_12_answer_121": "Grille d'égout",
        "question_12_answer_122": "Autre",
        "question_13": "Où avez-vous trouvé le moustique?",
        "question_13_answer_131": "Dans un véhicule",
        "question_13_answer_132": "Dans un bâtiment",
        "question_13_answer_133": "À l'air libre",
        "question_14": "Où étiez-vous quand vous avez été piqué?",
        "question_15": "Où avez-vous trouvé le moustique ?",
        "question_16": "Où se trouve le site de reproduction ?",
        "question_4_answer_43": "À l'air libre",
        "question_4_answer_44": "Je ne sais pas",
    },
    "lb": {
        "question_1": "Wéivill Picküren hutt Dir a wou sinn déi un ärem Kierper?",
        "question_1_answer_11": "",
        "question_2": "Wou sidd dir gepickt ginn?",
        "question_2_answer_21": "Kapp",
        "question_2_answer_22": "Lénken Aarm",
        "question_2_answer_23": "Rietsen Aarm",
        "question_2_answer_24": "Broscht",
        "question_2_answer_25": "Lénks Been",
        "question_2_answer_26": "Riets Been",
        "question_3": "Um wéi eng Dageszäit sidd dir gepickt ginn?",
        "question_3_answer_31": "Moies",
        "question_3_answer_32": "Mëttesstonn",
        "question_3_answer_33": "Nomëttes",
        "question_3_answer_34": "Nuecht",
        "question_4": "Wou sidd dir gepickt ginn?",
        "question_4_answer_41": "An engem Gefier",
        "question_4_answer_42": "An engem Gebai",
        "question_5": "Wéini sidd Dir gepickt ginn?",
        "question_5_answer_51": "Elo just",
        "question_5_answer_52": "An de leschte 24 Stonnen",
        "question_6": "Wat fir eng Mustikenaart mengt Dir huet Iech gepickt?",
        "question_6_answer_61": "Invasiv Aedes",
        "question_6_answer_62": "Gewéinlech Hausmustik",
        "question_6_answer_63": "Aner",
        "question_6_answer_64": "Ech weess net",
        "question_7": "Wéi gesäit d'Mustik aus?",
        "question_7_answer_711": "Broscht 1",
        "question_7_answer_712": "Broscht 2",
        "question_7_answer_713": "Broscht 3",
        "question_7_answer_714": "Broscht 4",
        "question_7_answer_721": "Hannerleif 1",
        "question_7_answer_722": "Hannerleif 2",
        "question_7_answer_723": "Hannerleif 3",
        "question_7_answer_724": "Hannerleif 4",
        "question_7_answer_731": "Been 1",
        "question_7_answer_732": "Been 2",
        "question_7_answer_733": "Been 3",
        "question_7_answer_734": "Been 4",
        "question_8": "Huet d'Mustik Iech gepickt?",
        "question_8_answer_81": "Nee",
        "question_8_answer_82": "Jo",
        "question_10": "Ass Waasser do?",
        "question_10_answer_101": "Yo",
        "question_10_answer_102": "Nee",
        "question_12": "Wat fir eng Zort Bruttplaz hutt Dir am ëffentleche Raum fonnt?",
        "question_12_answer_121": "Gulli",
        "question_12_answer_122": "Aner",
        "question_13": "Wou hutt Dir d'Mustik fonnt?",
        "question_13_answer_131": "An engem Gefier",
        "question_13_answer_132": "An engem Gebai",
        "question_13_answer_133": "Dobaussen",
        "question_14": "Wou waard Dir wéi Dir gepickt gouft?",
        "question_15": "Wou hutt Dir d'Mustik fonnt?",
        "question_16": "Wou ass d'Bruttplaz?",
        "question_4_answer_43": "Dobaussen",
        "question_4_answer_44": "Ech weess net",
    },
    "ro": {
        "question_1": "Câte înțepături aveți și unde sunt localizate pe corp?",
        "question_1_answer_11": "",
        "question_2": "Unde aveți înțepături?",
        "question_2_answer_21": "Cap",
        "question_2_answer_22": "Mâna stângă",
        "question_2_answer_23": "Mâna dreaptă",
        "question_2_answer_24": "Piept",
        "question_2_answer_25": "Piciorul stâng",
        "question_2_answer_26": "Piciorul drept",
        "question_3": "În ce perioadă a zilei?",
        "question_3_answer_31": "Dimineața",
        "question_3_answer_32": "Miezul zilei",
        "question_3_answer_33": "După amiaza",
        "question_3_answer_34": "Noaptea",
        "question_4": "Unde v-au înțepat?",
        "question_4_answer_41": "În mașină?",
        "question_4_answer_42": "În interiorul unei clădiri",
        "question_5": "Când ați fost înțepat?",
        "question_5_answer_51": "Chiar acum",
        "question_5_answer_52": "În ultimele 24 de ore",
        "question_6": "Ce fel de țânțar credeți că a fost?",
        "question_6_answer_61": "Aedes invaziv",
        "question_6_answer_62": "Țânțar comun",
        "question_6_answer_63": "Alt tip",
        "question_6_answer_64": "Nu știu",
        "question_7": "Cum arăta țânțarul?",
        "question_7_answer_711": "Torace 1",
        "question_7_answer_712": "Torace 2",
        "question_7_answer_713": "Torace 3",
        "question_7_answer_714": "Torace 4",
        "question_7_answer_721": "Abdomen 1",
        "question_7_answer_722": "Abdomen 2",
        "question_7_answer_723": "Abdomen 3",
        "question_7_answer_724": "Abdomen 4",
        "question_7_answer_731": "Picior 1",
        "question_7_answer_732": "Picior 2",
        "question_7_answer_733": "Picior 3",
        "question_7_answer_734": "Picior 4",
        "question_8": "V-a înțepat țânțarul?",
        "question_8_answer_81": "Nu",
        "question_8_answer_82": "Da",
        "question_10": "Este apă în apropiere?",
        "question_10_answer_101": "Da",
        "question_10_answer_102": "Nu",
        "question_12": "Ce fel de loc de reproducere ați găsit într-un loc public?",
        "question_12_answer_121": "Sistem de scurgere în caz de furtună",
        "question_12_answer_122": "Altceva",
        "question_13": "Unde ați găsit țânțarul?",
        "question_13_answer_131": "În interiorul unui vehicul",
        "question_13_answer_132": "Într-o clădire",
        "question_13_answer_133": "În aer liber",
        "question_14": "Unde ați fost înțepați?",
        "question_15": "Unde ați găsit țânțarul?",
        "question_16": "Unde este locul de reproducere?",
        "question_4_answer_43": "Afară",
        "question_4_answer_44": "Nu știu",
    },
    "nl": {
        "question_1": "Hoeveel muggenbeten heeft u en waar bevinden ze zich op uw lichaam?",
        "question_1_answer_11": "vraag_1_antwoord_11",
        "question_2": "Waar bent u gebeten?",
        "question_2_answer_21": "Hoofd",
        "question_2_answer_22": "Linker arm",
        "question_2_answer_23": "Rechter arm",
        "question_2_answer_24": "Romp",
        "question_2_answer_25": "Linker been",
        "question_2_answer_26": "Rechter been",
        "question_3": "Op welk moment van de dag?",
        "question_3_answer_31": "Ochtend",
        "question_3_answer_32": "Middag",
        "question_3_answer_33": "Namiddag",
        "question_3_answer_34": "Nacht",
        "question_4": "Waar bent u gebeten?",
        "question_4_answer_41": "In een voertuig",
        "question_4_answer_42": "In een gebouw",
        "question_5": "Wanneer bent u gebeten?",
        "question_5_answer_51": "Nu net",
        "question_5_answer_52": "In de afgelopen 24 uur",
        "question_6": "Welk type mug denkt u dat het was?",
        "question_6_answer_61": "Invasieve Aedes",
        "question_6_answer_62": "Algemene mug",
        "question_6_answer_63": "Anders",
        "question_6_answer_64": "Weet ik niet",
        "question_7": "Hoe ziet de mug eruit?",
        "question_7_answer_711": "Borststuk 1",
        "question_7_answer_712": "Borststuk 2",
        "question_7_answer_713": "Borststuk 3",
        "question_7_answer_714": "Borststuk 4",
        "question_7_answer_721": "Achterlijf 1",
        "question_7_answer_722": "Achterlijf 2",
        "question_7_answer_723": "Achterlijf 3",
        "question_7_answer_724": "Achterlijf 4",
        "question_7_answer_731": "Poot 1",
        "question_7_answer_732": "Poot 2",
        "question_7_answer_733": "Poot 3",
        "question_7_answer_734": "Poot 4",
        "question_8": "Bent u door de mug gebeten?",
        "question_8_answer_81": "Nee",
        "question_8_answer_82": "Ja",
        "question_10": "Is er water in de buurt?",
        "question_10_answer_101": "Ja",
        "question_10_answer_102": "Nee",
        "question_12": "Welk type broedplaats heeft u aangetroffen in een openbare ruimte?",
        "question_12_answer_121": "Afvoerput",
        "question_12_answer_122": "Anders",
        "question_13": "Waar heeft u de mug aangetroffen?",
        "question_13_answer_131": "In een voortuig",
        "question_13_answer_132": "In een gebouw",
        "question_13_answer_133": "Buiten",
        "question_14": "Waar was u toen u werd gebeten?",
        "question_15": "Waar heeft u de mug aangetroffen?",
        "question_16": "Waar is de broedplaats",
        "question_4_answer_43": "Buiten",
        "question_4_answer_44": "Ik weet het niet",
    },
    "bg": {
        "question_1": "Колко ухапвания имате и по коя част на тялото?",
        "question_1_answer_11": "",
        "question_2": "Къде бяхте ухапани?",
        "question_2_answer_21": "Глава",
        "question_2_answer_22": "Лява ръка",
        "question_2_answer_23": "Дясна ръка",
        "question_2_answer_24": "Гърди",
        "question_2_answer_25": "Ляв крак",
        "question_2_answer_26": "Десен крак",
        "question_3": "По кое време на деня?",
        "question_3_answer_31": "Сутрин",
        "question_3_answer_32": "По обяд",
        "question_3_answer_33": "След обяд",
        "question_3_answer_34": "Нощем",
        "question_4": "Къде бяхте ухапани?",
        "question_4_answer_41": "Вътре в превозно средство",
        "question_4_answer_42": "Вътре в помещение",
        "question_5": "Кога бяхте ухапани?",
        "question_5_answer_51": "Преди малко",
        "question_5_answer_52": "През последните 24 часа",
        "question_6": "Какъв вид комар смятате, че беше?",
        "question_6_answer_61": "Инвазивен Aedes",
        "question_6_answer_62": "Обикновен комар",
        "question_6_answer_63": "Друг",
        "question_6_answer_64": "Не знам",
        "question_7": "Как изглежда комарът?",
        "question_7_answer_711": "Гърди 1",
        "question_7_answer_712": "Гърди 2",
        "question_7_answer_713": "Гърди 3",
        "question_7_answer_714": "Гърди 4",
        "question_7_answer_721": "Коремче 1",
        "question_7_answer_722": "Коремче 2",
        "question_7_answer_723": "Коремче 3",
        "question_7_answer_724": "Коремче 4",
        "question_7_answer_731": "Крак 1",
        "question_7_answer_732": "Крак 2",
        "question_7_answer_733": "Крак 3",
        "question_7_answer_734": "Крак 4",
        "question_8": "Комарът ухапа ли Ви?",
        "question_8_answer_81": "Не",
        "question_8_answer_82": "Да",
        "question_10": "Има ли вода?",
        "question_10_answer_101": "Да",
        "question_10_answer_102": "Не",
        "question_12": "Какъв тип развъдно място открихте на обществено място?",
        "question_12_answer_121": "Дъждовна канализация",
        "question_12_answer_122": "Друго",
        "question_13": "Къде открихте комара?",
        "question_13_answer_131": "Вътре в превозно средство",
        "question_13_answer_132": "Вътре в помещение",
        "question_13_answer_133": "На открито",
        "question_14": "Къде бяхте, когато бяхте ухапани?",
        "question_15": "Къде открихте комара?",
        "question_16": "Къде е развъдното място?",
        "question_4_answer_43": "На открито",
        "question_4_answer_44": "Не знам",
    },
    "pt": {
        "question_1": "Quantas picadas tens e em que parte do corpo?",
        "question_1_answer_11": "questão_1_resposta_11",
        "question_2": "Onde te picaram?",
        "question_2_answer_21": "Cabeça",
        "question_2_answer_22": "Braço esquerdo",
        "question_2_answer_23": "Braço direito",
        "question_2_answer_24": "Peito",
        "question_2_answer_25": "Perna esquerda",
        "question_2_answer_26": "Perna direita",
        "question_3": "Em que período foi?",
        "question_3_answer_31": "Manhã",
        "question_3_answer_32": "Meio dia",
        "question_3_answer_33": "Tarde",
        "question_3_answer_34": "Noite",
        "question_4": "Onde te picaram?",
        "question_4_answer_41": "Dentro de um veículo",
        "question_4_answer_42": "Dentro de um edifício",
        "question_5": "Quando te picaram?",
        "question_5_answer_51": "Agora mesmo",
        "question_5_answer_52": "Nas últimas 24h",
        "question_6": "Que tipo de mosquito acha que é?",
        "question_6_answer_61": "Aedes invasor",
        "question_6_answer_62": "Mosquito comum",
        "question_6_answer_63": "Outro",
        "question_6_answer_64": "Não sei",
        "question_7": "Como é o mosquito?",
        "question_7_answer_711": "Tórax 1",
        "question_7_answer_712": "Tórax 2",
        "question_7_answer_713": "Tórax 3",
        "question_7_answer_714": "Tórax 4",
        "question_7_answer_721": "Abdómen 1",
        "question_7_answer_722": "Abdómen 2",
        "question_7_answer_723": "Abdómen 3",
        "question_7_answer_724": "Abdómen 4",
        "question_7_answer_731": "Pata 1",
        "question_7_answer_732": "Pata 2",
        "question_7_answer_733": "Pata 3",
        "question_7_answer_734": "Pata 4",
        "question_8": "O mosquito picou-te?",
        "question_8_answer_81": "Não",
        "question_8_answer_82": "Sim",
        "question_10": "Tem água?",
        "question_10_answer_101": "Sim",
        "question_10_answer_102": "Não",
        "question_12": "Como é o criadouro detetado na via pública?",
        "question_12_answer_121": "Drenagem",
        "question_12_answer_122": "Outro tipo",
        "question_13": "Onde encontraste o mosquito?",
        "question_13_answer_131": "Dentro de um veículo",
        "question_13_answer_132": "Dentro de um edifício",
        "question_13_answer_133": "No exterior",
        "question_14": "Onde estava quando foi picado?",
        "question_15": "Onde encontrou o mosquito?",
        "question_16": "Onde se encontra o criadouro?",
        "question_4_answer_43": "No exterior",
        "question_4_answer_44": "Não sei",
    }
}
