# Generated by Django 4.2.29 on 2026-03-24 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_tigauser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tigaserver_app', '0102_remove_notification_expert_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='NotificationContent',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('body_html_es', models.TextField(blank=True, default=None, help_text='Expert comment, expanded and allows html, in spanish', null=True)),
                        ('body_html_ca', models.TextField(blank=True, default=None, help_text='Expert comment, expanded and allows html, in catalan', null=True)),
                        ('body_html_en', models.TextField(blank=True, default=None, help_text='Expert comment, expanded and allows html, in english', null=True)),
                        ('title_es', models.TextField(blank=True, default=None, help_text='Title of the comment, shown in non-detail view, in spanish', null=True)),
                        ('title_ca', models.TextField(blank=True, default=None, help_text='Title of the comment, shown in non-detail view, in catalan', null=True)),
                        ('title_en', models.TextField(blank=True, default=None, help_text='Title of the comment, shown in non-detail view, in english', null=True)),
                        ('body_html_native', models.TextField(blank=True, default=None, help_text='Expert comment, expanded and allows html, in the language indicated by the field native_locale', null=True)),
                        ('title_native', models.TextField(blank=True, default=None, help_text='Title of the comment, shown in non-detail view, in the language indicated by the field title_native', null=True)),
                        ('native_locale', models.CharField(blank=True, default=None, help_text='Locale code for text in body_html_native and title_native', max_length=10, null=True)),
                        ('notification_label', models.CharField(blank=True, default=None, help_text='Arbitrary label used to group thematically equal notifications. Optional. ', max_length=255, null=True)),
                        ('predefined_available_to', models.ForeignKey(blank=True, help_text='If this field is not null, this notification is predefined - the predefined map notifications will go here. This field indicates the expert to which the notification is available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predefined_notifications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'tigaserver_app_notificationcontent',
                    },
                ),
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date_comment', models.DateTimeField(auto_now_add=True)),
                        ('expert_comment', models.TextField(help_text='Text message sent to user', verbose_name='Expert comment')),
                        ('expert_html', models.TextField(help_text='Expanded message information goes here. This field can contain HTML', verbose_name='Expert comment, expanded and allows html')),
                        ('photo_url', models.TextField(blank=True, help_text='Relative url to the public report photo', null=True, verbose_name='Url to picture that originated the comment')),
                        ('public', models.BooleanField(default=False, help_text='Whether the notification is shown in the public map or not')),
                        ('acknowledged', models.BooleanField(default=False, help_text='This is set to True through the public API, when the user signals that the message has been received')),
                        ('expert', models.ForeignKey(blank=True, help_text='Expert sending the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_notifications', to=settings.AUTH_USER_MODEL)),
                        ('notification_content', models.ForeignKey(blank=True, help_text='Multi language content of the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_content', to='notifications.notificationcontent')),
                        ('report', models.ForeignKey(blank=True, help_text='Report regarding the current notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_notifications', to='tigaserver_app.report')),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tigauser')),
                    ],
                    options={
                        'db_table': 'tigaserver_app_notification',
                    },
                ),
                migrations.CreateModel(
                    name='NotificationTopic',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('topic_code', models.CharField(help_text='Code for the topic.', max_length=100, unique=True)),
                        ('topic_description', models.TextField(help_text='Description for the topic, in english.')),
                        ('topic_group', models.IntegerField(choices=[(0, 'General'), (1, 'Language topics'), (2, 'Country topics'), (3, 'Country nuts3'), (4, 'Country nuts2'), (5, 'Special')], default=0, help_text='Your degree of belief that at least one photo shows a tiger mosquito breeding site', verbose_name='Group of topics')),
                    ],
                    options={
                        'db_table': 'tigaserver_app_notificationtopic',
                    },
                ),
                migrations.CreateModel(
                    name='SentNotification',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('notification', models.ForeignKey(help_text='The notification which has been sent', on_delete=django.db.models.deletion.CASCADE, related_name='notification_sendings', to='notifications.notification')),
                        ('sent_to_topic', models.ForeignKey(blank=True, help_text='Topic to which the notification was sent.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_sentnotifications', to='notifications.notificationtopic')),
                        ('sent_to_user', models.ForeignKey(blank=True, help_text='User to which the notification was sent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sentnotifications', to='users.tigauser')),
                    ],
                    options={
                        'db_table': 'tigaserver_app_sentnotification',
                    },
                ),
                migrations.CreateModel(
                    name='UserSubscription',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('topic', models.ForeignKey(help_text='Topics to which the user is subscribed', on_delete=django.db.models.deletion.CASCADE, related_name='topic_users', to='notifications.notificationtopic')),
                        ('user', models.ForeignKey(help_text='User which is subscribed to the topic', on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='users.tigauser')),
                    ],
                    options={
                        'db_table': 'tigaserver_app_usersubscription',
                        'unique_together': {('user', 'topic')},
                    },
                ),
                migrations.CreateModel(
                    name='AcknowledgedNotification',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('notification', models.ForeignKey(help_text='The notification which has been acknowledged or not', on_delete=django.db.models.deletion.CASCADE, related_name='notification_acknowledgements', to='notifications.notification')),
                        ('user', models.ForeignKey(help_text='User which has acknowledged the notification', on_delete=django.db.models.deletion.CASCADE, related_name='user_acknowledgements', to='users.tigauser')),
                    ],
                    options={
                        'db_table': 'tigaserver_app_acknowledgednotification',
                        'unique_together': {('user', 'notification')},
                    },
                ),
            ]
        )
    ]
