# Generated by Django 4.2.29 on 2026-03-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Report regarding the current notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_notifications', to='reports.report'),
        ),
    ]
