# Generated by Django 4.0.8 on 2023-01-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
