# Generated by Django 4.2.29 on 2026-04-02 10:19

from django.db import migrations, models


def populate_notificationcontent(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    NotificationContent = apps.get_model("notifications", "NotificationContent")

    old_notifications_with_message = Notification.objects.filter(
        notification_content__isnull=True,
    ).exclude(
        models.Q(expert_comment__isnull=True)
        | models.Q(expert_comment__exact='')
        | models.Q(expert_html__isnull=True)
        | models.Q(expert_html__exact='')
    )
    for notification in old_notifications_with_message.iterator():
        notification_content = NotificationContent.objects.create(
            title_en=notification.expert_comment,
            body_html_en=notification.expert_html,
        )
        notification.notification_content = notification_content
        notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationrecipient'),
    ]

    operations = [
        migrations.RunPython(populate_notificationcontent, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='notification',
            name='expert_comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='expert_html',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='photo_url',
        ),
    ]
