# Generated by Django 4.2.29 on 2026-04-02 10:19

from django.db import migrations, models


def delete_notification_without_notificationcontent(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")

    Notification.objects.filter(
        notification_content__isnull=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_populate_notificationcontent_from_notification'),
    ]

    operations = [
        migrations.RunPython(delete_notification_without_notificationcontent, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notification',
            name='notification_content',
            field=models.ForeignKey(help_text='Multi language content of the notification', on_delete=models.deletion.PROTECT, related_name='notification_content', to='notifications.notificationcontent'),
        )
    ]
