# Generated by Django 4.2.29 on 2026-04-02 10:19

from django.db import migrations


def populate_notification_recipient(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    AcknowledgedNotification = apps.get_model("notifications", "AcknowledgedNotification")
    NotificationRecipient = apps.get_model("notifications", "NotificationRecipient")

    bulk_recipients = []
    old_notifications_assignation = Notification.objects.filter(
        user__isnull=False
    ).exclude(user='00000000-0000-0000-0000-000000000000')
    for notification in old_notifications_assignation.iterator():
        bulk_recipients.append(
            NotificationRecipient(
                notification_id=notification.id,
                user_id=notification.user_id,
                is_read=notification.acknowledged or AcknowledgedNotification.objects.filter(
                    notification_id=notification.id,
                    user_id=notification.user_id,
                ).exists()
            )
        )

    NotificationRecipient.objects.bulk_create(bulk_recipients, batch_size=2000, ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_made_notification_content_required'),
    ]

    operations = [
        migrations.RunPython(populate_notification_recipient, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='acknowledged',
        ),
    ]
