# Generated by Django 4.2.29 on 2026-04-02 10:19

from django.db import migrations, models


def populate_notification_recipient(apps, schema_editor):
    AcknowledgedNotification = apps.get_model("notifications", "AcknowledgedNotification")
    SentNotification = apps.get_model("notifications", "SentNotification")
    NotificationRecipient = apps.get_model("notifications", "NotificationRecipient")

    bulk_recipients = []
    sent_notifications = SentNotification.objects.filter(
        sent_to_user__isnull=False
    ).annotate(
        is_read=models.Exists(
            AcknowledgedNotification.objects.filter(
                notification=models.OuterRef("notification_id"),
                user=models.OuterRef("sent_to_user_id"),
            )
        )
    )
    for sendings in sent_notifications.iterator():
        bulk_recipients.append(
            NotificationRecipient(
                notification_id=sendings.notification_id,
                user_id=sendings.sent_to_user_id,
                is_read=sendings.is_read
            )
        )

    NotificationRecipient.objects.bulk_create(bulk_recipients, batch_size=2000, ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_populate_notificationrecipient_from_notification'),
    ]

    operations = [
        migrations.RunPython(populate_notification_recipient, reverse_code=migrations.RunPython.noop),
    ]
