# Generated by Django 4.2.29 on 2026-04-02 10:19

from django.db import migrations, models


def populate_notification_recipient(apps, schema_editor):
    AcknowledgedNotification = apps.get_model("notifications", "AcknowledgedNotification")
    SentNotification = apps.get_model("notifications", "SentNotification")
    NotificationRecipient = apps.get_model("notifications", "NotificationRecipient")
    NotificationRecipientTopic = apps.get_model("notifications", "NotificationRecipient_through_topics")
    TigaUser = apps.get_model("users", "TigaUser")

    sent_notifications = SentNotification.objects.filter(
        sent_to_topic__isnull=False
    ).select_related("notification")
    for sendings in sent_notifications.iterator():
        bulk_recipients = []
        bulk_recipients_through_topics = []
        topic_users_qs = TigaUser.objects.filter(
            user_subscriptions__topic_id=sendings.sent_to_topic_id,
            registration_time__lte=sendings.notification.date_comment
        ).annotate(
            has_read_notification=models.Exists(
                AcknowledgedNotification.objects.filter(
                    notification_id=sendings.notification_id,
                    user=models.OuterRef("pk"),
                )
            )
        )
        for user in topic_users_qs.iterator():
            bulk_recipients.append(
                NotificationRecipient(
                    notification_id=sendings.notification_id,
                    user=user,
                    is_read=user.has_read_notification
                )
        )
        recipients = NotificationRecipient.objects.bulk_create(bulk_recipients, batch_size=2000)
        for recipient in recipients:
            bulk_recipients_through_topics.append(
                NotificationRecipientTopic(
                    notificationrecipient_id=recipient.pk,
                    notificationtopic_id=sendings.sent_to_topic_id,
                )
            )

        NotificationRecipientTopic.objects.bulk_create(bulk_recipients_through_topics, batch_size=2000, ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_populate_notificationrecipient_from_sentnotification'),
    ]

    operations = [
        migrations.RunPython(populate_notification_recipient, reverse_code=migrations.RunPython.noop),
    ]
