# Generated by Django 4.2.29 on 2026-04-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_populate_notificationrecipient_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcknowledgedNotification',
        ),
        migrations.DeleteModel(
            name='SentNotification',
        ),
    ]
