# Generated by Django 4.2.29 on 2026-04-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_remove_sentnotification_acknowledgednotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='public',
        ),
    ]
