# Generated by Django 4.2.29 on 2026-04-08 10:19

from django.db import migrations, models
from modeltranslation.utils import build_localized_fieldname

def populate_title_and_body_html(apps, schema_editor):
    NotificationContent = apps.get_model('notifications', 'NotificationContent')

    available_native_locale = NotificationContent.objects.filter(
        native_locale__isnull=False
    ).values_list("native_locale", flat=True).distinct()

    for native_locale in available_native_locale:
        NotificationContent.objects.filter(native_locale=native_locale).update(**{
            build_localized_fieldname("title", native_locale): models.F("title_native"),
            build_localized_fieldname("body_html", native_locale): models.F("body_html_native"),
        })


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_remove_notificationcontent_body_html_native_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_title_and_body_html, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='notificationcontent',
            name='body_html_native',
        ),
        migrations.RemoveField(
            model_name='notificationcontent',
            name='native_locale',
        ),
        migrations.RemoveField(
            model_name='notificationcontent',
            name='title_native',
        ),
    ]
