# Generated by Django 4.2.30 on 2026-07-06 14:24

from django.db import migrations, models
import mosquito_alert.utils.json


def populate_audience(apps, schema_editor):
    pass


def reverse_populate_audience(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_remove_notificationcontent_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.JSONField(blank=True, decoder=mosquito_alert.utils.json.DjangoGEOJSONDecoder, encoder=mosquito_alert.utils.json.DjangoGEOJSONEncoder,
                                   help_text='Criteria used to select recipients. It is the audience filter for the notification, in django ORM filter format', null=True),
        ),
        # migrations.RunPython(
        #     populate_audience,
        #     reverse_code=reverse_populate_audience
        # )
    ]
