# Generated by Django 4.2.30 on 2026-07-06 14:24

from django.db import migrations, models
import mosquito_alert.utils.json


def populate_audience(apps, schema_editor):
    NotificationTopic = apps.get_model('notifications', 'NotificationTopic')
    Notification = apps.get_model('notifications', 'Notification')
    Country = apps.get_model('geo', 'Country')
    NutsEurope = apps.get_model('geo', 'NutsEurope')

    notifications_to_update = []
    for topic in NotificationTopic.objects.filter(notificationrecipient__isnull=False).distinct('pk'):
        audience = None
        if topic.topic_group == 1:
            audience = {"locale": topic.topic_code}
        elif topic.topic_group == 2:
            audience = {"last_location__within": Country.objects.get(pk=topic.topic_code).geom}
        elif topic.topic_group == 3:
            audience = {"last_location__within": NutsEurope.objects.get(nuts_id=topic.topic_code, levl_code=3).geom}
        elif topic.topic_group == 4:
            audience = {"last_location__within": NutsEurope.objects.get(nuts_id=topic.topic_code, levl_code=2).geom}
        elif topic.topic_group == 5:
            audience = {}

        notification_qs = Notification.objects.filter(notificationrecipient__through_topics=topic).distinct('pk')
        for notification in notification_qs.iterator():
            notification.audience = audience
            notifications_to_update.append(notification)

    Notification.objects.bulk_update(notifications_to_update, ['audience'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_remove_notificationcontent_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.JSONField(blank=True, decoder=mosquito_alert.utils.json.DjangoGEOJSONDecoder, encoder=mosquito_alert.utils.json.DjangoGEOJSONEncoder,
                                   help_text='Criteria used to select recipients. It is the audience filter for the notification, in django ORM filter format', null=True),
        ),
        migrations.RunPython(
            populate_audience,
            reverse_code=migrations.RunPython.noop
        )
    ]
