# Generated by Django 4.2.30 on 2026-07-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_notification_audience'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notificationrecipient',
            name='through_topics',
        ),
        migrations.DeleteModel(
            name='NotificationTopic',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
